<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="amd.20150913232631.1"><vh>@settings</vh>
<v t="amd.20150913232631.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="amd.20150913232631.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20150919102739.1"><vh>專案架構</vh>
<v t="amd.20150919113520.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20151007224830.1"><vh>Jupyter 安裝與執行</vh></v>
<v t="amd.20150919103357.1"><vh>pelican 設定</vh></v>
</v>
<v t="amd.20151029230307.1"><vh>Leo 範例程式</vh></v>
<v t="amd.20150919113957.1"><vh>以下為 pelican 文章</vh>
<v t="amd.20151021120245.1"><vh>@button admin pelican</vh></v>
<v t="amd.20150919124128.1"><vh>@button user pelican</vh></v>
<v t="amd.20150919114010.1"><vh>@path pelican</vh>
<v t="amd.20151006130205.1"><vh>@edit publishconf.py</vh></v>
<v t="amd.20151006113136.1"><vh>@path content</vh>
<v t="amd.20150919114035.1"><vh>@edit 2015cphww1.md</vh></v>
<v t="amd.20151029231142.1"><vh>@edit 2015cphww7.md</vh></v>
<v t="amd.20150920000911.1"><vh>@edit 2015cpnote1.md</vh></v>
</v>
</v>
</v>
<v t="amd.20150919120205.1"><vh>以下為 reveal 投影片</vh>
<v t="amd.20150915211341.1"><vh>@clean simplest.html</vh>
<v t="amd.20150917085040.1"><vh>檔案說明</vh></v>
<v t="amd.20150915211351.1"><vh>html 標註</vh>
<v t="amd.20150915211351.4"><vh>body 標註</vh>
<v t="amd.20150915211351.5"><vh>div class="reveal"</vh>
<v t="amd.20150915211351.6"><vh>div class="slides"</vh>
<v t="amd.20150915211351.7"><vh>有關我的作業</vh></v>
<v t="amd.20150915211351.9"><vh>作業任務一</vh></v>
<v t="amd.20150915211351.12"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="amd.20150915211351.15"><vh>script</vh></v>
</v>
</v>
</v>
</v>
<v t="amd.20151021113722.1"><vh>@path plugin</vh>
<v t="amd.20151021113731.1"><vh>@path liquid_tags</vh>
<v t="amd.20151021113745.1"><vh>@edit notebook.py</vh></v>
</v>
</v>
<v t="amd.20151021114454.1" a="E"><vh>@path user</vh>
<v t="leo.20151112140837.1"><vh>@path 40323101</vh>
<v t="leo.20151112140837.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151112140837.3"><vh>@edit 40323101_cp_w1_p.html</vh></v>
<v t="leo.20151112140837.4"><vh>@edit 40323101_cp_w2_p.html</vh></v>
<v t="leo.20151112140837.5"><vh>@edit 40323101_cp_w3_p.html</vh></v>
<v t="leo.20151112140837.6"><vh>@edit 40323101_cp_w4_p.html</vh></v>
<v t="leo.20151112140837.7"><vh>@edit 40323101_cp_w5_p.html</vh></v>
<v t="leo.20151112140837.8"><vh>@edit 40323101_cp_w6_p.html</vh></v>
<v t="leo.20151112140837.9"><vh>@edit 40323101_cp_w7_p.html</vh></v>
<v t="leo.20151112140837.10"><vh>@edit 40323101_cp_w8_p.html</vh></v>
<v t="leo.20151112140837.11" a="E"><vh>@path pelican</vh>
<v t="leo.20151112140837.12"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151112140837.13"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151112140837.14" a="E"><vh>@path content</vh>
<v t="leo.20151112140837.15"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151112140837.16"><vh>@edit 40323101_cp_w1.md</vh></v>
<v t="leo.20151112140837.17"><vh>@edit 40323101_cp_w2.md</vh></v>
<v t="leo.20151112140837.18"><vh>@edit 40323101_cp_w3.md</vh></v>
<v t="leo.20151112140837.19"><vh>@edit 40323101_cp_w4.md</vh></v>
<v t="leo.20151112140837.20"><vh>@edit 40323101_cp_w5.md</vh></v>
<v t="leo.20151112140837.21"><vh>@edit 40323101_cp_w6.md</vh></v>
<v t="leo.20151112140837.22"><vh>@edit 40323101_cp_w7.md</vh></v>
<v t="leo.20151112140837.23"><vh>@edit 40323101_cp_w8.md</vh></v>
</v>
</v>
</v>
<v t="amd.20151021114529.1"><vh>各組員必須自行建立 以下節點</vh></v>
<v t="leo.20151108102259.1"><vh>@path 40323124</vh>
<v t="leo.20151108102259.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151108102259.3"><vh>@edit 40323124_cp_w1_p.html</vh></v>
<v t="leo.20151108102259.4"><vh>@path pelican</vh>
<v t="leo.20151108102259.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151108102259.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151108102259.7" a="E"><vh>@path content</vh>
<v t="leo.20151108102259.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151108102259.9"><vh>@edit 40323124_cp_w1.md</vh></v>
</v>
</v>
</v>
<v t="123.20151029141051.1" a="E"><vh>@path 40323115</vh>
<v t="123.20151029141051.2"><vh>以下為投影片 ------------</vh></v>
<v t="123.20151105202522.1"><vh>@edit 40323115_cp_w1_p.html</vh></v>
<v t="123.20151029141051.4" a="E"><vh>@path pelican</vh>
<v t="123.20151029141051.5"><vh>以下為設定檔 ------------</vh></v>
<v t="123.20151029141051.6"><vh>@edit publishconf.py</vh></v>
<v t="123.20151029141051.7"><vh>@path content</vh>
<v t="123.20151029141051.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="123.20151029141051.9"><vh>@edit 40323115_cp_w1.md</vh></v>
<v t="123.20151105195756.1"><vh>@edit 40323115_cp_w2.md</vh></v>
<v t="123.20151105195933.1"><vh>@edit 40323115_cp_w3.md</vh></v>
<v t="123.20151105195935.1"><vh>@edit 40323115_cp_w4.md</vh></v>
<v t="123.20151105195938.1"><vh>@edit 40323115_cp_w5.md</vh></v>
<v t="123.20151105200243.1"><vh>@edit 40323115_cp_w6.md</vh></v>
<v t="123.20151105200245.1"><vh>@edit 40323115_cp_w7.md</vh></v>
<v t="123.20151105200247.1"><vh>@edit 40323115_cp_w8.md</vh></v>
</v>
</v>
</v>
<v t="123.20151029151348.1"><vh>@path 40323154</vh>
<v t="123.20151029151348.2"><vh>以下為投影片 ------------</vh></v>
<v t="123.20151029151348.3"><vh>@edit 40323154_cp_w1_p.html</vh></v>
<v t="123.20151029151348.4"><vh>@path pelican</vh>
<v t="123.20151029151348.6"><vh>@edit publishconf.py</vh></v>
<v t="123.20151029151348.5"><vh>以下為設定檔 ------------</vh></v>
<v t="123.20151029151348.7" a="E"><vh>@path content</vh>
<v t="123.20151029151348.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="123.20151029151348.9"><vh>@edit 40323154_cp_w1.md</vh></v>
<v t="123.20151029154939.1"><vh>@edit 2015cpnote1.md</vh></v>
<v t="123.20151029154804.1"><vh>@edit 2015cphww1.md</vh></v>
</v>
</v>
</v>
<v t="123.20151022140839.1"><vh>@path 40323150</vh>
<v t="123.20151022140839.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151110011610.1" a="E"><vh>@clean simplest.html</vh>
<v t="leo.20151110011610.2"><vh>檔案說明</vh></v>
<v t="leo.20151110011610.3" a="E"><vh>html 標註</vh>
<v t="leo.20151110011610.4" a="E"><vh>body 標註</vh>
<v t="leo.20151110011610.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151110011610.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151110011610.7"><vh>封面</vh></v>
<v t="leo.20151110011610.8"><vh>目錄</vh></v>
<v t="leo.20151110011610.9" a="E"><vh>list</vh>
<v t="leo.20151110011610.10"><vh>1</vh></v>
<v t="leo.20151110011610.11"><vh>2</vh></v>
<v t="leo.20151110011610.12"><vh>3</vh></v>
<v t="leo.20151110011610.13"><vh>4</vh></v>
<v t="leo.20151110011610.14"><vh>5</vh></v>
<v t="leo.20151110011610.15"><vh>6</vh></v>
<v t="leo.20151110011610.16"><vh>7</vh></v>
<v t="leo.20151110011610.17"><vh>8</vh></v>
<v t="leo.20151110033440.1"><vh>vid</vh></v>
</v>
<v t="leo.20151110011610.18"><vh>W1</vh></v>
<v t="leo.20151110011610.19"><vh>W2</vh></v>
<v t="leo.20151110011610.20"><vh>W3</vh></v>
<v t="leo.20151110011610.21"><vh>W4</vh></v>
<v t="leo.20151110011610.22"><vh>W5</vh></v>
<v t="leo.20151110011610.23"><vh>W6</vh></v>
<v t="leo.20151110011610.24"><vh>W7</vh></v>
<v t="leo.20151110011610.25"><vh>W8</vh></v>
<v t="leo.20151110011610.26"><vh>影片</vh></v>
<v t="leo.20151110011610.27"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20151110011610.28"><vh>script</vh></v>
<v t="leo.20151110011610.29"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151110022245.1"><vh>@clean simplest1.html</vh>
<v t="leo.20151110022245.2"><vh>檔案說明</vh></v>
<v t="leo.20151110022245.3"><vh>html 標註</vh>
<v t="leo.20151110022245.4" a="E"><vh>body 標註</vh>
<v t="leo.20151110022245.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151110022245.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151110022245.7"><vh>封面</vh></v>
<v t="leo.20151110022245.18"><vh>W1</vh></v>
<v t="leo.20151110022245.27"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20151110022245.28"><vh>script</vh></v>
<v t="leo.20151110022245.29"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151110022331.1"><vh>@clean simplest2.html</vh>
<v t="leo.20151110022331.2"><vh>檔案說明</vh></v>
<v t="leo.20151110022331.3" a="E"><vh>html 標註</vh>
<v t="leo.20151110022331.4" a="E"><vh>body 標註</vh>
<v t="leo.20151110022331.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151110022331.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151110022331.7"><vh>封面</vh></v>
<v t="leo.20151110022331.19"><vh>W2</vh></v>
<v t="leo.20151110023754.1"><vh>影片</vh></v>
<v t="leo.20151110022331.27"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20151110022331.28"><vh>script</vh></v>
<v t="leo.20151110022331.29"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151110022521.1"><vh>@clean simplest3.html</vh>
<v t="leo.20151110022521.2"><vh>檔案說明</vh></v>
<v t="leo.20151110022521.3" a="E"><vh>html 標註</vh>
<v t="leo.20151110022521.4" a="E"><vh>body 標註</vh>
<v t="leo.20151110022521.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151110022521.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151110022521.7"><vh>封面</vh></v>
<v t="leo.20151110022521.20"><vh>W3</vh></v>
<v t="leo.20151110023801.1"><vh>影片</vh></v>
<v t="leo.20151110022521.27"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20151110022521.28"><vh>script</vh></v>
<v t="leo.20151110022521.29"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151110022556.1"><vh>@clean simplest4.html</vh>
<v t="leo.20151110022556.2"><vh>檔案說明</vh></v>
<v t="leo.20151110022556.3" a="E"><vh>html 標註</vh>
<v t="leo.20151110022556.4" a="E"><vh>body 標註</vh>
<v t="leo.20151110022556.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151110022556.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151110022556.7"><vh>封面</vh></v>
<v t="leo.20151110022556.21"><vh>W4</vh></v>
<v t="leo.20151110022556.26"><vh>影片</vh></v>
<v t="leo.20151110022556.27"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20151110022556.28"><vh>script</vh></v>
<v t="leo.20151110022556.29"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151110022630.1"><vh>@clean simplest5.html</vh>
<v t="leo.20151110022630.2"><vh>檔案說明</vh></v>
<v t="leo.20151110022630.3" a="E"><vh>html 標註</vh>
<v t="leo.20151110022630.4" a="E"><vh>body 標註</vh>
<v t="leo.20151110022630.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151110022630.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151110022630.7"><vh>封面</vh></v>
<v t="leo.20151110022630.22"><vh>W5</vh></v>
<v t="leo.20151110022630.26"><vh>影片</vh></v>
<v t="leo.20151110022630.27"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20151110022630.28"><vh>script</vh></v>
<v t="leo.20151110022630.29"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151110022653.1"><vh>@clean simplest6.html</vh>
<v t="leo.20151110022653.2"><vh>檔案說明</vh></v>
<v t="leo.20151110022653.3" a="E"><vh>html 標註</vh>
<v t="leo.20151110022653.4" a="E"><vh>body 標註</vh>
<v t="leo.20151110022653.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151110022653.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151110022653.7"><vh>封面</vh></v>
<v t="leo.20151110022653.23"><vh>W6</vh></v>
<v t="leo.20151110022653.27"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20151110022653.28"><vh>script</vh></v>
<v t="leo.20151110022653.29"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151110022714.1"><vh>@clean simplest7.html</vh>
<v t="leo.20151110022714.2"><vh>檔案說明</vh></v>
<v t="leo.20151110022714.3" a="E"><vh>html 標註</vh>
<v t="leo.20151110022714.4" a="E"><vh>body 標註</vh>
<v t="leo.20151110022714.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151110022714.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151110022714.7"><vh>封面</vh></v>
<v t="leo.20151110022714.24"><vh>W7</vh></v>
<v t="leo.20151110022714.27"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20151110022714.28"><vh>script</vh></v>
<v t="leo.20151110022714.29"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151110022821.1"><vh>@clean simplest8.html</vh>
<v t="leo.20151110022821.2"><vh>檔案說明</vh></v>
<v t="leo.20151110022821.3" a="E"><vh>html 標註</vh>
<v t="leo.20151110022821.4" a="E"><vh>body 標註</vh>
<v t="leo.20151110022821.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151110022821.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151110022821.7"><vh>封面</vh></v>
<v t="leo.20151110022821.25"><vh>W8</vh></v>
<v t="leo.20151110022821.27"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20151110022821.28"><vh>script</vh></v>
<v t="leo.20151110022821.29"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151022140839.4"><vh>@path pelican</vh>
<v t="123.20151022140839.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151112160920.1"><vh>@edit publishconf.py</vh></v>
<v t="123.20151022140839.7" a="E"><vh>@path content</vh>
<v t="123.20151022140839.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151110011806.1"><vh>@edit 2015cphww1.md</vh></v>
<v t="leo.20151112161929.1"><vh>@edit 2015cphww2.md</vh></v>
<v t="leo.20151112161943.1"><vh>@edit 2015cphww3.md</vh></v>
<v t="leo.20151112161952.1"><vh>@edit 2015cphww4.md</vh></v>
<v t="leo.20151112162001.1"><vh>@edit 2015cphww5.md</vh></v>
<v t="leo.20151112162009.1"><vh>@edit 2015cphww6.md</vh></v>
<v t="leo.20151112162019.1"><vh>@edit 2015cphww7.md</vh></v>
<v t="leo.20151112162030.1"><vh>@edit 2015cphww8.md</vh></v>
<v t="123.20151022140839.9"><vh>@edit 2015cphwwall.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151029134123.1"><vh>@path 40323108</vh>
<v t="leo.20151029134123.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151029134123.3"><vh>@edit 40323108_cp_w1_p.html</vh></v>
<v t="leo.20151029134123.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151029134123.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151029134123.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151029134123.7" a="E"><vh>@path content</vh>
<v t="leo.20151029134123.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151029134123.9"><vh>@edit 40323108_cp_w1.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151026231828.1"><vh>@path 40323143</vh>
<v t="leo.20151026231828.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151026231828.3"><vh>@edit 40323143_cp_w1_p.html</vh></v>
<v t="leo.20151026231828.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151026231828.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151026231828.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151026231828.7" a="E"><vh>@path content</vh>
<v t="leo.20151026231828.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151026231828.9"><vh>@edit 40323143_cp_w1.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151026231833.1"><vh>@path 40323145</vh>
<v t="leo.20151026231833.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151026231833.3"><vh>@edit 40323145_cp_w1_p.html</vh></v>
<v t="leo.20151026231833.4"><vh>@path pelican</vh>
<v t="leo.20151026231833.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151026231833.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151026231833.7"><vh>@path content</vh>
<v t="leo.20151026231833.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151026231833.9"><vh>@edit 40323145_cp_w1.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151107102720.1"><vh>@path 40323106</vh>
<v t="leo.20151107102720.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151107102720.3"><vh>@edit 40323106_cp_w1_p.html</vh></v>
<v t="leo.20151112171219.1"><vh>@edit 40323106_cp_w2_p.html</vh></v>
<v t="leo.20151112171226.1"><vh>@edit 40323106_cp_w4_p.html</vh></v>
<v t="leo.20151107102720.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151107102720.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151107102720.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151107102720.7" a="E"><vh>@path content</vh>
<v t="leo.20151107102720.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151107102720.9"><vh>@edit 40323106_cp_w1.md</vh></v>
<v t="leo.20151112170533.1"><vh>@edit 40323106_cp_w2.md</vh></v>
<v t="leo.20151112171010.1"><vh>@edit 40323106_cp_w4.md</vh></v>
</v>
</v>
</v>
<v t="amd.20151021114504.1"><vh>@path 40323131</vh>
<v t="amd.20151021213523.1"><vh>以下為投影片 ------------</vh></v>
<v t="amd.20151021114639.1"><vh>@edit 40323131_cp_w1_p.html</vh></v>
<v t="amd.20151021114516.1"><vh>@path pelican</vh>
<v t="amd.20151021213548.1"><vh>以下為設定檔 ------------</vh></v>
<v t="amd.20151021114727.1"><vh>@edit publishconf.py</vh></v>
<v t="amd.20151021114712.1"><vh>@path content</vh>
<v t="amd.20151021213558.1"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="amd.20151021114905.1"><vh>@edit 40323131_cp_w1.md</vh></v>
<v t="123.20151022141903.1"><vh>@edit 40323131_cp_w2.md</vh></v>
</v>
</v>
</v>
<v t="123.20151105235045.1"><vh>@path 40323130</vh>
<v t="123.20151105235045.2"><vh>以下為投影片 ------------</vh></v>
<v t="123.20151105235045.3"><vh>@edit 40323130_cp_w1_p.html</vh></v>
<v t="123.20151105235045.4" a="E"><vh>@path pelican</vh>
<v t="123.20151105235045.5"><vh>以下為設定檔 ------------</vh></v>
<v t="123.20151105235045.6"><vh>@edit publishconf.py</vh></v>
<v t="123.20151105235045.7" a="E"><vh>@path content</vh>
<v t="123.20151105235045.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="123.20151105235045.9"><vh>@edit 40323130_cp_w1.md</vh></v>
<v t="123.20151106001720.1"><vh>@edit 40323130_cp_w2.md</vh></v>
<v t="123.20151106001722.1"><vh>@edit 40323130_cp_w3.md</vh></v>
<v t="123.20151106001723.1"><vh>@edit 40323130_cp_w4.md</vh></v>
<v t="123.20151106001725.1"><vh>@edit 40323130_cp_w5.md</vh></v>
<v t="123.20151106001731.1"><vh>@edit 40323130_cp_w6.md</vh></v>
<v t="123.20151106001732.1"><vh>@edit 40323130_cp_w7.md</vh></v>
<v t="123.20151106001734.1"><vh>@edit 40323130_cp_w8.md</vh></v>
</v>
</v>
</v>
<v t="123.20151022143546.1"><vh>@path 40323116</vh>
<v t="123.20151022143546.2"><vh>以下為投影片 ------------</vh></v>
<v t=".20151029140247.1"><vh>@edit 40323116_cp_w1_p.html</vh></v>
<v t=".20151029140136.1"><vh>newHeadline</vh></v>
<v t="123.20151022143546.4" a="E"><vh>@path pelican</vh>
<v t="123.20151022143546.5"><vh>以下為設定檔 ------------</vh></v>
<v t="123.20151022143546.6"><vh>@edit publishconf.py</vh></v>
<v t="123.20151022143546.7"><vh>@path content</vh>
<v t="123.20151022143546.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="123.20151022143546.9"><vh>@edit 40323116_cp_w1.md</vh></v>
<v t="123.20151105141002.1"><vh>@edit 40323116_cp_w2.md</vh></v>
<v t="123.20151105141010.1"><vh>@edit 40323116_cp_w3.md</vh></v>
<v t="123.20151105141012.1"><vh>@edit 40323116_cp_w4.md</vh></v>
<v t="123.20151105141009.1"><vh>@edit 40323116_cp_w5.md</vh></v>
<v t="123.20151105141014.1"><vh>@edit 40323116_cp_w6.md</vh></v>
<v t="123.20151105141016.1"><vh>@edit 40323116_cp_w7.md</vh></v>
<v t="123.20151105141105.1"><vh>@edit 40323116_cp_w8.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151105124254.1"><vh>@path 40323107</vh>
<v t="leo.20151105124254.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151105124254.3"><vh>@edit 40323107_cp_w1_p.html</vh></v>
<v t="leo.20151105131955.1"><vh>@edit 40323107_cp_w2_p.html</vh></v>
<v t="leo.20151105124254.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151105124254.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151105124254.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151105124254.7" a="E"><vh>@path content</vh>
<v t="leo.20151105124254.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151105124254.9"><vh>@edit 40323107_cp_w1.md</vh></v>
<v t="leo.20151105124254.10"><vh>@edit 40323107_cp_w2.md</vh></v>
<v t="leo.20151105130500.1"><vh>@edit 40323107_cp_w3.md</vh></v>
</v>
</v>
</v>
<v t="123.20151112143917.1" a="E"><vh>@path 40323117</vh>
<v t="123.20151112143917.2"><vh>以下為投影片 ------------</vh></v>
<v t="123.20151112143917.3"><vh>@edit 40323117_cp_w1_p.html</vh></v>
<v t="123.20151112143917.4" a="E"><vh>@path pelican</vh>
<v t="123.20151112143917.5"><vh>以下為設定檔 ------------</vh></v>
<v t="123.20151112143917.6"><vh>@edit publishconf.py</vh></v>
<v t="123.20151112143917.7"><vh>@path content</vh>
<v t="123.20151112143917.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="123.20151112143917.9"><vh>@edit 40323117_cp_w1.md</vh></v>
<v t="123.20151112143917.10"><vh>@edit 40323117_cp_w2.md</vh></v>
<v t="123.20151112143917.11"><vh>@edit 40323117_cp_w3.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151105133807.1"><vh>@path 40323120</vh>
<v t="leo.20151105133807.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151105133807.3"><vh>@edit 40323120_cp_w1_p.html</vh></v>
<v t="leo.20151105133807.5" a="E"><vh>@path pelican</vh>
<v t="leo.20151105133807.6"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151105133807.7"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151105133807.8" a="E"><vh>@path content</vh>
<v t="leo.20151105133807.9"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151105133807.10"><vh>@edit 40323120_cp_w1.md</vh></v>
<v t="leo.20151105133807.11"><vh>@edit 40323120_cp_w2.md</vh></v>
<v t="leo.20151105133807.12"><vh>@edit 40323120_cp_w3.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151107143002.1"><vh>@path 40323119</vh>
<v t="leo.20151107143002.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151107143002.3"><vh>@edit 40323119_cp_w1_p.html</vh></v>
<v t="leo.20151107143002.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151107143002.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151107143002.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151107143002.7" a="E"><vh>@path content</vh>
<v t="leo.20151107143002.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151107143002.9"><vh>@edit 40323119_cp_w1.md</vh></v>
<v t="leo.20151107143002.10"><vh>@edit 40323119_cp_w2.md</vh></v>
<v t="leo.20151107143002.11"><vh>@edit 40323119_cp_w3.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151107151002.1"><vh>@path 40323151</vh>
<v t="leo.20151107151002.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151107151002.3"><vh>@edit 40323151_cp_w1_p.html</vh></v>
<v t="leo.20151107151002.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151107151002.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151107151002.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151107151002.7" a="E"><vh>@path content</vh>
<v t="leo.20151107151002.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151107151002.9"><vh>@edit 40323151_cp_w1.md</vh></v>
<v t="leo.20151107151002.10"><vh>@edit 40323151_cp_w2.md</vh></v>
<v t="leo.20151107151002.11"><vh>@edit 40323151_cp_w3.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151107143554.1"><vh>@path 40323111</vh>
<v t="leo.20151107143554.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151107143554.3"><vh>@edit 40323111_cp_w1_p.html</vh></v>
<v t="leo.20151107143554.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151107143554.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151107143554.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151107143554.7" a="E"><vh>@path content</vh>
<v t="leo.20151107143554.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151107143554.9"><vh>@edit 40323111_cp_w1.md</vh></v>
<v t="leo.20151107143554.10"><vh>@edit 40323111_cp_w2.md</vh></v>
<v t="leo.20151107143554.11"><vh>@edit 40323111_cp_w3.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151022140632.1" a="E"><vh>@path 40323123</vh>
<v t="leo.20151022140632.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151022140632.3"><vh>@edit 40323123_cp_w1_p.html</vh></v>
<v t="leo.20151022140632.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151022140632.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151022140632.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151022140632.7"><vh>@path content</vh>
<v t="leo.20151022140632.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151022140632.9"><vh>@edit 40323123_cp_w1.md</vh></v>
<v t="leo.20151022141015.1"><vh>@edit 40323123_cp_w2.md</vh></v>
<v t="2015.20151031012011.1"><vh>@edit 40323123_cp_w3.md</vh></v>
<v t="2015.20151031012011.2"><vh>@edit 40323123_cp_w4.md</vh></v>
<v t="2015.20151031012011.3"><vh>@edit 40323123_cp_w5.md</vh></v>
<v t="leo.20151031031253.1"><vh>@edit 40323123_cp_w6.md</vh></v>
<v t="leo.20151031031254.1"><vh>@edit 40323123_cp_w7.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151022200428.1"><vh>@path 40323105</vh>
<v t="leo.20151022200428.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151022200428.3"><vh>@edit 40323105_cp_w1_p.html</vh></v>
<v t="leo.20151106223604.1"><vh>@edit 40323105_cp_w2_p.html</vh></v>
<v t="leo.20151106230410.1"><vh>@edit 40323105_cp_w3_p.html</vh></v>
<v t="leo.20151106231132.1"><vh>@edit 40323105_cp_w4_p.html</vh></v>
<v t="leo.20151106231519.1"><vh>@edit 40323105_cp_w5_p.html</vh></v>
<v t="leo.20151106231525.1"><vh>@edit 40323105_cp_w6_p.html</vh></v>
<v t="leo.20151106234140.1"><vh>@edit 40323105_cp_w7_p.html</vh></v>
<v t="leo.20151106234148.1"><vh>@edit 40323105_cp_w8_p.html</vh></v>
<v t="leo.20151022200428.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151022200428.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151022200428.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151022200428.7" a="E"><vh>@path content</vh>
<v t="leo.20151022200428.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151022200428.9"><vh>@edit 40323105_cp_w1.md</vh></v>
<v t="leo.20151022200428.10"><vh>@edit 40323105_cp_w2.md</vh></v>
<v t="leo.20151106230524.1"><vh>@edit 40323105_cp_w3.md</vh></v>
<v t="leo.20151106231250.1"><vh>@edit 40323105_cp_w4.md</vh></v>
<v t="leo.20151106231715.1"><vh>@edit 40323105_cp_w5.md</vh></v>
<v t="leo.20151106231717.1"><vh>@edit 40323105_cp_w6.md</vh></v>
<v t="leo.20151106234314.1"><vh>@edit 40323105_cp_w7.md</vh></v>
<v t="leo.20151106234315.1"><vh>@edit 40323105_cp_w8.md</vh></v>
</v>
</v>
</v>
<v t="123.20151112144223.1"><vh>@path 40323113</vh>
<v t="123.20151112144223.2"><vh>以下為投影片 ------------</vh></v>
<v t="123.20151112144223.3"><vh>@edit 40323113_cp_w1_p.html</vh></v>
<v t="123.20151112144223.4"><vh>@edit 40323113_cp_w2_p.html</vh></v>
<v t="123.20151112144223.5"><vh>@edit 40323113_cp_w3_p.html</vh></v>
<v t="123.20151112144223.6"><vh>@edit 40323113_cp_w4_p.html</vh></v>
<v t="123.20151112144223.7"><vh>@edit 40323113_cp_w5_p.html</vh></v>
<v t="123.20151112144223.8"><vh>@edit 40323113_cp_w6_p.html</vh></v>
<v t="123.20151112144223.9"><vh>@edit 40323113_cp_w7_p.html</vh></v>
<v t="123.20151112144223.11" a="E"><vh>@path pelican</vh>
<v t="123.20151112144223.12"><vh>以下為設定檔 ------------</vh></v>
<v t="123.20151112144223.13"><vh>@edit publishconf.py</vh></v>
<v t="123.20151112144223.14" a="E"><vh>@path content</vh>
<v t="123.20151112144223.15"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="123.20151112144223.16"><vh>@edit 40323113_cp_w1.md</vh></v>
<v t="123.20151112144223.17"><vh>@edit 40323113_cp_w2.md</vh></v>
<v t="123.20151112144223.18"><vh>@edit 40323113_cp_w3.md</vh></v>
<v t="123.20151112144223.19"><vh>@edit 40323113_cp_w4.md</vh></v>
<v t="123.20151112144223.20"><vh>@edit 40323113_cp_w5.md</vh></v>
<v t="123.20151112144223.21"><vh>@edit 40323113_cp_w6.md</vh></v>
<v t="123.20151112144223.22"><vh>@edit 40323113_cp_w7.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151029135119.1"><vh>@path 40323155</vh>
<v t="leo.20151029135119.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151029135119.3"><vh>@edit 40323155_cp_w1_p.html</vh></v>
<v t="leo.20151029135119.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151029135119.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151029135119.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151029135119.7" a="E"><vh>@path content</vh>
<v t="leo.20151029135119.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151029135119.9"><vh>@edit 40323155_cp_ppt.md</vh></v>
<v t="leo.20151029135119.10"><vh>@edit 40323155_cp_w1.md</vh></v>
<v t="leo.20151105192015.1"><vh>@edit 40323155_cp_w2.md</vh></v>
<v t="leo.20151105192017.1"><vh>@edit 40323155_cp_w3.md</vh></v>
<v t="leo.20151105192019.1"><vh>@edit 40323155_cp_w4.md</vh></v>
<v t="leo.20151105192020.1"><vh>@edit 40323155_cp_w5.md</vh></v>
<v t="leo.20151105192022.1"><vh>@edit 40323155_cp_w6.md</vh></v>
<v t="leo.20151105192024.1"><vh>@edit 40323155_cp_w7.md</vh></v>
<v t="leo.20151105192455.1"><vh>@edit 40323155_cp_w8.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151029145359.1"><vh>@path 40323133</vh>
<v t="leo.20151029145359.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151029145359.3"><vh>@edit 40323133_cp_w1_p.html</vh></v>
<v t="leo.20151029145359.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151029145359.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151029145359.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151029145359.7" a="E"><vh>@path content</vh>
<v t="leo.20151029145359.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151029145359.9"><vh>@edit 40323133_cp_w1.md</vh></v>
<v t="leo.20151029145359.10"><vh>@edit 40323133_cp_w2.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151029150115.1"><vh>@path 40323141</vh>
<v t="leo.20151029150115.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151107154825.1"><vh>@edit 40323141_cp_w1_p.html</vh></v>
<v t="leo.20151107155327.1"><vh>@edit 40323141_cp_w2_p.html</vh></v>
<v t="leo.20151107160137.1" a="M"><vh>@edit 40323141_cp_w3_p.html</vh></v>
<v t="leo.20151029150115.4"><vh>@path pelican</vh>
<v t="leo.20151029150115.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151029150115.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151029150115.7"><vh>@path content</vh>
<v t="leo.20151029150115.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151029150115.9"><vh>@edit 40323141_cp_w1.md</vh></v>
<v t="leo.20151107155946.1"><vh>@edit 40323141_cp_w2.md</vh></v>
<v t="leo.20151107160624.1"><vh>@edit 40323141_cp_w3.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151029150735.1"><vh>@path 40323139</vh>
<v t="leo.20151029150735.2"><vh>以下為投影片 ------------</vh></v>
<v t="123.20151112152714.1" a="E"><vh>@clean simplest8.html</vh>
<v t="123.20151112152714.2"><vh>檔案說明</vh></v>
<v t="123.20151112152714.3" a="E"><vh>html 標註</vh>
<v t="123.20151112152714.4" a="E"><vh>body 標註</vh>
<v t="123.20151112152714.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151112152714.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151112152714.7"><vh>有關我的作業</vh></v>
<v t="123.20151112152714.8"><vh>作業任務一</vh></v>
<v t="123.20151112152714.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="123.20151112152714.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151112152706.1"><vh>@clean simplest7.html</vh>
<v t="123.20151112152706.2"><vh>檔案說明</vh></v>
<v t="123.20151112152706.3" a="E"><vh>html 標註</vh>
<v t="123.20151112152706.4" a="E"><vh>body 標註</vh>
<v t="123.20151112152706.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151112152706.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151112152706.7"><vh>有關我的作業</vh></v>
<v t="123.20151112152706.8"><vh>作業任務一</vh></v>
<v t="123.20151112152706.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="123.20151112152706.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151112152654.1"><vh>@clean simplest6.html</vh>
<v t="123.20151112152654.2"><vh>檔案說明</vh></v>
<v t="123.20151112152654.3" a="E"><vh>html 標註</vh>
<v t="123.20151112152654.4" a="E"><vh>body 標註</vh>
<v t="123.20151112152654.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151112152654.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151112152654.7"><vh>有關我的作業</vh></v>
<v t="123.20151112152654.8"><vh>作業任務一</vh></v>
<v t="123.20151112152654.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="123.20151112152654.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151112152642.1"><vh>@clean simplest5.html</vh>
<v t="123.20151112152642.2"><vh>檔案說明</vh></v>
<v t="123.20151112152642.3" a="E"><vh>html 標註</vh>
<v t="123.20151112152642.4" a="E"><vh>body 標註</vh>
<v t="123.20151112152642.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151112152642.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151112152642.7"><vh>有關我的作業</vh></v>
<v t="123.20151112152642.8"><vh>作業任務一</vh></v>
<v t="123.20151112152642.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="123.20151112152642.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151112152627.1"><vh>@clean simplest4.html</vh>
<v t="123.20151112152627.2"><vh>檔案說明</vh></v>
<v t="123.20151112152627.3" a="E"><vh>html 標註</vh>
<v t="123.20151112152627.4" a="E"><vh>body 標註</vh>
<v t="123.20151112152627.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151112152627.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151112152627.7"><vh>有關我的作業</vh></v>
<v t="123.20151112152627.8"><vh>作業任務一</vh></v>
<v t="123.20151112152627.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="123.20151112152627.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151112152449.1"><vh>@clean simplest3.html</vh>
<v t="123.20151112152449.2"><vh>檔案說明</vh></v>
<v t="123.20151112152449.3" a="E"><vh>html 標註</vh>
<v t="123.20151112152449.4" a="E"><vh>body 標註</vh>
<v t="123.20151112152449.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151112152449.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151112152449.7"><vh>有關我的作業</vh></v>
<v t="123.20151112152449.8"><vh>作業任務一</vh></v>
<v t="123.20151112152449.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="123.20151112152449.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151112151228.1"><vh>@clean simplest2.html</vh>
<v t="123.20151112151228.2"><vh>檔案說明</vh></v>
<v t="123.20151112151228.3" a="E"><vh>html 標註</vh>
<v t="123.20151112151228.4" a="E"><vh>body 標註</vh>
<v t="123.20151112151228.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151112151228.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151112151228.7"><vh>有關我的作業</vh></v>
<v t="123.20151112151228.8"><vh>作業任務一</vh></v>
<v t="123.20151112151228.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="123.20151112151228.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151112151449.1"><vh>@clean simplest.html</vh>
<v t="123.20151112151449.2"><vh>檔案說明</vh></v>
<v t="123.20151112151449.3" a="E"><vh>html 標註</vh>
<v t="123.20151112151449.4" a="E"><vh>body 標註</vh>
<v t="123.20151112151449.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151112151449.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151112151449.7"><vh>有關我的作業</vh></v>
<v t="123.20151112151449.8"><vh>作業任務一</vh></v>
<v t="123.20151112151449.9"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="123.20151112151449.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151029150735.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151029150735.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151029150735.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151029150735.7" a="E"><vh>@path content</vh>
<v t="leo.20151029150735.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151029150735.9"><vh>@edit 40323139_cp_w1.md</vh></v>
<v t="leo.20151029150735.10"><vh>@edit 40323139_cp_w2.md</vh></v>
<v t="123.20151112143739.1"><vh>@edit 40323139_cp_w3.md</vh></v>
<v t="123.20151112143743.1"><vh>@edit 40323139_cp_w4.md</vh></v>
<v t="123.20151112143743.2"><vh>@edit 40323139_cp_w5.md</vh></v>
<v t="123.20151112143743.3"><vh>@edit 40323139_cp_w6.md</vh></v>
<v t="123.20151112143743.4"><vh>@edit 40323139_cp_w7.md</vh></v>
<v t="123.20151112143743.5"><vh>@edit 40323139_cp_w8.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151029154052.1"><vh>@path 40323132</vh>
<v t="leo.20151029154052.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151029154052.3"><vh>@edit 40323132_cp_w1_p.html</vh></v>
<v t="leo.20151029154052.4"><vh>@path pelican</vh>
<v t="leo.20151029154052.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151029154052.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151029154052.7" a="E"><vh>@path content</vh>
<v t="leo.20151029154052.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151029154052.9"><vh>@edit 40323132_cp_w1.md</vh></v>
<v t="leo.20151029154052.10"><vh>@edit 40323132_cp_w2.md</vh></v>
<v t="123.20151106222830.1"><vh>@edit 40323132_cp_w3.md</vh></v>
<v t="123.20151106222832.1"><vh>@edit 40323132_cp_w4.md</vh></v>
<v t="123.20151106222834.1"><vh>@edit 40323132_cp_w5.md</vh></v>
<v t="123.20151106222836.1"><vh>@edit 40323132_cp_w6.md</vh></v>
<v t="123.20151106222838.1"><vh>@edit 40323132_cp_w7.md</vh></v>
<v t="123.20151106222840.1"><vh>@edit 40323132_cp_w8.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151029154544.1"><vh>@path 40323144</vh>
<v t="leo.20151029154544.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151029154544.3"><vh>@edit 40323144_cp_w1_p.html</vh></v>
<v t="leo.20151029154544.4"><vh>@path pelican</vh>
<v t="leo.20151029154544.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151029154544.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151029154544.7"><vh>@path content</vh>
<v t="leo.20151029154544.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151029154544.9"><vh>@edit 40323144_cp_w1.md</vh></v>
<v t="leo.20151029154544.10"><vh>@edit 40323144_cp_w2.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151029154913.1"><vh>@path 40323149</vh>
<v t="leo.20151029154913.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151107173641.1"><vh>@clean simplest.html</vh>
<v t="leo.20151107173641.2"><vh>檔案說明</vh></v>
<v t="leo.20151107173641.3" a="E"><vh>html 標註</vh>
<v t="leo.20151107173641.4" a="E"><vh>body 標註</vh>
<v t="leo.20151107173641.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151107173641.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151107173641.7"><vh>Front page</vh></v>
<v t="leo.20151107173641.8"><vh>W1</vh></v>
<v t="leo.20151107173641.9"><vh>W2</vh></v>
<v t="leo.20151107173641.10"><vh>W3</vh></v>
<v t="leo.20151107173641.11"><vh>W4</vh></v>
<v t="leo.20151107173641.12"><vh>W5</vh></v>
<v t="leo.20151107173641.13"><vh>W6</vh></v>
<v t="leo.20151107173641.14"><vh>W7</vh></v>
<v t="leo.20151107173641.15"><vh>W8</vh></v>
</v>
</v>
<v t="leo.20151107173641.16"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151029154913.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151029154913.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151029154913.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151029154913.7" a="E"><vh>@path content</vh>
<v t="leo.20151029154913.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151029154913.9"><vh>@edit 40323149_cp_w1.md</vh></v>
<v t="leo.20151029154913.10"><vh>@edit 40323149_cp_w2.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151029160134.1"><vh>@path 40323154</vh>
<v t="leo.20151029160134.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151029160134.3"><vh>@edit 40323154_cp_w1_p.html</vh></v>
<v t="123.20151112132704.1"><vh>@edit 40323154_cp_w2_p.html</vh></v>
<v t="123.20151112132713.1"><vh>@edit 40323154_cp_w3_p.html</vh></v>
<v t="123.20151112132712.1"><vh>@edit 40323154_cp_w4_p.html</vh></v>
<v t="123.20151112132706.1"><vh>@edit 40323154_cp_w5_p.html</vh></v>
<v t="123.20151112132710.1"><vh>@edit 40323154_cp_w6_p.html</vh></v>
<v t="123.20151112132709.1"><vh>@edit 40323154_cp_w7_p.html</vh></v>
<v t="123.20151112132708.1"><vh>@edit 40323154_cp_w8_p.html</vh></v>
<v t="leo.20151029160134.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151029160134.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151029160134.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151029160134.7" a="E"><vh>@path content</vh>
<v t="leo.20151029160134.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151029160134.9"><vh>@edit 40323154_cp_w1.md</vh></v>
<v t="leo.20151029160134.10"><vh>@edit 40323154_cp_w2.md</vh></v>
<v t="123.20151112132724.1"><vh>@edit 40323154_cp_w3.md</vh></v>
<v t="123.20151112132728.1"><vh>@edit 40323154_cp_w4.md</vh></v>
<v t="123.20151112132734.1"><vh>@edit 40323154_cp_w5.md</vh></v>
<v t="123.20151112132735.1"><vh>@edit 40323154_cp_w6.md</vh></v>
<v t="123.20151112132737.1"><vh>@edit 40323154_cp_w7.md</vh></v>
<v t="123.20151112132726.1"><vh>@edit 40323154_cp_w8.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151030143639.1"><vh>@path 40323152</vh>
<v t="leo.20151030143639.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151030143639.3"><vh>@edit 40323152_cp_w1_p.html</vh></v>
<v t="leo.20151030143639.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151030143639.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151030143639.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151030143639.7" a="E"><vh>@path content</vh>
<v t="leo.20151030143639.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151030143639.9"><vh>@edit 40323152_cp_w1.md</vh></v>
<v t="leo.20151030143639.10"><vh>@edit 40323152_cp_w2.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151105200949.1"><vh>@path 40323146</vh>
<v t="leo.20151105200949.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151105200949.3"><vh>@edit 40323146_cp_w1_p.html</vh></v>
<v t="leo.20151105200949.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151105200949.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151105200949.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151105200949.7"><vh>@path content</vh>
<v t="leo.20151105200949.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151105200949.9"><vh>@edit 40323146_cp_w1.md</vh></v>
<v t="leo.20151105200949.10"><vh>@edit 40323146_cp_w2.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151107051316.1"><vh>@path 40323136</vh>
<v t="leo.20151107051316.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151107051316.3"><vh>@edit 40323136_cp_w1_p.html</vh></v>
<v t="leo.20151107051316.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151107051316.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151107051316.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151107051316.7" a="E"><vh>@path content</vh>
<v t="leo.20151107051316.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151107051316.9"><vh>@edit 40323136_cp_w1.md</vh></v>
<v t="leo.20151107051316.10"><vh>@edit 40323136_cp_w2.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151112121934.1"><vh>@path 40323147</vh>
<v t="leo.20151112121934.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151112121934.3"><vh>@edit 40323147_cp_w1_p.html</vh></v>
<v t="leo.20151112121934.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151112121934.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151112121934.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151112121934.7" a="E"><vh>@path content</vh>
<v t="leo.20151112121934.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151112121934.9"><vh>@edit 40323147_cp_w1.md</vh></v>
<v t="leo.20151112121934.10"><vh>@edit 40323147_cp_w2.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151112123318.1"><vh>@path 40323156</vh>
<v t="leo.20151112123318.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151112123318.3"><vh>@edit 40323156_cp_w1_p.html</vh></v>
<v t="leo.20151112123318.4"><vh>@path pelican</vh>
<v t="leo.20151112123318.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151112123318.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151112123318.7" a="E"><vh>@path content</vh>
<v t="leo.20151112123318.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151112123318.9"><vh>@edit 40323156_cp_w1.md</vh></v>
<v t="leo.20151112123318.10"><vh>@edit 40323156_cp_w2.md</vh></v>
</v>
</v>
</v>
<v t="leo.20151112123934.1"><vh>@path 40323142</vh>
<v t="leo.20151112123934.2"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20151112123934.3"><vh>@edit 40323142_cp_w1_p.html</vh></v>
<v t="leo.20151112123934.4" a="E"><vh>@path pelican</vh>
<v t="leo.20151112123934.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151112123934.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151112123934.7" a="E"><vh>@path content</vh>
<v t="leo.20151112123934.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20151112123934.9"><vh>@edit 40323142_cp_w1.md</vh></v>
<v t="leo.20151112123934.10"><vh>@edit 40323142_cp_w2.md</vh></v>
</v>
</v>
</v>
</v>
<v t="leo.20151112140518.1"><vh>Recovered Nodes</vh>
<v t="leo.20151112140518.2"><vh>Recovered node "W3" from @clean simplest.html</vh>
<v t="leo.20151112140518.3"><vh>old:W3</vh></v>
<v t="leo.20151112140518.4"><vh>new:W3</vh></v>
</v>
<v t="leo.20151112140518.5"><vh>Recovered node "W4" from @clean simplest.html</vh>
<v t="leo.20151112140518.6"><vh>old:W4</vh></v>
<v t="leo.20151112140518.7"><vh>new:W4</vh></v>
</v>
<v t="leo.20151112140518.8"><vh>Recovered node "W5" from @clean simplest.html</vh>
<v t="leo.20151112140518.9"><vh>old:W5</vh></v>
<v t="leo.20151112140518.10"><vh>new:W5</vh></v>
</v>
<v t="leo.20151112140518.11"><vh>Recovered node "W6" from @clean simplest.html</vh>
<v t="leo.20151112140518.12"><vh>old:W6</vh></v>
<v t="leo.20151112140518.13"><vh>new:W6</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx=".20151029140136.1"></t>
<t tx="123.20151022140839.1"></t>
<t tx="123.20151022140839.2"></t>
<t tx="123.20151022140839.4"></t>
<t tx="123.20151022140839.5"></t>
<t tx="123.20151022140839.7"></t>
<t tx="123.20151022140839.8"></t>
<t tx="123.20151022143546.1"></t>
<t tx="123.20151022143546.2"></t>
<t tx="123.20151022143546.4"></t>
<t tx="123.20151022143546.5"></t>
<t tx="123.20151022143546.7"></t>
<t tx="123.20151022143546.8"></t>
<t tx="123.20151029141051.1"></t>
<t tx="123.20151029141051.2"></t>
<t tx="123.20151029141051.4"></t>
<t tx="123.20151029141051.5"></t>
<t tx="123.20151029141051.7"></t>
<t tx="123.20151029141051.8"></t>
<t tx="123.20151029151348.1"></t>
<t tx="123.20151029151348.2"></t>
<t tx="123.20151029151348.4"></t>
<t tx="123.20151029151348.5"></t>
<t tx="123.20151029151348.7"></t>
<t tx="123.20151029151348.8"></t>
<t tx="123.20151105235045.1"></t>
<t tx="123.20151105235045.2"></t>
<t tx="123.20151105235045.4"></t>
<t tx="123.20151105235045.5"></t>
<t tx="123.20151105235045.7"></t>
<t tx="123.20151105235045.8"></t>
<t tx="123.20151112143917.1"></t>
<t tx="123.20151112143917.2"></t>
<t tx="123.20151112143917.4"></t>
<t tx="123.20151112143917.5"></t>
<t tx="123.20151112143917.7"></t>
<t tx="123.20151112143917.8"></t>
<t tx="123.20151112144223.1"></t>
<t tx="123.20151112144223.11"></t>
<t tx="123.20151112144223.12"></t>
<t tx="123.20151112144223.14"></t>
<t tx="123.20151112144223.15"></t>
<t tx="123.20151112144223.2"></t>
<t tx="123.20151112151228.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151112151228.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151112151228.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151112151228.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151112151228.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151112151228.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112151228.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112151228.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二甲&lt;/h1&gt;
    &lt;p&gt;40323139陳延誠2015/09/24&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="123.20151112151228.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;W2筆記:&lt;/h1&gt;
    &lt;p&gt;先把python.properties中的V:\IDE\Python33全部改成V:\anaconda3，可以利用LEO上面的功能將V:\IDE\Python33全部改成V:\anaconda3，速度會比較快。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20151112151228.9">&lt;section&gt;
    &lt;h1&gt;心得和自評&lt;/h1&gt;
    &lt;p&gt;這週一開始因為第一週的投影片沒先用好，所以在一開始就卡了一下子，後來靠著同學的幫忙，終於把投影片給用出來了，也知道為甚麼沒辦法把投影片用出來，好像是沒有認證的關係。&lt;/p&gt;
    &lt;p&gt;自評分數75&lt;a href="#/hw-task-one"&gt;&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151112151449.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151112151449.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151112151449.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151112151449.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151112151449.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151112151449.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112151449.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112151449.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二甲&lt;/h1&gt;
    &lt;p&gt;40323139 陳延誠2015/09/17 &lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="123.20151112151449.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;操作步驟:&lt;/h1&gt;
    &lt;p&gt;首先先去下載Ana3_lite2然後下載老師的fix和reveal2然後去github建立自己的檔案(Initialize this repository with a README要打勾) 然後複製網址git clone ，好了之後在遠端建一個分支然後再來近端也建一個分支git branch gh-pages，切換到新創的分支git checkout gh-pages ，再來把剛下載的reveal丟進去自己創的檔案，丟完之後就可以把reveal.leo丟進去leo進行編輯，編輯完之後按save再來把她git push 上去&lt;/p&gt;
  
&lt;/section&gt;
				
</t>
<t tx="123.20151112151449.9">&lt;section&gt;
    &lt;h1&gt;心得和自評&lt;/h1&gt;
    &lt;p&gt;心得:覺得這門課非常困難，老師上課上的內容覺得艱深，雖然老師上課都有錄影片，但回家自己操作過後還是oh my god ，上課的時候有認真聽也有拿筆記本出來抄但有時候還是聽不懂一些使用方法，後來靠著老師的教學影片和同學幫忙下完成了作業&lt;/p&gt;
    &lt;p&gt;自評分數:70&lt;a href="#/hw-task-one"&gt;&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151112152449.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151112152449.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151112152449.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151112152449.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151112152449.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151112152449.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152449.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152449.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二甲&lt;/h1&gt;
    &lt;p&gt;40323139陳延誠2015/10/01&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="123.20151112152449.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;W3筆記:&lt;/h1&gt;
    &lt;p&gt;上次的作業還沒做完繼續做上次的作業，去老師的網址找solvespace，然後找solvespace的操作步驟然後再下載檔案&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20151112152449.9">&lt;section&gt;
    &lt;h1&gt;心得和自評&lt;/h1&gt;
    &lt;p&gt;這週一樣延續上禮拜的作業，還要先去下載solvespace，我下載完之後開啟solvespace時，發現這是一個新的繪圖軟體，因為上面都是英文的，讓我覺得比較困難。&lt;/p&gt;
    &lt;p&gt;自評分數76&lt;a href="#/hw-task-one"&gt;&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151112152627.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151112152627.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151112152627.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151112152627.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151112152627.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151112152627.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152627.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152627.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二甲&lt;/h1&gt;
    &lt;p&gt;40323139陳延誠2015/10/08&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="123.20151112152627.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;操作步驟:&lt;/h1&gt;
    &lt;p&gt;先到老師給的網站wordpress-2015course.rhcloud.com.然後搜尋Solvespace 2.1 版 點選https://github.com/whitequark/solvespace/releases 下載Solvespace 然後找到2015Fall CADPB 第4週下方有Solvespace 基本操作 點進去之後再點introductory tutorial 就可以照著教學來畫圖了&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20151112152627.9">&lt;section&gt;
    &lt;h1&gt;心得和自評&lt;/h1&gt;
    &lt;p&gt;操作SolveSpace的時候一開始都還蠻簡單的但英文的介面真的讓人有些不懂，長料的地方一開始都只長一邊，後來才發現原來要打勾two-sides，終於把中間的肋給長出來了，再來後面兩個圓畫出來長料後要按difference，就完成囉&lt;/p&gt;
    &lt;p&gt;自評分數80&lt;a href="#/hw-task-one"&gt;&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151112152642.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151112152642.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151112152642.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151112152642.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151112152642.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151112152642.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152642.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152642.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二甲&lt;/h1&gt;
    &lt;p&gt;40323139陳延誠2015/10/15&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="123.20151112152642.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;W5筆記:&lt;/h1&gt;
    &lt;p&gt;1.繼續上禮拜的作業，上禮拜的作業是solvespace的畫圖，沒畫完的繼續畫。
    2.開始進行實物測繪了。
    3.老師要有更新過的reveal，要在裡面更改資料。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20151112152642.9">&lt;section&gt;
    &lt;h1&gt;心得和自評&lt;/h1&gt;
    &lt;p&gt;這禮拜老師有把reveal更新成reveal2，只是把bootstrap3改成octopress，然後這禮拜也開始腳踏車的實物測繪，要派兩個人去看，但好像非常困難。&lt;/p&gt;
    &lt;p&gt;自評分數74&lt;a href="#/hw-task-one"&gt;&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151112152654.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151112152654.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151112152654.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151112152654.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151112152654.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151112152654.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152654.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152654.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二甲&lt;/h1&gt;
    &lt;p&gt;40323139 陳延誠2015/10/22&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="123.20151112152654.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;操作步驟:&lt;/h1&gt;
    &lt;p&gt;首先先去Ana3_2015然後按data再來apps可以找到creo2_64bit點選裡面的Parametric再點bin可以找到parametric(檔案類型:AutoCAD PostScript 樣式，然後再去老師得網站2015Fall CADPA 第六週可以找到cero的教學，一步一步照著上面做，即可做出。&lt;/p&gt;
  
&lt;/section&gt;
				
</t>
<t tx="123.20151112152654.9">&lt;section&gt;
    &lt;h1&gt;心得和自評&lt;/h1&gt;
    &lt;p&gt;在畫這張圖的時候，遇到了很多困難，比如說在畫一開始的方形跟圓柱的ˊ時候就花了一些時間才把他們弄好，在來後面的連接，也要先把中心線先對好再來點要接合的面才能把它門完全接好在一起，雖然過程很複雜但做出來的成品覺得還蠻漂亮的。&lt;/p&gt;
    &lt;p&gt;自評分數:80&lt;a href="#/hw-task-one"&gt;&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151112152706.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151112152706.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151112152706.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151112152706.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151112152706.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151112152706.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152706.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152706.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二甲&lt;/h1&gt;
    &lt;p&gt;40323139 陳延誠2015/10/29&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="123.20151112152706.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;W7筆記:&lt;/h1&gt;
    &lt;p&gt;1.怎麼將倉儲裡面的Leo做更改
2.怎麼在班級倉儲裡建立使用者
3.如何解決Leo衝突&lt;/p&gt;
  
&lt;/section&gt;
				
</t>
<t tx="123.20151112152706.9">&lt;section&gt;
    &lt;h1&gt;心得和自評&lt;/h1&gt;
    &lt;p&gt;這禮拜在跟同學學如何創建自己的倉儲並將倉儲的Leo更改，然後在把更改後的Leo 做save - button按pelican-content然後在把他推上去，推上去的時候因為有人已經先推了，所以就不能推了，然後在git pull下來重推一次結果leo就掛掉了。&lt;/p&gt;
    &lt;p&gt;自評分數:75&lt;a href="#/hw-task-one"&gt;&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151112152714.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151112152714.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151112152714.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151112152714.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151112152714.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151112152714.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152714.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151112152714.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;四設計二甲&lt;/h1&gt;
    &lt;p&gt;40323139 陳延誠2015/11/05&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="123.20151112152714.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;W8筆記:&lt;/h1&gt;
    &lt;p&gt;1.開始進入班級協同倉儲裡改自己的檔案
2.解決衝突
(1)首先先將Leo檔打開至SciTE
(2)有新版本及舊版本,我們先將舊的版本刪掉
(3)它會有x7把它們通通刪掉
(4)把他們前面有一些等號也要把它刪掉
(5)儲存後再重開一次檔案即可&lt;/p&gt;
  
&lt;/section&gt;
				
</t>
<t tx="123.20151112152714.9">&lt;section&gt;
    &lt;h1&gt;心得和自評&lt;/h1&gt;
    &lt;p&gt;已經快到期中考週了，大家都忙著要趕期中報告，找同學來教我怎麼做才會比較快或是比較順，可是在學校有時候leo會掛掉，只能在學校做了一點之後存到隨身碟裡面帶回家做，回家做時又怕跟同學同時間推，所以有時候就必須先git pull下來再推回去。。&lt;/p&gt;
    &lt;p&gt;自評分數:76&lt;a href="#/hw-task-one"&gt;&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150913232631.1"></t>
<t tx="amd.20150913232631.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="amd.20150913232631.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="amd.20150915211341.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915211351.1">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="amd.20150915211351.12">&lt;section&gt;
    &lt;h1&gt;第3張投影片&lt;/h1&gt;
    &lt;p&gt;成績自評分數的量化依據?&lt;/p&gt;
    &lt;p&gt;可以連結到內部投影片&lt;a href="#/hw-task-one"&gt;作業任務一&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150915211351.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="amd.20150915211351.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915211351.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;有關我的作業&lt;/h1&gt;
    &lt;p&gt;學號姓名與日期&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="amd.20150915211351.9">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;作業任務一&lt;/h1&gt;
    &lt;p&gt;有關作業任務一的說明&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://www.google.com"&gt;Google&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150917085040.1">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="amd.20150919102739.1">主要為 reveal.js 的簡報目錄架構, 其他子目錄為

images - 存放簡報與 pelican 網誌所需要的影像檔案

pelican - 存放 pelican 專案資料檔, 並且設法讓 pelican 所產生的 output 檔案直接存放到上層 reveal.js 根目錄

content/notebook - 存放 Jupyter 的 IPython notebook 檔案, 然後再由 pelican 設定, 將內容放入 blog 文章中

</t>
<t tx="amd.20150919103357.1">打算利用

pelican pelican -o ./../ -s publishconf.py

-o 指定 ouput 所在目錄, 這裡使用上一層目錄, 

-s 則指定 setting, 這裡採用 publishconf.py 中的設定

將位於專案中 pelican 目錄內的 .md 檔案, 轉為 html 網誌格式, 然後存在 reveal.js 的架構目錄中

也就是 index.html 是由 pelican 控制</t>
<t tx="amd.20150919113957.1"></t>
<t tx="amd.20150919114010.1"></t>
<t tx="amd.20150919120205.1"></t>
<t tx="amd.20150919124128.1">@language python
import os
os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t ../../theme/pelican-octopress")
g.es("user pelican 執行完畢")</t>
<t tx="amd.20151006113136.1"></t>
<t tx="amd.20151007224830.1">安裝

sudo pip3 install jupyter

執行

jupyter notebook
</t>
<t tx="amd.20151021113722.1"></t>
<t tx="amd.20151021113731.1"></t>
<t tx="amd.20151021114454.1"></t>
<t tx="amd.20151021114504.1"></t>
<t tx="amd.20151021114516.1"></t>
<t tx="amd.20151021114529.1"></t>
<t tx="amd.20151021114712.1"></t>
<t tx="amd.20151021120245.1">@language python
import os
os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t theme/pelican-octopress")
g.es("admin pelican 執行完畢")</t>
<t tx="amd.20151021213523.1"></t>
<t tx="amd.20151021213548.1"></t>
<t tx="amd.20151021213558.1"></t>
<t tx="amd.20151029230307.1">@language python
'''
寫在節點內文, 然後按下 Ctrl+b 可以執行
'''
lines = open("cadpa.txt", "r", encoding="utf-8").read().splitlines()
for i in range(len(lines)):
    g.es("&lt;a href='user/"+lines[i]+"/'&gt;"+lines[i]+"&lt;/a&gt;")
    
'''
cadpa.txt 檔案內容

40223116
40223252
40323101
40323102
40323103
40323105
40323106
40323107
40323108
40323109
40323110
40323111
40323112
40323113
40323115
40323116
40323117
40323118
40323119
40323120
40323121
40323122
40323123
40323124
40323125
40323126
40323127
40323128
40323129
40323130
40323131
40323132
40323133
40323135
40323136
40323137
40323138
40323139
40323140
40323141
40323142
40323143
40323144
40323145
40323146
40323147
40323148
40323149
40323150
40323151
40323152
40323153
40323154
40323155
40323156
'''</t>
<t tx="leo.20151022140632.1"></t>
<t tx="leo.20151022140632.2"></t>
<t tx="leo.20151022140632.4"></t>
<t tx="leo.20151022140632.5"></t>
<t tx="leo.20151022140632.7"></t>
<t tx="leo.20151022140632.8"></t>
<t tx="leo.20151022200428.1"></t>
<t tx="leo.20151022200428.2"></t>
<t tx="leo.20151022200428.4"></t>
<t tx="leo.20151022200428.5"></t>
<t tx="leo.20151022200428.7"></t>
<t tx="leo.20151022200428.8"></t>
<t tx="leo.20151026231828.1"></t>
<t tx="leo.20151026231828.2"></t>
<t tx="leo.20151026231828.4"></t>
<t tx="leo.20151026231828.5"></t>
<t tx="leo.20151026231828.7"></t>
<t tx="leo.20151026231828.8"></t>
<t tx="leo.20151026231833.1"></t>
<t tx="leo.20151026231833.2"></t>
<t tx="leo.20151026231833.4"></t>
<t tx="leo.20151026231833.5"></t>
<t tx="leo.20151026231833.7"></t>
<t tx="leo.20151026231833.8"></t>
<t tx="leo.20151029134123.1"></t>
<t tx="leo.20151029134123.2"></t>
<t tx="leo.20151029134123.4"></t>
<t tx="leo.20151029134123.5"></t>
<t tx="leo.20151029134123.7"></t>
<t tx="leo.20151029134123.8"></t>
<t tx="leo.20151029135119.1"></t>
<t tx="leo.20151029135119.2"></t>
<t tx="leo.20151029135119.4"></t>
<t tx="leo.20151029135119.5"></t>
<t tx="leo.20151029135119.7"></t>
<t tx="leo.20151029135119.8"></t>
<t tx="leo.20151029145359.1"></t>
<t tx="leo.20151029145359.2"></t>
<t tx="leo.20151029145359.4"></t>
<t tx="leo.20151029145359.5"></t>
<t tx="leo.20151029145359.7"></t>
<t tx="leo.20151029145359.8"></t>
<t tx="leo.20151029150115.1"></t>
<t tx="leo.20151029150115.2"></t>
<t tx="leo.20151029150115.4"></t>
<t tx="leo.20151029150115.5"></t>
<t tx="leo.20151029150115.7"></t>
<t tx="leo.20151029150115.8"></t>
<t tx="leo.20151029150735.1"></t>
<t tx="leo.20151029150735.2"></t>
<t tx="leo.20151029150735.4"></t>
<t tx="leo.20151029150735.5"></t>
<t tx="leo.20151029150735.7"></t>
<t tx="leo.20151029150735.8"></t>
<t tx="leo.20151029154052.1"></t>
<t tx="leo.20151029154052.2"></t>
<t tx="leo.20151029154052.4"></t>
<t tx="leo.20151029154052.5"></t>
<t tx="leo.20151029154052.7"></t>
<t tx="leo.20151029154052.8"></t>
<t tx="leo.20151029154544.1"></t>
<t tx="leo.20151029154544.2"></t>
<t tx="leo.20151029154544.4"></t>
<t tx="leo.20151029154544.5"></t>
<t tx="leo.20151029154544.7"></t>
<t tx="leo.20151029154544.8"></t>
<t tx="leo.20151029154913.1"></t>
<t tx="leo.20151029154913.2"></t>
<t tx="leo.20151029154913.4"></t>
<t tx="leo.20151029154913.5"></t>
<t tx="leo.20151029154913.7"></t>
<t tx="leo.20151029154913.8"></t>
<t tx="leo.20151029160134.1"></t>
<t tx="leo.20151029160134.2"></t>
<t tx="leo.20151029160134.4"></t>
<t tx="leo.20151029160134.5"></t>
<t tx="leo.20151029160134.7"></t>
<t tx="leo.20151029160134.8"></t>
<t tx="leo.20151030143639.1"></t>
<t tx="leo.20151030143639.2"></t>
<t tx="leo.20151030143639.4"></t>
<t tx="leo.20151030143639.5"></t>
<t tx="leo.20151030143639.7"></t>
<t tx="leo.20151030143639.8"></t>
<t tx="leo.20151105124254.1"></t>
<t tx="leo.20151105124254.2"></t>
<t tx="leo.20151105124254.4"></t>
<t tx="leo.20151105124254.5"></t>
<t tx="leo.20151105124254.7"></t>
<t tx="leo.20151105124254.8"></t>
<t tx="leo.20151105133807.1"></t>
<t tx="leo.20151105133807.2"></t>
<t tx="leo.20151105133807.5"></t>
<t tx="leo.20151105133807.6"></t>
<t tx="leo.20151105133807.8"></t>
<t tx="leo.20151105133807.9"></t>
<t tx="leo.20151105200949.1"></t>
<t tx="leo.20151105200949.2"></t>
<t tx="leo.20151105200949.4"></t>
<t tx="leo.20151105200949.5"></t>
<t tx="leo.20151105200949.7"></t>
<t tx="leo.20151105200949.8"></t>
<t tx="leo.20151107051316.1"></t>
<t tx="leo.20151107051316.2"></t>
<t tx="leo.20151107051316.4"></t>
<t tx="leo.20151107051316.5"></t>
<t tx="leo.20151107051316.7"></t>
<t tx="leo.20151107051316.8"></t>
<t tx="leo.20151107102720.1"></t>
<t tx="leo.20151107102720.2"></t>
<t tx="leo.20151107102720.4"></t>
<t tx="leo.20151107102720.5"></t>
<t tx="leo.20151107102720.7"></t>
<t tx="leo.20151107102720.8"></t>
<t tx="leo.20151107143002.1"></t>
<t tx="leo.20151107143002.2"></t>
<t tx="leo.20151107143002.4"></t>
<t tx="leo.20151107143002.5"></t>
<t tx="leo.20151107143002.7"></t>
<t tx="leo.20151107143002.8"></t>
<t tx="leo.20151107143554.1"></t>
<t tx="leo.20151107143554.2"></t>
<t tx="leo.20151107143554.4"></t>
<t tx="leo.20151107143554.5"></t>
<t tx="leo.20151107143554.7"></t>
<t tx="leo.20151107143554.8"></t>
<t tx="leo.20151107151002.1"></t>
<t tx="leo.20151107151002.2"></t>
<t tx="leo.20151107151002.4"></t>
<t tx="leo.20151107151002.5"></t>
<t tx="leo.20151107151002.7"></t>
<t tx="leo.20151107151002.8"></t>
<t tx="leo.20151107173641.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151107173641.10">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第三週內容&lt;/h1&gt;
    &lt;p&gt;1.reveal與js pellican網址投影片製作&lt;/p&gt;
    &lt;p&gt;2.&lt;a href="http://www.sciencedirect.com/science/article/pii/B9780815514473500029"&gt;摘要&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;3.Solvespace 操作: &lt;a href="http://solvespace.com/tutorial.pl"&gt;連結&lt;/a&gt; (簡介)&lt;/p&gt;
    &lt;p&gt;4.將隨身leo安裝到近端並解壓縮網址:&lt;a href="http://140.130.17.17/public/fix.zip"&gt;連結&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;5.把fix.bat打開&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:學到了Solvespace這繪圖軟體，雖說全英文比較不習慣，各種操作還有待摸索，但同時多了一個新技能!!&lt;/p&gt;
    &lt;p&gt;自評:80分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151107173641.11">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第四週內容&lt;/h1&gt;
    &lt;p&gt;1.Creo Parametric 基本操作: &lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;連結&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;2.Solvespace的繪圖&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:這禮拜家裡因有急事請假，所以這堂課沒上到，回來後請教同學這週課程，Creo是第一次碰，所以還要多多練習，而Solvespace有比上次更上手&lt;/p&gt;
    &lt;p&gt;自評:65分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151107173641.12">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第五週內容&lt;/h1&gt;
    &lt;p&gt;Pro/Engineer Mechanism:&lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m (Nutcracker Mechanism)"&gt;連結&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;reveal 2.0 更新&lt;p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:reveal 2.0更新後，每次都要重新git clone，多花了一些時間，但功能也有些變化&lt;/p&gt;
    &lt;p&gt;自評:75分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151107173641.13">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第六週內容&lt;/h1&gt;
    &lt;p&gt;1.pelican 網誌與 reveal.js 投影片製作, 內容送到 Github pages&lt;/p&gt;
    &lt;p&gt;2.&lt;a href="What engineers do? "&gt;摘要&lt;/a&gt;&lt;p&gt;
    &lt;p&gt;3.Solvespace 基本操作: &lt;a href="http://solvespace.com/tutorial.pl (簡介)"&gt;連結&lt;/a&gt;&lt;p&gt;
    &lt;p&gt;4.Creo Parametric 基本操作: &lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;連結&lt;/a&gt;&lt;p&gt;
    &lt;p&gt;5.Pro/Engineer Mechanism: &lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m (Nutcracker Mechanism)"&gt;連結&lt;/a&gt;&lt;p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:在投影片製作時，打出來的字後請重新檢查，只要有意點錯誤，呈現的投影片就會亂，所以要再三檢查格式是否正確&lt;/p&gt;
    &lt;p&gt;自評:85分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;

</t>
<t tx="leo.20151107173641.14">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第七週內容&lt;/h1&gt;
    &lt;p&gt;建置班級協統倉儲的網誌&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:推上去時各種衝突，推個兩、三次才成功也要感謝組員的幫助&lt;/p&gt;
    &lt;p&gt;自評:75分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151107173641.15">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第八週內容&lt;/h1&gt;
    &lt;p&gt;建置班級協統倉儲的網誌&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:這週的內容跟上週差不多，而在倉儲內有些檔案是壞掉的，下載後用leo發現打不開&lt;/p&gt;
    &lt;p&gt;自評:85分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151107173641.16">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151107173641.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151107173641.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151107173641.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151107173641.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151107173641.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151107173641.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;電腦輔助設計與實習&lt;/h1&gt;
    &lt;p&gt;班級:四設計二甲&lt;/p&gt;	
         &lt;p&gt; 學號:40323149&lt;/p&gt;	
         &lt;p&gt; 姓名:楊智堯&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151107173641.8">&lt;section id="hw-task-one"&gt;
    &lt;section&gt;
    &lt;h1&gt;第一週內容&lt;/h1&gt;
    &lt;p&gt;1.請上課帶筆記本、耳機、隨身碟&lt;/p&gt;
    &lt;p&gt;2.git指令&lt;/p&gt;
    &lt;p&gt;3.建立github倉儲&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;建立Github倉儲&lt;/h2&gt;
    &lt;p&gt;1.利用github建立投影&lt;/p&gt;
    &lt;p&gt;2.git clone github倉儲網址-複製倉儲內容&lt;/p&gt;
    &lt;p&gt;3.cd資料夾名-點入資料夾&lt;/p&gt;
    &lt;p&gt;4.git branch gh-pages-建立分支&lt;/p&gt;
   &lt;p&gt; 5.git checkout gh-pages-換分支&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;				
&lt;p&gt;6. 複製老師github上的revel倉儲&lt;/p&gt;		
&lt;p&gt;7.複製的內容丟入自己git clone下來的資料夾(除了README.md and .git) &lt;/p&gt;
&lt;p&gt;8.git add-A更改內容 &lt;/p&gt;
&lt;p&gt;9.git commit-m"40323149"&lt;/p&gt;
&lt;p&gt;10.git config--global user.email 確認帳號&lt;/p&gt;
&lt;p&gt;11.git config--global user.name 確認名字 &lt;/p&gt;
&lt;p&gt;12.git push original gh-pages 推回原本網站&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:這門課跟一年級時一樣非常的有挑戰，完全沒接觸過東西，但把它吸收進去後，未來有更多的資源能運用&lt;/p&gt;
    &lt;p&gt;自評:75分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151107173641.9">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第二週內容&lt;/h1&gt;
    &lt;p&gt;1.電腦輔助設計與協同產品設計專業練習&lt;/p&gt;
    &lt;p&gt;2.修正 notebook.py，之後才能順利把檔案push&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:在請教同學後，大部分已成功推出去的同學出現錯誤，一開始還擔心，後來才知道可能是網速問題，但我出現錯誤的原因是信箱沒有認證...&lt;/p&gt;
    &lt;p&gt;自評:70分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151108102259.1"></t>
<t tx="leo.20151108102259.2"></t>
<t tx="leo.20151108102259.4"></t>
<t tx="leo.20151108102259.5"></t>
<t tx="leo.20151108102259.7"></t>
<t tx="leo.20151108102259.8"></t>
<t tx="leo.20151110011610.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151110011610.10">&lt;li&gt;&lt;p&gt;&lt;small&gt;W1-利用 Leo Editor 摘要重點, 建立個人 Github 課程倉儲&lt;a href="#/w1"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;
   </t>
<t tx="leo.20151110011610.11">&lt;li&gt;&lt;p&gt;&lt;small&gt;W2-完成 Solvespace所提供的 Tutorial,學會使用基本操作&lt;a href="#/w2"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20151110011610.12">&lt;li&gt;&lt;p&gt;&lt;small&gt;W3-學習 Creo Parametric 最基本的零件繪製&lt;a href="#/w3"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20151110011610.13">&lt;li&gt;&lt;p&gt;&lt;small&gt;W4-學習 Creo Parametric 最基本的零件繪製&lt;a href="#/w4"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20151110011610.14">&lt;li&gt;&lt;p&gt;&lt;small&gt;W5-學習 Creo Parametric 最基本的零件繪製&lt;a href="#/w5"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20151110011610.15">&lt;li&gt;&lt;p&gt;&lt;small&gt;W6-建立協同網站&lt;a href="#/w6"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20151110011610.16">&lt;li&gt;&lt;p&gt;&lt;small&gt;W7-建立協同網站&lt;a href="#/w7"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20151110011610.17">&lt;li&gt;&lt;p&gt;&lt;small&gt;W8-總結&lt;a href="#/w8"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20151110011610.18">&lt;section id="w1"data-background="#FF0000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-1&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.上課攜帶筆記本、耳機、隨身硬碟&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.建立工程環境-(Ana3_lite2.7z)&lt;/p&gt;	
    &lt;p class="fragment"&gt;3.上課用電子書&lt;a href="http://www.sciencedirect.com/science/article/pii/B9780815514473500029"&gt;Engineering Problem Solving&lt;/a&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;4.Vimeo 影片嵌入&lt;/p&gt;
    &lt;p class="fragment"&gt;請連結→ &lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech from 虎尾科大機械設計工程系&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;新學期開始了，該準備收收心回來上課了，這學期"電腦輔助設計實習"感覺會學到蠻多新東西的，雖然剛開始拉，很多都聽不懂...還有許多地方還可以更好喔!&lt;/p&gt;
    &lt;p&gt;自評分數: 75分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/2"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20151110011610.19">&lt;section id="w2"data-background="#ff8000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-2&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.reveal.js 倉儲&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.指令學習:
    &lt;p class="fragment"&gt;&lt;small&gt;※git branch-檢查分支.※git branch *gh-pages*-建立分支(**內為分支名稱)&lt;/small&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;&lt;small&gt;※git checkout*gh-pages*-切換分支.※dir-檔案資料&lt;/small&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;&lt;small&gt;※git push origin gh-pages - 將近端資料推到遠端分支&lt;/small&gt;&lt;/p&gt;	
    &lt;p class="fragment"&gt;3.建立&lt;a href="http://40323150.github.io/2015cadp"&gt;個人Git hub&lt;/a&gt;課程倉儲網站&lt;/p&gt;	
     &lt;p class="fragment"&gt;&lt;a href="https://vimeo.com/145155334"&gt;Solvespace－Tutorial 實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p class="fragment highlight-blue"&gt;或slide down↓&lt;a href="#/3/2"&gt;(slide down↓)&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;TUTORIAL: ANGLE BRACKET&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155334" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;剛開始很多部分還是蠻模糊的，不過經過老師一步一步講解後，就比較好跟上進度，再加上有操作影片等，漸漸能完成本次作業，很高興能看到網站架構成功!!&lt;/p&gt;
    &lt;p&gt;自評分數: 90分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/3"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110011610.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151110011610.20">&lt;section id="w3"data-background="#FFD306"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-3&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.利用Leo editer製作各週作業分支&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.&lt;a href="http://solvespace.com/tutorial.pl"&gt;Solvespace&lt;/a&gt;介紹&lt;/p&gt;	
    &lt;p class="fragment"&gt;3.利用Leo editer編輯&lt;a href="http://40323150.github.io/2015cadp/simplest.html"&gt;作業&lt;/a&gt;投影片&lt;/p&gt;	
     &lt;p class="fragment"&gt;&lt;a href="https://vimeo.com/145155876"&gt;Creo Parametric-Corner cube實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p class="fragment highlight-green"&gt;或slide down↓&lt;a href="#/4/2"&gt;(slide down↓)&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;Creo Parametric:Procedure－Corner cube&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155876" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;用投影片弄得有點煩，一直無法修改，或達不到想要呈現的樣子，還得多加練習reveal.js 的基本語法，又新增了一樣繪圖軟體-Solvespace。整體上漸漸能熟悉工作環境並且能協助同學架設網站&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/4"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;




				
</t>
<t tx="leo.20151110011610.21">&lt;section id="w4"data-background="#00BB00"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-4&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt;
    &lt;p class="fragment"&gt;1.使用pelican建立作業分支&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.製作作業影片&lt;/p&gt;	
    &lt;p class="fragment"&gt;3.Creo Parametric 基本操作，可參考&lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;這裡&lt;/a&gt;&lt;/p&gt;	
    &lt;p class="fragment"&gt;&lt;a href="https://vimeo.com/145156351"&gt;Creo Parametric－Strut 實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p class="fragment highlight-red"&gt;或slide down↓&lt;a href="#/5/2"&gt;(slide down↓)&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;Creo Parametric:Procedure－Strut&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156351" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;使用Solvespace嘗試繪製零件，其實和其他繪圖軟體差不多，熟悉一些動作指令，以及網站參考資料，照著圖片跟著步驟，就能做出需要的模型。&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/5"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				




</t>
<t tx="leo.20151110011610.22">&lt;section id="w5"data-background="#00AEAE"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-5&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.Pro/Engineer Mechanism &lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m"&gt;&lt;/a&gt;&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.繼續完成各項進度&lt;small&gt;ex:網路建立及修正&lt;/small&gt;&lt;/p&gt;
     &lt;p class="fragment"&gt;&lt;a href="https://vimeo.com/145156576"&gt;Creo Parametric-Assembly 實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p class="fragment highlight-red"&gt;或slide down↓&lt;a href="#/6/2"&gt;(slide down↓)&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;Creo Parametric: Procedure–Assembly&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156576" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;漸入佳境，開始熟悉程式環境，並且能更有效建立及修改網站架構等等
    &lt;p&gt;自評:90分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/6"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110011610.23">&lt;section id="w6"data-background="#0000C6"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-6&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.至Git hub建立全班協同網站&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="https://github.com/2015fallhw/2015fallcadpa"&gt;全班協同倉儲&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;開始整班協同倉儲，將自己進度上傳至協同網站，剛開始比較混亂，有些人傳錯檔案，導致後續同學下載錯誤檔案，也因可能過多人同時上傳，導致網路系統崩潰。&lt;/p&gt;
    &lt;p&gt;自評:80&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/7"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110011610.24">&lt;section id="w7"data-background="#9F4D95"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-7&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.二甲 CADP 全班協同作業&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/"&gt;2015FALL 作業主頁&lt;/a&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;2.全班協同作業－40323150&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150/"&gt;2015-電腦輔助設計實習課程&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;成功將各自進度上傳至協同作業網站，並建立分支，及修改各項連結&lt;/p&gt;
    自評:75&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/8"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110011610.25">&lt;section id="w8" data-background="#000000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-8&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.2015 Fall CADP W8 總結&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="http://wordpress-2015course.rhcloud.com/?p=4281#more-4281"&gt;2015 Fall CADP W8 總結&lt;/a&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;2.CADP-二甲組員連結:&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/2015cp_hw_w7.html"&gt;2015 電腦輔助設計實習甲班 W7 示範&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;學習到這裡，終於也快經過半個學期了，總結這半學期所學到的東西也不少，時間很快就流逝掉了，以後還得多加努力!!!&lt;/p&gt;
    &lt;p&gt;自評:90&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/9"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110011610.26">&lt;section id="vid"&gt;
    &lt;section&gt;
&lt;h2&gt;實作影片回顧&lt;/h2&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;(W2)TUTORIAL:ANGLE BRACKET&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155334" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;(W3)Creo Parametric－Corner cube&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155876" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;(W4)Creo Parametric－Strut&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156351" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;(W5)Creo Parametric –Assembly&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156576" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
&lt;/section&gt;</t>
<t tx="leo.20151110011610.27">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20151110011610.28">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151110011610.29">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20151110011610.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20151110011610.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151110011610.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110011610.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110011610.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20151110011610.8">&lt;section&gt;
    &lt;h1&gt;&lt;small&gt;◎目錄&lt;/small&gt;&lt;/h1&gt;
    
				
</t>
<t tx="leo.20151110011610.9">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;
					</t>
<t tx="leo.20151110022245.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151110022245.18">&lt;section id="w1"data-background="#FF0000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-1&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt;
    &lt;p&gt;1.上課攜帶筆記本、耳機、隨身硬碟&lt;/p&gt;	
    &lt;p&gt;2.建立工程環境-(Ana3_lite2.7z)&lt;/p&gt;	
    &lt;p&gt;3.上課用電子書&lt;a href="http://www.sciencedirect.com/science/article/pii/B9780815514473500029"&gt;Engineering Problem Solving&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;4.Vimeo 影片嵌入&lt;/p&gt;
    &lt;p&gt;請連結→ &lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech from 虎尾科大機械設計工程系&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;新學期開始了，該準備收收心回來上課了，這學期"電腦輔助設計實習"感覺會學到蠻多新東西的，雖然剛開始拉，很多都聽不懂...還有許多地方還可以更好喔!&lt;/p&gt;
    &lt;p&gt;自評分數: 75分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="/#2"&gt;top&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20151110022245.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151110022245.27">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20151110022245.28">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151110022245.29">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20151110022245.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20151110022245.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151110022245.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022245.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022245.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20151110022331.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151110022331.19">&lt;section id="w2"data-background="#ff8000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-2&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;1.reveal.js 倉儲&lt;/p&gt;	
    &lt;p&gt;2.指令學習:
    &lt;p&gt;&lt;small&gt;※git branch-檢查分支.※git branch *gh-pages*-建立分支(**內為分支名稱)&lt;/small&gt;&lt;/p&gt;
    &lt;p&gt;&lt;small&gt;※git checkout*gh-pages*-切換分支.※dir-檔案資料&lt;/small&gt;&lt;/p&gt;
    &lt;p&gt;&lt;small&gt;※git push origin gh-pages - 將近端資料推到遠端分支&lt;/small&gt;&lt;/p&gt;	
    &lt;p&gt;3.建立&lt;a href="http://40323150.github.io/2015cadp"&gt;個人Git hub&lt;/a&gt;課程倉儲網站&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;剛開始很多部分還是蠻模糊的，不過經過老師一步一步講解後，就比較好跟上進度，再加上有操作影片等，漸漸能完成本次作業，很高興能看到網站架構成功!!&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/3"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110022331.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151110022331.27">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20151110022331.28">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151110022331.29">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20151110022331.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20151110022331.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151110022331.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022331.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022331.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20151110022521.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151110022521.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151110022521.20">&lt;section id="w3"data-background="#FFD306"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-3&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt;
    &lt;p&gt;1.利用Leo editer製作各週作業分支&lt;/p&gt;	
    &lt;p&gt;2.&lt;a href="http://solvespace.com/tutorial.pl"&gt;Solvespace&lt;/a&gt;介紹&lt;/p&gt;	
    &lt;p&gt;3.利用Leo editer編輯&lt;a href="http://40323150.github.io/2015cadp/simplest.html"&gt;作業&lt;/a&gt;投影片&lt;/p&gt;	
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;用投影片弄得有點煩，一直無法修改，或達不到想要呈現的樣子，還得多加練習reveal.js 的基本語法，又新增了一樣繪圖軟體-Solvespace。整體上漸漸能熟悉工作環境並且能協助同學架設網站&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/4"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;




				
</t>
<t tx="leo.20151110022521.27">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20151110022521.28">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151110022521.29">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20151110022521.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20151110022521.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151110022521.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022521.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022521.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20151110022556.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151110022556.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151110022556.21">&lt;section id="w4"data-background="#00BB00"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-4&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt;
    &lt;p&gt;使用pelican建立作業分支&lt;/p&gt;	
    &lt;p&gt;2.製作Solvespace作業影片&lt;/p&gt;
    &lt;p&gt;&lt;a href="https://vimeo.com/144714197"&gt;40323150 Solvespace－Tutorial 實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p&gt;或&lt;a href="#/5/2"&gt;slide down↓&lt;/a&gt;&lt;/p&gt;	
    &lt;p&gt;3.Creo Parametric 基本操作，可參考&lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;這裡&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;使用Solvespace嘗試繪製零件，其實和其他繪圖軟體差不多，熟悉一些動作指令，以及網站參考資料，照著圖片跟著步驟，就能做出需要的模型。&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/5"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				




</t>
<t tx="leo.20151110022556.26">&lt;section&gt;
&lt;h2&gt;Creo Parametric－Strut實作影片&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156351" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;/section&gt;</t>
<t tx="leo.20151110022556.27">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20151110022556.28">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151110022556.29">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20151110022556.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20151110022556.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151110022556.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022556.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022556.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20151110022630.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151110022630.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151110022630.22">&lt;section id="w5"data-background="#00AEAE"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-5&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;Pro/Engineer Mechanism &lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m"&gt;&lt;/a&gt;&lt;/p&gt;	
    &lt;p&gt;2.繼續完成各項進度&lt;small&gt;ex:網路建立及修正&lt;/small&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;漸入佳境，開始熟悉程式環境，並且能更有效建立及修改網站架構等等
    &lt;p&gt;自評:90&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/6"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110022630.26">&lt;section&gt;
&lt;h2&gt;Creo Parametric– Assembly實作影片&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156576" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;/section&gt;</t>
<t tx="leo.20151110022630.27">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20151110022630.28">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151110022630.29">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20151110022630.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20151110022630.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151110022630.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022630.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022630.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20151110022653.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151110022653.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151110022653.23">&lt;section id="w6"data-background="#0000C6"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-6&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;1.至Git hub建立全班協同網站&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="https://github.com/2015fallhw/2015fallcadpa"&gt;全班協同倉儲&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;開始整班協同倉儲，將自己進度上傳至協同網站，剛開始比較混亂，有些人傳錯檔案，導致後續同學下載錯誤檔案，也因可能過多人同時上傳，導致網路系統崩潰。&lt;/p&gt;
    &lt;p&gt;自評:84&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/7"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110022653.27">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20151110022653.28">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151110022653.29">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20151110022653.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20151110022653.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151110022653.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022653.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022653.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20151110022714.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151110022714.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151110022714.24">&lt;section id="w7"data-background="#9F4D95"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-7&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;1.二甲 CADP 全班協同作業&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/"&gt;2015FALL 作業主頁&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;2.全班協同作業－40323150&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150/"&gt;2015-電腦輔助設計實習課程&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;成功將各自進度上傳至協同作業網站，並建立分支，及修改各項連結&lt;/p&gt;
    自評:75&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/8"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110022714.27">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20151110022714.28">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151110022714.29">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20151110022714.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20151110022714.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151110022714.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022714.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022714.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20151110022821.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151110022821.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151110022821.25">&lt;section id="w8" data-background="#000000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-8&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;1.2015 Fall CADP W8 總結&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="http://wordpress-2015course.rhcloud.com/?p=4281#more-4281"&gt;2015 Fall CADP W8 總結&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;2.CADP-二甲組員連結:&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/2015cp_hw_w7.html"&gt;2015 電腦輔助設計實習甲班 W7 示範&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;學習到這裡，終於也快經過半個學期了，總結這半學期所學到的東西也不少，時間很快就流逝掉了，以後還得多加努力!!!&lt;/p&gt;
    &lt;p&gt;自評:90&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/9"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151110022821.27">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20151110022821.28">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151110022821.29">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20151110022821.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20151110022821.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151110022821.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022821.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151110022821.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20151110023754.1">&lt;section&gt;
&lt;h2&gt;Solvespace－Tutorial 實作影片&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155334" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;/section&gt;</t>
<t tx="leo.20151110023801.1">&lt;section&gt;
&lt;h2&gt;Creo Parametric－Corner cube實作影片&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155876" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;/section&gt;</t>
<t tx="leo.20151110033440.1">&lt;li&gt;&lt;p&gt;&lt;small&gt;實作影片&lt;a href="#/vid"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20151112121934.1"></t>
<t tx="leo.20151112121934.2"></t>
<t tx="leo.20151112121934.4"></t>
<t tx="leo.20151112121934.5"></t>
<t tx="leo.20151112121934.7"></t>
<t tx="leo.20151112121934.8"></t>
<t tx="leo.20151112123318.1"></t>
<t tx="leo.20151112123318.2"></t>
<t tx="leo.20151112123318.4"></t>
<t tx="leo.20151112123318.5"></t>
<t tx="leo.20151112123318.7"></t>
<t tx="leo.20151112123318.8"></t>
<t tx="leo.20151112123934.1"></t>
<t tx="leo.20151112123934.2"></t>
<t tx="leo.20151112123934.4"></t>
<t tx="leo.20151112123934.5"></t>
<t tx="leo.20151112123934.7"></t>
<t tx="leo.20151112123934.8"></t>
<t tx="leo.20151112140518.1"></t>
<t tx="leo.20151112140518.10">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第五週內容&lt;/h1&gt;
    &lt;p&gt;Pro/Engineer Mechanism:&lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m (Nutcracker Mechanism)"&gt;連結&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;reveal 2.0 更新&lt;p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:reveal 2.0更新後，每次都要重新git clone，多花了一些時間，但功能也有些變化&lt;/p&gt;
    &lt;p&gt;自評:75分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151112140518.11">(uncached) leo.20151107173641.13
Diff...
  &lt;section&gt;
      &lt;section&gt;
      &lt;h1&gt;第六週內容&lt;/h1&gt;
      &lt;p&gt;1.pelican 網誌與 reveal.js 投影片製作, 內容送到 Github pages&lt;/p&gt;
+     &lt;p&gt;2.Solvespace 基本操作&lt;/p&gt;
+     &lt;p&gt;3.Creo Parametric 基本操作&lt;/p&gt;
+     &lt;p&gt;4.Pro/Engineer Mechanism&lt;/p&gt;
-     &lt;p&gt;2.&lt;a href="What engineers do? "&gt;摘要&lt;/a&gt;&lt;p&gt;
-     &lt;p&gt;3.Solvespace 基本操作: &lt;a href="http://solvespace.com/tutorial.pl (簡介)"&gt;連結&lt;/a&gt;&lt;p&gt;
-     &lt;p&gt;4.Creo Parametric 基本操作: &lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;連結&lt;/a&gt;&lt;p&gt;
-     &lt;p&gt;5.Pro/Engineer Mechanism: &lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m (Nutcracker Mechanism)"&gt;連結&lt;/a&gt;&lt;p&gt;
      &lt;/section&gt;
        &lt;section&gt;
      &lt;h2&gt;心得和自評&lt;/h2&gt;
      &lt;p&gt;心得:在投影片製作時，打出來的字後請重新檢查，只要有意點錯誤，呈現的投影片就會亂，所以要再三檢查格式是否正確&lt;/p&gt;
      &lt;p&gt;自評:85分&lt;/p&gt;
      &lt;/section&gt;
  &lt;/section&gt;
- 
</t>
<t tx="leo.20151112140518.12">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第六週內容&lt;/h1&gt;
    &lt;p&gt;1.pelican 網誌與 reveal.js 投影片製作, 內容送到 Github pages&lt;/p&gt;
    &lt;p&gt;2.Solvespace 基本操作&lt;/p&gt;
    &lt;p&gt;3.Creo Parametric 基本操作&lt;/p&gt;
    &lt;p&gt;4.Pro/Engineer Mechanism&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:在投影片製作時，打出來的字後請重新檢查，只要有意點錯誤，呈現的投影片就會亂，所以要再三檢查格式是否正確&lt;/p&gt;
    &lt;p&gt;自評:85分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151112140518.13">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第六週內容&lt;/h1&gt;
    &lt;p&gt;1.pelican 網誌與 reveal.js 投影片製作, 內容送到 Github pages&lt;/p&gt;
    &lt;p&gt;2.&lt;a href="What engineers do? "&gt;摘要&lt;/a&gt;&lt;p&gt;
    &lt;p&gt;3.Solvespace 基本操作: &lt;a href="http://solvespace.com/tutorial.pl (簡介)"&gt;連結&lt;/a&gt;&lt;p&gt;
    &lt;p&gt;4.Creo Parametric 基本操作: &lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;連結&lt;/a&gt;&lt;p&gt;
    &lt;p&gt;5.Pro/Engineer Mechanism: &lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m (Nutcracker Mechanism)"&gt;連結&lt;/a&gt;&lt;p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:在投影片製作時，打出來的字後請重新檢查，只要有意點錯誤，呈現的投影片就會亂，所以要再三檢查格式是否正確&lt;/p&gt;
    &lt;p&gt;自評:85分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;

</t>
<t tx="leo.20151112140518.2">(uncached) leo.20151107173641.10
Diff...
  &lt;section&gt;
      &lt;section&gt;
      &lt;h1&gt;第三週內容&lt;/h1&gt;
      &lt;p&gt;1.reveal與js pellican網址投影片製作&lt;/p&gt;
-     &lt;p&gt;2.&lt;a href="http://www.sciencedirect.com/science/article/pii/B9780815514473500029"&gt;摘要&lt;/a&gt;&lt;/p&gt;
-     &lt;p&gt;3.Solvespace 操作: &lt;a href="http://solvespace.com/tutorial.pl"&gt;連結&lt;/a&gt; (簡介)&lt;/p&gt;
-     &lt;p&gt;4.將隨身leo安裝到近端並解壓縮網址:&lt;a href="http://140.130.17.17/public/fix.zip"&gt;連結&lt;/a&gt;&lt;/p&gt;
+     &lt;p&gt;2.摘要&lt;/p&gt;
+     &lt;p&gt;3.Solvespace操作&lt;/p&gt;
+     &lt;p&gt;4.將隨身leo網址，安裝到近端並解壓縮&lt;/p&gt;
      &lt;p&gt;5.把fix.bat打開&lt;/p&gt;
      &lt;/section&gt;
        &lt;section&gt;
      &lt;h2&gt;心得和自評&lt;/h2&gt;
      &lt;p&gt;心得:學到了Solvespace這繪圖軟體，雖說全英文比較不習慣，各種操作還有待摸索，但同時多了一個新技能!!&lt;/p&gt;
      &lt;p&gt;自評:80分&lt;/p&gt;
      &lt;/section&gt;
  &lt;/section&gt;
</t>
<t tx="leo.20151112140518.3">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第三週內容&lt;/h1&gt;
    &lt;p&gt;1.reveal與js pellican網址投影片製作&lt;/p&gt;
    &lt;p&gt;2.摘要&lt;/p&gt;
    &lt;p&gt;3.Solvespace操作&lt;/p&gt;
    &lt;p&gt;4.將隨身leo網址，安裝到近端並解壓縮&lt;/p&gt;
    &lt;p&gt;5.把fix.bat打開&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:學到了Solvespace這繪圖軟體，雖說全英文比較不習慣，各種操作還有待摸索，但同時多了一個新技能!!&lt;/p&gt;
    &lt;p&gt;自評:80分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151112140518.4">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第三週內容&lt;/h1&gt;
    &lt;p&gt;1.reveal與js pellican網址投影片製作&lt;/p&gt;
    &lt;p&gt;2.&lt;a href="http://www.sciencedirect.com/science/article/pii/B9780815514473500029"&gt;摘要&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;3.Solvespace 操作: &lt;a href="http://solvespace.com/tutorial.pl"&gt;連結&lt;/a&gt; (簡介)&lt;/p&gt;
    &lt;p&gt;4.將隨身leo安裝到近端並解壓縮網址:&lt;a href="http://140.130.17.17/public/fix.zip"&gt;連結&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;5.把fix.bat打開&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:學到了Solvespace這繪圖軟體，雖說全英文比較不習慣，各種操作還有待摸索，但同時多了一個新技能!!&lt;/p&gt;
    &lt;p&gt;自評:80分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151112140518.5">(uncached) leo.20151107173641.11
Diff...
  &lt;section&gt;
      &lt;section&gt;
      &lt;h1&gt;第四週內容&lt;/h1&gt;
-     &lt;p&gt;1.Creo Parametric 基本操作: &lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;連結&lt;/a&gt;&lt;/p&gt;
+     &lt;p&gt;1.Creo Parametric基本操作&lt;/p&gt;
      &lt;p&gt;2.Solvespace的繪圖&lt;/p&gt;
      &lt;/section&gt;
        &lt;section&gt;
      &lt;h2&gt;心得和自評&lt;/h2&gt;
      &lt;p&gt;心得:這禮拜家裡因有急事請假，所以這堂課沒上到，回來後請教同學這週課程，Creo是第一次碰，所以還要多多練習，而Solvespace有比上次更上手&lt;/p&gt;
-     &lt;p&gt;自評:65分&lt;/p&gt;
?           ^^
+     &lt;p&gt;自評:70分&lt;/p&gt;
?           ^^
      &lt;/section&gt;
  &lt;/section&gt;
</t>
<t tx="leo.20151112140518.6">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第四週內容&lt;/h1&gt;
    &lt;p&gt;1.Creo Parametric基本操作&lt;/p&gt;
    &lt;p&gt;2.Solvespace的繪圖&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:這禮拜家裡因有急事請假，所以這堂課沒上到，回來後請教同學這週課程，Creo是第一次碰，所以還要多多練習，而Solvespace有比上次更上手&lt;/p&gt;
    &lt;p&gt;自評:70分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151112140518.7">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第四週內容&lt;/h1&gt;
    &lt;p&gt;1.Creo Parametric 基本操作: &lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;連結&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;2.Solvespace的繪圖&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:這禮拜家裡因有急事請假，所以這堂課沒上到，回來後請教同學這週課程，Creo是第一次碰，所以還要多多練習，而Solvespace有比上次更上手&lt;/p&gt;
    &lt;p&gt;自評:65分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151112140518.8">(uncached) leo.20151107173641.12
Diff...
  &lt;section&gt;
      &lt;section&gt;
      &lt;h1&gt;第五週內容&lt;/h1&gt;
+     &lt;p&gt;Pro/Engineer Mechanism: reveal 2.0 更新&lt;/p&gt;
-     &lt;p&gt;Pro/Engineer Mechanism:&lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m (Nutcracker Mechanism)"&gt;連結&lt;/a&gt;&lt;/p&gt;
-     &lt;p&gt;reveal 2.0 更新&lt;p&gt;
      &lt;/section&gt;
        &lt;section&gt;
      &lt;h2&gt;心得和自評&lt;/h2&gt;
      &lt;p&gt;心得:reveal 2.0更新後，每次都要重新git clone，多花了一些時間，但功能也有些變化&lt;/p&gt;
      &lt;p&gt;自評:75分&lt;/p&gt;
      &lt;/section&gt;
  &lt;/section&gt;
</t>
<t tx="leo.20151112140518.9">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;第五週內容&lt;/h1&gt;
    &lt;p&gt;Pro/Engineer Mechanism: reveal 2.0 更新&lt;/p&gt;
    &lt;/section&gt;
      &lt;section&gt;
    &lt;h2&gt;心得和自評&lt;/h2&gt;
    &lt;p&gt;心得:reveal 2.0更新後，每次都要重新git clone，多花了一些時間，但功能也有些變化&lt;/p&gt;
    &lt;p&gt;自評:75分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
</t>
<t tx="leo.20151112140837.1"></t>
<t tx="leo.20151112140837.11"></t>
<t tx="leo.20151112140837.12"></t>
<t tx="leo.20151112140837.14"></t>
<t tx="leo.20151112140837.15"></t>
<t tx="leo.20151112140837.2"></t>
</tnodes>
</leo_file>
