<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20160107155641.2"><vh>NewHeadline</vh></v>
<v t="leo.20160107155718.1"><vh>@button user pelican</vh></v>
<v t="leo.20160107155707.1"><vh>@path ./</vh>
<v t="123.20160109232054.1"><vh>以下為 reveal 投影片</vh>
<v t="123.20160109232054.2" a="E"><vh>@clean cadpaw1.html</vh>
<v t="123.20160109232054.3" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.4" a="E"><vh>head</vh>
<v t="123.20160109232054.5"><vh>title - 標題</vh></v>
<v t="123.20160109232054.6"><vh>meta - 說明</vh></v>
<v t="123.20160109232054.7"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="123.20160109232054.8" a="E"><vh>body</vh>
<v t="123.20160109232054.9" a="E"><vh>div - reveal</vh>
<v t="123.20160109232054.10"><vh>div - slides</vh>
<v t="123.20160109232054.11"><vh>h1 - 課程說明</vh></v>
<v t="123.20160109232054.12"><vh>h1 - 開放自評規劃</vh></v>
<v t="123.20160109232054.13"><vh>h2 - 實體輔助工具</vh></v>
<v t="123.20160109232054.14"><vh>h2 - 垂直有下屬頁</vh>
<v t="123.20160109232054.15"><vh>h2</vh></v>
<v t="123.20160109232054.16"><vh>h2</vh></v>
<v t="123.20160109232054.17"><vh>h2</vh></v>
</v>
<v t="123.20160109232054.18"><vh>h2 - 內含程式碼頁面</vh>
<v t="123.20160109232054.19" a="E"><vh>pre</vh>
<v t="123.20160109232054.20"><vh>code</vh></v>
</v>
<v t="123.20160109232054.21"><vh>p</vh></v>
</v>
<v t="123.20160109232054.22"><vh>h2</vh></v>
<v t="123.20160109232054.23"><vh>內嵌 Vimeo 影片</vh></v>
<v t="123.20160109232054.24"><vh>h2</vh></v>
<v t="123.20160109232054.25"><vh>h2</vh></v>
<v t="123.20160109232054.26"><vh>markdown 頁面</vh></v>
<v t="123.20160109232054.27" a="E"><vh>h2</vh>
<v t="123.20160109232054.28"><vh>Fragement 主頁面</vh></v>
<v t="123.20160109232054.29" a="E"><vh>下屬頁面</vh>
<v t="123.20160109232054.30"><vh>h2</vh></v>
<v t="123.20160109232054.31"><vh>p</vh></v>
<v t="123.20160109232054.32"><vh>p</vh></v>
<v t="123.20160109232054.33"><vh>p</vh></v>
<v t="123.20160109232054.34"><vh>p</vh></v>
<v t="123.20160109232054.35"><vh>p</vh></v>
<v t="123.20160109232054.36"><vh>p</vh></v>
<v t="123.20160109232054.37"><vh>p</vh></v>
</v>
</v>
<v t="123.20160109232054.38"><vh>h2</vh></v>
<v t="123.20160109232054.39"><vh>p</vh>
<v t="123.20160109232054.40"><vh>a</vh></v>
<v t="123.20160109232054.41"><vh>a</vh></v>
<v t="123.20160109232054.42"><vh>a</vh></v>
<v t="123.20160109232054.43"><vh>a</vh></v>
<v t="123.20160109232054.44"><vh>a</vh></v>
<v t="123.20160109232054.45"><vh>a</vh></v>
</v>
<v t="123.20160109232054.46"><vh>h2 - 更換主題</vh></v>
<v t="123.20160109232054.47" a="E"><vh>p</vh>
<v t="123.20160109232054.48"><vh>a</vh></v>
<v t="123.20160109232054.49"><vh>a</vh></v>
<v t="123.20160109232054.50"><vh>a</vh></v>
<v t="123.20160109232054.51"><vh>a</vh></v>
<v t="123.20160109232054.52"><vh>a</vh></v>
<v t="123.20160109232054.53"><vh>a</vh></v>
<v t="123.20160109232054.54"><vh>a</vh></v>
<v t="123.20160109232054.55"><vh>a</vh></v>
<v t="123.20160109232054.56"><vh>a</vh></v>
<v t="123.20160109232054.57"><vh>a</vh></v>
<v t="123.20160109232054.58"><vh>a</vh></v>
</v>
<v t="123.20160109232054.59"><vh>h2</vh></v>
<v t="123.20160109232054.60"><vh>p</vh>
<v t="123.20160109232054.61"><vh>code</vh></v>
</v>
<v t="123.20160109232054.62"><vh>a</vh></v>
<v t="123.20160109232054.63"><vh>h2</vh></v>
<v t="123.20160109232054.64" a="E"><vh>pre</vh>
<v t="123.20160109232054.65"><vh>code</vh></v>
</v>
<v t="123.20160109232054.66"><vh>h2 - 背景填圖頁面</vh></v>
<v t="123.20160109232054.67" a="E"><vh>pre</vh>
<v t="123.20160109232054.68"><vh>code</vh></v>
</v>
<v t="123.20160109232054.69" a="E"><vh>div</vh>
<v t="123.20160109232054.70"><vh>h2</vh></v>
<v t="123.20160109232054.71"><vh>pre</vh>
<v t="123.20160109232054.72"><vh>code</vh></v>
</v>
</v>
<v t="123.20160109232054.73"><vh>h2</vh></v>
<v t="123.20160109232054.74"><vh>h2</vh></v>
<v t="123.20160109232054.75"><vh>p</vh></v>
<v t="123.20160109232054.76"><vh>pre</vh>
<v t="123.20160109232054.77"><vh>code</vh></v>
</v>
<v t="123.20160109232054.78"><vh>h2 - 背景轉換</vh></v>
<v t="123.20160109232054.79"><vh>p</vh></v>
<v t="123.20160109232054.80" a="E"><vh>pre</vh>
<v t="123.20160109232054.81"><vh>code</vh></v>
</v>
<v t="123.20160109232054.82" a="E"><vh>h2 - 內含程式碼頁面</vh>
<v t="123.20160109232054.83" a="E"><vh>pre</vh>
<v t="123.20160109232054.84"><vh>code</vh></v>
</v>
<v t="123.20160109232054.85"><vh>p</vh></v>
</v>
<v t="123.20160109232054.86"><vh>h2</vh></v>
<v t="123.20160109232054.87" a="E"><vh>ul</vh>
<v t="123.20160109232054.88"><vh>li</vh></v>
<v t="123.20160109232054.89"><vh>li</vh></v>
<v t="123.20160109232054.90"><vh>li</vh></v>
<v t="123.20160109232054.91"><vh>li</vh></v>
</v>
<v t="123.20160109232054.92"><vh>h2</vh></v>
<v t="123.20160109232054.93"><vh>ol</vh>
<v t="123.20160109232054.94"><vh>li</vh></v>
<v t="123.20160109232054.95"><vh>li</vh></v>
<v t="123.20160109232054.96"><vh>li</vh></v>
</v>
<v t="123.20160109232054.97"><vh>h2 - 表格頁面</vh></v>
<v t="123.20160109232054.98" a="E"><vh>table</vh>
<v t="123.20160109232054.99"><vh>thead</vh>
<v t="123.20160109232054.100"><vh>tr</vh>
<v t="123.20160109232054.101"><vh>th</vh></v>
<v t="123.20160109232054.102"><vh>th</vh></v>
<v t="123.20160109232054.103"><vh>th</vh></v>
</v>
</v>
<v t="123.20160109232054.104"><vh>tbody</vh>
<v t="123.20160109232054.105"><vh>tr</vh>
<v t="123.20160109232054.106"><vh>td</vh></v>
<v t="123.20160109232054.107"><vh>td</vh></v>
<v t="123.20160109232054.108"><vh>td</vh></v>
</v>
<v t="123.20160109232054.109"><vh>tr</vh>
<v t="123.20160109232054.110"><vh>td</vh></v>
<v t="123.20160109232054.111"><vh>td</vh></v>
<v t="123.20160109232054.112"><vh>td</vh></v>
</v>
<v t="123.20160109232054.113"><vh>tr</vh>
<v t="123.20160109232054.114"><vh>td</vh></v>
<v t="123.20160109232054.115"><vh>td</vh></v>
<v t="123.20160109232054.116"><vh>td</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.117"><vh>h2</vh></v>
<v t="123.20160109232054.118"><vh>p</vh>
<v t="123.20160109232054.119"><vh>q</vh></v>
</v>
<v t="123.20160109232054.120"><vh>blockquote</vh></v>
<v t="123.20160109232054.121"><vh>h2</vh></v>
<v t="123.20160109232054.122"><vh>p</vh>
<v t="123.20160109232054.123"><vh>a</vh></v>
</v>
<v t="123.20160109232054.124"><vh>h2</vh></v>
<v t="123.20160109232054.125" a="E"><vh>p</vh>
<v t="123.20160109232054.126"><vh>a</vh></v>
</v>
<v t="123.20160109232054.127"><vh>p</vh>
<v t="123.20160109232054.128"><vh>em</vh></v>
</v>
<v t="123.20160109232054.129"><vh>h2</vh></v>
<v t="123.20160109232054.130"><vh>p</vh>
<v t="123.20160109232054.131"><vh>a</vh></v>
</v>
<v t="123.20160109232054.132"><vh>iframe</vh></v>
<v t="123.20160109232054.133"><vh>h2</vh></v>
<v t="123.20160109232054.134" a="E"><vh>p</vh>
<v t="123.20160109232054.135"><vh>code</vh></v>
<v t="123.20160109232054.136"><vh>code</vh></v>
</v>
<v t="123.20160109232054.137"><vh>h2</vh></v>
<v t="123.20160109232054.138"><vh>p</vh>
<v t="123.20160109232054.139"><vh>code</vh></v>
</v>
<v t="123.20160109232054.140"><vh>pre</vh>
<v t="123.20160109232054.141"><vh>code</vh></v>
</v>
<v t="123.20160109232054.142"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="123.20160109232054.143"><vh>p</vh></v>
<v t="123.20160109232054.144" a="E"><vh>h2 unordered list 頁面</vh>
<v t="123.20160109232054.145"><vh>li</vh>
<v t="123.20160109232054.146"><vh>a</vh></v>
</v>
<v t="123.20160109232054.147"><vh>li</vh>
<v t="123.20160109232054.148"><vh>a</vh></v>
</v>
<v t="123.20160109232054.149"><vh>li</vh>
<v t="123.20160109232054.150"><vh>a</vh></v>
</v>
<v t="123.20160109232054.151"><vh>li</vh>
<v t="123.20160109232054.152"><vh>a</vh></v>
</v>
<v t="123.20160109232054.153"><vh>li</vh></v>
</v>
<v t="123.20160109232054.154"><vh>結束單頁</vh></v>
</v>
</v>
<v t="123.20160109232054.155"><vh>script</vh></v>
<v t="123.20160109232054.156"><vh>script</vh></v>
<v t="123.20160109232054.157"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.158"><vh>@clean cadpbw1.html</vh>
<v t="123.20160109232054.159"><vh>html</vh>
<v t="123.20160109232054.160" a="E"><vh>head</vh>
<v t="123.20160109232054.161"><vh>title</vh></v>
</v>
<v t="123.20160109232054.162" a="E"><vh>body</vh>
<v t="123.20160109232054.163" a="E"><vh>div</vh>
<v t="123.20160109232054.164" a="E"><vh>div</vh>
<v t="123.20160109232054.165"><vh>title page</vh>
<v t="123.20160109232054.166"><vh>標題頁下的子頁</vh></v>
</v>
<v t="123.20160109232054.167"><vh>本日要點</vh></v>
<v t="123.20160109232054.168"><vh>Anaconda Python</vh></v>
<v t="123.20160109232054.169" a="E"><vh>設計的表達方式</vh>
<v t="123.20160109232054.170"><vh>協同模式下的網際雲端內容呈現</vh></v>
</v>
<v t="123.20160109232054.171"><vh>結論</vh></v>
</v>
</v>
<v t="123.20160109232054.172"><vh>script</vh></v>
<v t="123.20160109232054.173"><vh>script</vh></v>
<v t="123.20160109232054.174"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.175"><vh>@clean cpw1.html</vh>
<v t="123.20160109232054.176"><vh>檔案說明</vh></v>
<v t="123.20160109232054.177" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.178" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.179" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.180" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.181"><vh>有關我的作業</vh></v>
<v t="123.20160109232054.182"><vh>課程規劃</vh></v>
<v t="123.20160109232054.183"><vh>作業規劃</vh></v>
<v t="123.20160109232054.184"><vh>Git 操作</vh></v>
<v t="123.20160109232054.185"><vh>Jupyter 操作</vh></v>
<v t="123.20160109232054.186"><vh>結論</vh></v>
</v>
</v>
<v t="123.20160109232054.187"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.188"><vh>@clean simplest.html</vh>
<v t="123.20160109232054.189"><vh>檔案說明</vh></v>
<v t="123.20160109232054.190" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.191" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.192" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.193" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.194"><vh>介紹</vh></v>
<v t="123.20160109232054.195"><vh>第一周</vh></v>
<v t="123.20160109232054.196"><vh>第一周心得</vh></v>
<v t="123.20160109232054.197"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.198"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.199"><vh>@clean simplest1.html</vh>
<v t="123.20160109232054.200"><vh>檔案說明</vh></v>
<v t="123.20160109232054.201" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.202" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.203" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.204" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.205"><vh>介紹</vh></v>
<v t="123.20160109232054.206"><vh>第二周</vh></v>
<v t="123.20160109232054.207"><vh>第二周心得</vh></v>
<v t="123.20160109232054.208"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.209"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.210"><vh>@clean simplest2.html</vh>
<v t="123.20160109232054.211"><vh>檔案說明</vh></v>
<v t="123.20160109232054.212" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.213" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.214" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.215" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.216"><vh>介紹</vh></v>
<v t="123.20160109232054.217"><vh>第三周</vh></v>
<v t="123.20160109232054.218"><vh>第三周心得</vh></v>
<v t="123.20160109232054.219"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.220"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.221"><vh>@clean simplest3.html</vh>
<v t="123.20160109232054.222"><vh>檔案說明</vh></v>
<v t="123.20160109232054.223" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.224" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.225" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.226" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.227"><vh>介紹</vh></v>
<v t="123.20160109232054.228"><vh>第四周</vh></v>
<v t="123.20160109232054.229"><vh>第四周心得</vh></v>
<v t="123.20160109232054.230"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.231"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.232"><vh>@clean simplest4.html</vh>
<v t="123.20160109232054.233"><vh>檔案說明</vh></v>
<v t="123.20160109232054.234" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.235" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.236" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.237" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.238"><vh>介紹</vh></v>
<v t="123.20160109232054.239"><vh>第五周</vh></v>
<v t="123.20160109232054.240"><vh>第五周心得</vh></v>
<v t="123.20160109232054.241"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.242"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.243"><vh>@clean simplest5.html</vh>
<v t="123.20160109232054.244"><vh>檔案說明</vh></v>
<v t="123.20160109232054.245" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.246" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.247" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.248" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.249"><vh>介紹</vh></v>
<v t="123.20160109232054.250"><vh>第六周</vh></v>
<v t="123.20160109232054.251"><vh>第六周心得</vh></v>
<v t="123.20160109232054.252"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.253"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.254"><vh>@clean simplest6.html</vh>
<v t="123.20160109232054.255"><vh>檔案說明</vh></v>
<v t="123.20160109232054.256"><vh>html 標註</vh>
<v t="123.20160109232054.257" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.258" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.259" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.260"><vh>介紹</vh></v>
<v t="123.20160109232054.261"><vh>第七周</vh></v>
<v t="123.20160109232054.262"><vh>第七周心得</vh></v>
<v t="123.20160109232054.263"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.264"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.265"><vh>@clean simplest7.html</vh>
<v t="123.20160109232054.266"><vh>檔案說明</vh></v>
<v t="123.20160109232054.267" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.268" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.269" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.270" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.271"><vh>介紹</vh></v>
<v t="123.20160109232054.272"><vh>第八周</vh></v>
<v t="123.20160109232054.273"><vh>第八周心得</vh></v>
<v t="123.20160109232054.274"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.275"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.276"><vh>@clean simplest8.html</vh>
<v t="123.20160109232054.277"><vh>檔案說明</vh></v>
<v t="123.20160109232054.278" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.279" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.280" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.281" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.282"><vh>介紹</vh></v>
<v t="123.20160109232054.283"><vh>第九周</vh></v>
<v t="123.20160109232054.284"><vh>第九周心得</vh></v>
<v t="123.20160109232054.285"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.286"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.287"><vh>@clean simplest9.html</vh>
<v t="123.20160109232054.288"><vh>檔案說明</vh></v>
<v t="123.20160109232054.289" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.290" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.291" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.292" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.293"><vh>介紹</vh></v>
<v t="123.20160109232054.294"><vh>第十周</vh></v>
<v t="123.20160109232054.295"><vh>第十周心得</vh></v>
<v t="123.20160109232054.296"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.297"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.298"><vh>@clean simplest10.html</vh>
<v t="123.20160109232054.299"><vh>檔案說明</vh></v>
<v t="123.20160109232054.300" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.301" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.302" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.303" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.304"><vh>介紹</vh></v>
<v t="123.20160109232054.305"><vh>第十一周</vh></v>
<v t="123.20160109232054.306"><vh>第十一周心得</vh></v>
<v t="123.20160109232054.307"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.308"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.309"><vh>@clean simplest11.html</vh>
<v t="123.20160109232054.310"><vh>檔案說明</vh></v>
<v t="123.20160109232054.311" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.312" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.313" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.314" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.315"><vh>介紹</vh></v>
<v t="123.20160109232054.316"><vh>第十二周</vh></v>
<v t="123.20160109232054.317"><vh>第十二周心得</vh></v>
<v t="123.20160109232054.318"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.319"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.320"><vh>@clean simplest12.html</vh>
<v t="123.20160109232054.321"><vh>檔案說明</vh></v>
<v t="123.20160109232054.322" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.323" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.324" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.325" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.326"><vh>介紹</vh></v>
<v t="123.20160109232054.327"><vh>第十三周</vh></v>
<v t="123.20160109232054.328"><vh>第十三周心得</vh></v>
<v t="123.20160109232054.329"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.330"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.331"><vh>@clean simplest13.html</vh>
<v t="123.20160109232054.332"><vh>檔案說明</vh></v>
<v t="123.20160109232054.333" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.334" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.335" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.336" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.337"><vh>介紹</vh></v>
<v t="123.20160109232054.338"><vh>第十四周</vh></v>
<v t="123.20160109232054.339"><vh>第十四周心得</vh></v>
<v t="123.20160109232054.340"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.341"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.342"><vh>@clean simplest14.html</vh>
<v t="123.20160109232054.343"><vh>檔案說明</vh></v>
<v t="123.20160109232054.344" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.345" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.346" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.347" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.348"><vh>介紹</vh></v>
<v t="123.20160109232054.349"><vh>第十五周</vh></v>
<v t="123.20160109232054.350"><vh>第十五周心得</vh></v>
<v t="123.20160109232054.351"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.352"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.353"><vh>@clean simplest15.html</vh>
<v t="123.20160109232054.354"><vh>檔案說明</vh></v>
<v t="123.20160109232054.355" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.356" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.357" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.358" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.359"><vh>介紹</vh></v>
<v t="123.20160109232054.360"><vh>第十六周</vh></v>
<v t="123.20160109232054.361"><vh>第十六周心得</vh></v>
<v t="123.20160109232054.362"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.363"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.364"><vh>@clean simplest16.html</vh>
<v t="123.20160109232054.365"><vh>檔案說明</vh></v>
<v t="123.20160109232054.366" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.367" a="E"><vh>body 標註</vh>
<v t="123.20160109232054.368" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109232054.369" a="E"><vh>div class="slides"</vh>
<v t="123.20160109232054.370"><vh>介紹</vh></v>
<v t="123.20160109232054.371"><vh>第十七周</vh></v>
<v t="123.20160109232054.372"><vh>第十七周心得</vh></v>
<v t="123.20160109232054.373"><vh>評分</vh></v>
</v>
</v>
<v t="123.20160109232054.374"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.375"><vh>@clean v31ref.html</vh>
<v t="123.20160109232054.376" a="E"><vh>html 標註</vh>
<v t="123.20160109232054.377"><vh>head</vh></v>
<v t="123.20160109232054.378" a="E"><vh>body</vh>
<v t="123.20160109232054.379" a="E"><vh>div - reveal and slides</vh>
<v t="123.20160109232054.380"><vh>一般單頁加上 anchor</vh></v>
<v t="123.20160109232054.381"><vh>一般單頁</vh></v>
<v t="123.20160109232054.382" a="E"><vh>垂直有下屬頁</vh>
<v t="123.20160109232054.383"><vh>下屬頁之一</vh></v>
<v t="123.20160109232054.384"><vh>下屬頁之二</vh></v>
<v t="123.20160109232054.385"><vh>下屬頁之三</vh></v>
</v>
<v t="123.20160109232054.386"><vh>一般頁面加上跳頁 anchor</vh></v>
<v t="123.20160109232054.387"><vh>markdown 頁面</vh></v>
<v t="123.20160109232054.388" a="E"><vh>逐一出現項目頁面</vh>
<v t="123.20160109232054.389"><vh>Fragement 主頁面</vh></v>
<v t="123.20160109232054.390" a="E"><vh>垂直之下屬頁面</vh>
<v t="123.20160109232054.391"><vh>標題</vh></v>
<v t="123.20160109232054.392"><vh>一般項目</vh></v>
<v t="123.20160109232054.393"><vh>逐一跳出項目 grow</vh></v>
<v t="123.20160109232054.394"><vh>逐一跳出項目 shrink</vh></v>
<v t="123.20160109232054.395"><vh>逐一跳出項目 fade-out</vh></v>
<v t="123.20160109232054.396"><vh>逐一跳出項目 cruuent-visible</vh></v>
<v t="123.20160109232054.397"><vh>逐一跳出項目 highlight-red</vh></v>
<v t="123.20160109232054.398"><vh>逐一跳出項目 highlight-blue</vh></v>
</v>
</v>
<v t="123.20160109232054.399"><vh>背景填圖頁面</vh></v>
<v t="123.20160109232054.400" a="E"><vh>內含程式碼頁面</vh>
<v t="123.20160109232054.401" a="E"><vh>pre</vh>
<v t="123.20160109232054.402"><vh>code</vh></v>
</v>
<v t="123.20160109232054.403"><vh>p</vh></v>
</v>
<v t="123.20160109232054.404" a="E"><vh>ul 資料表列</vh>
<v t="123.20160109232054.405"><vh>li</vh></v>
<v t="123.20160109232054.406"><vh>li</vh></v>
<v t="123.20160109232054.407"><vh>li</vh></v>
<v t="123.20160109232054.408"><vh>li</vh></v>
</v>
<v t="123.20160109232054.409" a="E"><vh>ol 資料表列</vh>
<v t="123.20160109232054.410"><vh>li</vh></v>
<v t="123.20160109232054.411"><vh>li</vh></v>
<v t="123.20160109232054.412"><vh>li</vh></v>
</v>
<v t="123.20160109232054.413" a="E"><vh>表格頁面</vh>
<v t="123.20160109232054.414" a="E"><vh>thead</vh>
<v t="123.20160109232054.415" a="E"><vh>tr</vh>
<v t="123.20160109232054.416"><vh>th</vh></v>
<v t="123.20160109232054.417"><vh>th</vh></v>
<v t="123.20160109232054.418"><vh>th</vh></v>
</v>
</v>
<v t="123.20160109232054.419" a="E"><vh>tbody</vh>
<v t="123.20160109232054.420"><vh>tr</vh>
<v t="123.20160109232054.421"><vh>td</vh></v>
<v t="123.20160109232054.422"><vh>td</vh></v>
<v t="123.20160109232054.423"><vh>td</vh></v>
</v>
<v t="123.20160109232054.424"><vh>tr</vh>
<v t="123.20160109232054.425"><vh>td</vh></v>
<v t="123.20160109232054.426"><vh>td</vh></v>
<v t="123.20160109232054.427"><vh>td</vh></v>
</v>
<v t="123.20160109232054.428"><vh>tr</vh>
<v t="123.20160109232054.429"><vh>td</vh></v>
<v t="123.20160109232054.430"><vh>td</vh></v>
<v t="123.20160109232054.431"><vh>td</vh></v>
</v>
</v>
</v>
<v t="123.20160109232054.432" a="E"><vh>Clever Quotes</vh>
<v t="123.20160109232054.433"><vh>q</vh></v>
<v t="123.20160109232054.434"><vh>blockquote</vh></v>
</v>
<v t="123.20160109232054.435"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="123.20160109232054.436" a="E"><vh>h2 unordered list 頁面</vh>
<v t="123.20160109232054.437"><vh>li</vh>
<v t="123.20160109232054.438"><vh>a</vh></v>
</v>
<v t="123.20160109232054.439"><vh>li</vh>
<v t="123.20160109232054.440"><vh>a</vh></v>
</v>
<v t="123.20160109232054.441"><vh>li</vh>
<v t="123.20160109232054.442"><vh>a</vh></v>
</v>
<v t="123.20160109232054.443"><vh>li</vh>
<v t="123.20160109232054.444"><vh>a</vh></v>
</v>
<v t="123.20160109232054.445"><vh>li</vh></v>
</v>
<v t="123.20160109232054.446"><vh>結束單頁</vh></v>
</v>
<v t="123.20160109232054.447"><vh>script</vh></v>
</v>
</v>
</v>
</v>
<v t="leo.20160107155707.4"><vh>@path pelican</vh>
<v t="leo.20160107155707.5"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20160107155707.6"><vh>@edit publishconf.py</vh></v>
<v t="leo.20160107155707.7" a="E"><vh>@path content</vh>
<v t="leo.20160107155707.8"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="123.20160109232441.2"><vh>@edit 2015cphww2.md</vh></v>
<v t="123.20160109232441.3"><vh>@edit 2015cphww1.md</vh></v>
<v t="123.20160109232441.5"><vh>@edit 2015cphww6.md</vh></v>
<v t="123.20160109232441.7"><vh>@edit 2015cphww8.md</vh></v>
<v t="123.20160109232441.6"><vh>@edit 2015cphww7.md</vh></v>
<v t="123.20160109232441.8"><vh>@edit 2015cphww9.md</vh></v>
<v t="123.20160109232441.11"><vh>@edit 2015cphww12.md</vh></v>
<v t="123.20160109232441.12"><vh>@edit 2015cphww13.md</vh></v>
<v t="123.20160109232441.10"><vh>@edit 2015cphww11.md</vh></v>
<v t="123.20160109232441.15"><vh>@edit 2015cphww16.md</vh></v>
<v t="123.20160109232441.9"><vh>@edit 2015cphww10.md</vh></v>
<v t="123.20160109232441.13"><vh>@edit 2015cphww14.md</vh></v>
<v t="123.20160109232441.16"><vh>@edit 2015cphww17.md</vh></v>
<v t="123.20160109232441.19"><vh>@edit 2015cpnote1.md</vh></v>
<v t="123.20160109232441.14"><vh>@edit 2015cphww15.md</vh></v>
<v t="123.20160109232441.18"><vh>@edit 2015cphww4.md</vh></v>
<v t="123.20160109232441.4"><vh>@edit 2015cphww5.md</vh></v>
<v t="123.20160109232441.17"><vh>@edit 2015cphww3.md</vh></v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="123.20160109232054.1"></t>
<t tx="123.20160109232054.10">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="123.20160109232054.100">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="123.20160109232054.101">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="123.20160109232054.102">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="123.20160109232054.103">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="123.20160109232054.104">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="123.20160109232054.105">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="123.20160109232054.106">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="123.20160109232054.107">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="123.20160109232054.108">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="123.20160109232054.109">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="123.20160109232054.11">&lt;section id="fragments"&gt;
        &lt;h1&gt;課程說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;課程名稱: 電腦輔助設計實習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;開放 主動 自學與自評&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;使用 Solvespace 與 Creo 2.0&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;每週都有作業, 由各學員自評分數&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="123.20160109232054.110">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="123.20160109232054.111">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="123.20160109232054.112">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="123.20160109232054.113">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="123.20160109232054.114">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="123.20160109232054.115">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="123.20160109232054.116">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="123.20160109232054.117">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.118">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="123.20160109232054.119">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="123.20160109232054.12">&lt;section id="fragments"&gt;
        &lt;h1&gt;自評說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;時效內的 Github 倉儲內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;完全開放的學員作業內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;彼此間可以互相學習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;存證內容: Github, copy.com, Vimeo 等&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;要怎麼收穫, 先怎麼栽!&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="123.20160109232054.120">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.121">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.122">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="123.20160109232054.123">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="123.20160109232054.124">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.125">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="123.20160109232054.126">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="123.20160109232054.127">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.128">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="123.20160109232054.129">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.13">&lt;section id="fragments"&gt;
    &lt;h2&gt;實體輔助工具&lt;/h2&gt;
    &lt;h3 class="fragment"&gt;電動折疊自行車&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;HP 伺服器&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;3D 印表機零件&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;其他需要採購工具?&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;先模擬分析, 再實際驗證?&lt;/h3&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.130">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="123.20160109232054.131">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="123.20160109232054.132">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.133">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.134">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.135">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="123.20160109232054.136">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="123.20160109232054.137">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.138">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="123.20160109232054.139">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="123.20160109232054.14">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="123.20160109232054.140">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="123.20160109232054.141">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="123.20160109232054.142">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.143">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="123.20160109232054.144">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.145">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="123.20160109232054.146">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="123.20160109232054.147">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="123.20160109232054.148">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="123.20160109232054.149">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="123.20160109232054.15">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="123.20160109232054.150">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="123.20160109232054.151">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="123.20160109232054.152">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="123.20160109232054.153">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="123.20160109232054.154">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="123.20160109232054.155">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="123.20160109232054.156">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="123.20160109232054.157">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="123.20160109232054.158">@language xml
@tabwidth -4
@others
</t>
<t tx="123.20160109232054.159">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="123.20160109232054.16">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="123.20160109232054.160">
&lt;head&gt;
@others
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;    
    &lt;!--Add support for earlier versions of Internet Explorer --&gt;
    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;
 
</t>
<t tx="123.20160109232054.161">
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015 Fall CADP B Week1&lt;/title&gt;
</t>
<t tx="123.20160109232054.162">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.163">
&lt;!-- Wrap the entire slide show in a div using the "reveal" class. --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.164">
&lt;!-- Wrap all slides in a single "slides" class --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.165">&lt;section id="title page"&gt;
&lt;section&gt;
標題頁面
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="123.20160109232054.166">&lt;section&gt;
標題頁下的子頁
&lt;/section&gt;</t>
<t tx="123.20160109232054.167">&lt;section&gt;
本日要點
&lt;/section&gt;</t>
<t tx="123.20160109232054.168">&lt;section&gt;
&lt;a href="http://continuum.io/downloads"&gt;Anaconda Python 下載&lt;/a&gt;
&lt;/section&gt;</t>
<t tx="123.20160109232054.169">&lt;section id="設計的表達方式"&gt;
&lt;section&gt;
設計的表達方式
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="123.20160109232054.17">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="123.20160109232054.170">&lt;section&gt;
協同模式下的網際雲端內容呈現
&lt;/section&gt;</t>
<t tx="123.20160109232054.171">&lt;section&gt;
結論
&lt;/section&gt;</t>
<t tx="123.20160109232054.172">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
    </t>
<t tx="123.20160109232054.173">&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
 
    </t>
<t tx="123.20160109232054.174">&lt;script&gt;
        // Required, even if empty.
        Reveal.initialize({
        });
    &lt;/script&gt;
</t>
<t tx="123.20160109232054.175">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.176">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.177">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015CP W1&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="123.20160109232054.178">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.179">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.18">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.180">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.181">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;計算機程式&lt;/h1&gt;
    &lt;p&gt;第1週教學內容&lt;/p&gt;		
&lt;/section&gt;
	</t>
<t tx="123.20160109232054.182">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;課程規劃&lt;/h1&gt;
    &lt;p&gt;教科書&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://openbookproject.net/thinkcs/python/english3e/"&gt;http://openbookproject.net/thinkcs/python/english3e/&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="123.20160109232054.183">&lt;section&gt;
    &lt;h1&gt;作業規劃&lt;/h1&gt;
    &lt;p&gt;影片內容&lt;/p&gt;
    &lt;a href="https://www.youtube.com/watch?v=9uq3w6JJS00"&gt;Zero to hero with Python&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="123.20160109232054.184">&lt;section&gt;
    &lt;h1&gt;Git 操作&lt;/h1&gt;
    &lt;p&gt;git clone&lt;/p&gt;
    &lt;p&gt;git config --global user.name&lt;/p&gt;
    &lt;p&gt;git config --global user.email&lt;/p&gt;
    &lt;p&gt;git add -A&lt;/p&gt;
    &lt;p&gt;git commit -m&lt;/p&gt;
    &lt;p&gt;git push&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="123.20160109232054.185">&lt;section&gt;
    &lt;h1&gt;Jupyter 操作&lt;/h1&gt;
    &lt;p&gt;啟動&lt;/p&gt;
    &lt;p&gt;基本執行&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="123.20160109232054.186">&lt;section&gt;
    &lt;h1&gt;結論&lt;/h1&gt;
    &lt;p&gt;自主開放學習&lt;/p&gt;
    &lt;p&gt;線上教材&lt;/p&gt;
    &lt;p&gt;影音教材&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="123.20160109232054.187">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	</t>
<t tx="123.20160109232054.188">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.189">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.19">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="123.20160109232054.190">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.191">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.192">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.193">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.194">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.195">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;筆記(第一周)&lt;/h2&gt;
    &lt;p&gt;上課記得帶筆記 1.先建立github倉儲,新增時Remade記得打勾 2.git clone 自己倉儲的網址,之後進入資料夾 cd cadpa_test 3.git branch 看在哪分之下 4.git branch gh-pages 建立分支 5.git checkout gh-pages 切換分支 下載reaval,解壓縮.複製全部除了 README.md 蓋掉 資料夾內容 1.git add -A 2.git commit -m "註解" 3.git push origin gh-pages 4.git config commit --global user.email"s9547486@yahoo.com.tw" git config commit --global user.name"40323138-1"認證 5.輸入帳密 
&lt;/section&gt;	
</t>
<t tx="123.20160109232054.196">&lt;section&gt;
        &lt;h2&gt;第一周心得&lt;/h2&gt;
        &lt;p&gt;
              第一次上課上學期是計算機程式而這學期是電腦輔助設計實習 第一周做的內容與上學期類似 所以做起來蠻順手的 還有記得下周要帶筆記阿!!&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.197">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第一周:65&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.198">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.199">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.2">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.20">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="123.20160109232054.200">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.201">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.202">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.203">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.204">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.205">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.206">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;筆記(第二周)&lt;/h2&gt;
    &lt;p&gt;1.下禮拜記得帶筆記2.開始做投影片練習

&lt;/section&gt;	
</t>
<t tx="123.20160109232054.207">&lt;section&gt;
        &lt;h2&gt;第二周心得&lt;/h2&gt;
        &lt;p&gt;
             這禮拜練習與上週相同 但推上去後會出現404的問題,留著大家去解決
自評分數
1.第二周:80
&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.208">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第二周:80&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.209">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.21">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="123.20160109232054.210">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.211">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.212">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.213">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.214">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.215">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.216">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.217">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;筆記(第三周)&lt;/h2&gt;
    &lt;p&gt;1.solvespace練習下載 2.看網站原文!!資料跟這練習&lt;/p&gt;
&lt;/section&gt;
				</t>
<t tx="123.20160109232054.218">&lt;section&gt;
        &lt;h2&gt;第三周心得&lt;/h2&gt;
        &lt;p&gt;這周練習新的軟體solvespace 相當新奇,竟然只有2.3MB 令我相當訝異,跟之前CAD,solid差很大,但使用後有蠻有趣的 學的新的繪圖軟體 &lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.219">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第三周:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.22">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.220">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.221">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.222">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.223">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.224">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.225">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.226">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.227">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.228">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;筆記(第四周)&lt;/h2&gt;
    &lt;p&gt;學習 Creo Parametric 最基本的零件繪製&lt;/p&gt;
&lt;/section&gt;
				</t>
<t tx="123.20160109232054.229">&lt;section&gt;
        &lt;h2&gt;第四周心得&lt;/h2&gt;
        &lt;p&gt;練習新的繪圖軟體Creo Parametric 之前有聽說過這軟體,聽說在以後工作上很實用,跟著網路上的說 明,一步步練習creo
自評分數
1.第四周:70
 &lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.23">&lt;section&gt;
&lt;h1&gt;嵌入 Vimeo 影片&lt;/h1&gt;
&lt;iframe src="https://player.vimeo.com/video/137724068" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程系 KMOL&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="123.20160109232054.230">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第四周:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.231">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.232">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.233">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.234">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.235">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.236">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.237">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.238">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.239">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務五&lt;/h2&gt;
    &lt;p&gt;筆記(第五周)&lt;/p&gt;
    &lt;p&gt;1.下載FIX 更新之前有問題的環境 2.去實驗室看折疊腳踏車&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.24">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.240">&lt;section&gt;
        &lt;h2&gt;第五周心得&lt;/h2&gt;
        &lt;p&gt;404問題已解絕,可能是github太久沒使用需要在信箱認證後才能繼續使用, LEO 開始出現被改壞 ,出現缺點只要一個人出錯後來要下載資料的人都會跟著clone&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.241">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第五周:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.242">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.243">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.244">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.245">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.246">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.247">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.248">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.249">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.25">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.250">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務六&lt;/h2&gt;
    &lt;p&gt;筆記(第六周)&lt;/p&gt;
    &lt;p&gt;1.終於開始要進入正課!!已建立全班共同倉儲 2.git clone 2015fallcadpa 4.與第一周的東西相同(分支...) 5.user資料夾,複製9999,copy並將它改成自己的學號,之後點進去 6.pelican裡的content,md檔案都刪掉) 7.在Leo複製@Path9999,一樣改學號 8.有9999全改成自己的學號 9.選起!自己!的節點!!按user-pelican 10.SAVE
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.251">&lt;section&gt;
        &lt;h2&gt;第六周心得&lt;/h2&gt;
        &lt;p&gt; 本周終於進入正課,開始用班級來做協統處理,大家一起做同一個東西,這時問題就來了,LEO 開始出現被改壞 ,出現缺點只要一個人出錯後來要下載資料的人都會跟著clone下錯誤的檔案,發現這缺點  &lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.252">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第六周:75&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.253">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.254">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.255">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.256">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.257">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.258">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.259">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.26">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="123.20160109232054.260">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.261">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務七&lt;/h2&gt;
    &lt;p&gt;筆記(第七周)&lt;/p&gt;
    &lt;p&gt;1.實驗室量取折疊腳踏車 2.LEO的缺點3.完成全班協統倉儲
        
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.262">&lt;section&gt;
        &lt;h2&gt;第七周心得&lt;/h2&gt;
        &lt;p&gt;因為有更多人會修理leo了,而且大家知道會壞掉,用的時候也會小心一點, 到這周我才把東西push上去,也在頁面右下角新增了自己倉儲的連結,終於做好一些東西了, 再推的時候超怕錯誤的,而且也怕被覆蓋掉,這樣我就要重做了,再來就把剩下的東西做完囉~~
自評分數
1.第七周:70
&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.263">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第七周:75&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.264">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.265">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.266">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.267">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.268">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.269">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.27">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="123.20160109232054.270">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.271">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.272">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務八&lt;/h2&gt;
    &lt;p&gt;筆記(第八周)&lt;/p&gt;
    &lt;p&gt;1.連結班上共同倉儲 2.解決衝突 3.git clone 2015fallcadpa 4.與第一周的東西相同(分支...) 5.user資料夾,複製9999,copy並將它改成自己的學號,之後點進去 6.pelican裡的content,md檔案都刪掉) 7.在Leo複製@Path9999,一樣改學號 8.將有關9999全改成自己的學號 9.加入各周內容W1,W2..... 9.選起!自己!的節點!!按user-pelican 10.SAVE
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.273">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;第八周心得分享&lt;/h2&gt;
        &lt;p&gt;很快就要期中考了,需要交報告,但每次坐時都會有人把LEO做壞了,每次都無法在課堂上完成作業練習,這次報告是在家裡做的,從前幾周老師說要帶筆記後,我第三周才開始代筆記過來做,前三周有點不應該,老師第一周就叫我們帶了,後來有作筆記,有了筆記在操作上快了許多,也能馬上知道哪裡做錯,忘記了就跟著筆記再做一次

&lt;/p&gt;
    &lt;/section&gt;
  
&lt;/section&gt;	
</t>
<t tx="123.20160109232054.274">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第八周:75&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.275">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.276">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.277">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.278">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.279">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.28">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="123.20160109232054.280">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.281">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.282">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.283">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務九&lt;/h2&gt;
    &lt;p&gt;筆記(第九周)&lt;/p&gt;
    &lt;p&gt;自評分數,繳交期中報告加緊最完&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.284">&lt;section&gt;
        &lt;h2&gt;第九周心得&lt;/h2&gt;
        &lt;p&gt; 期中報告快到了,目前還很多地方不會,上課有再聽但都沒有去,深入研究,所以很多小地方錯誤都不知道怎麼辦&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.285">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第九周:75&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.286">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.287">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.288">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.289">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.29">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="123.20160109232054.290">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.291">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.292">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.293">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.294">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十&lt;/h2&gt;
    &lt;p&gt;筆記(第十周)&lt;/p&gt;
    &lt;p&gt;繳期中報告最後一周,登入自評分數,網址&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.295">&lt;section&gt;
        &lt;h2&gt;第十周心得&lt;/h2&gt;
        &lt;p&gt;這禮拜是繳交前最後一周,期中考成績就看自己,做多少就該有多少分數,我把自己評70分不知道是高是低,該做都都有做,影片都有拍&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.296">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十周:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.297">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.298">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.299">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="123.20160109232054.30">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="123.20160109232054.300">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.301">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.302">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.303">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.304">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.305">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十一&lt;/h2&gt;
    &lt;p&gt;筆記(第十一周)&lt;/p&gt;
    &lt;p&gt;用creo畫零件,開始期中後大點名~沒來2次就要被當掉!!!!&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.306">&lt;section&gt;
        &lt;h2&gt;第十一周心得&lt;/h2&gt;
        &lt;p&gt;越來約接近我們設計系的課程了,這次畫CREO零件,要大家分小組,各自把零件分配畫完,我分配到2個,但我把全部的零件都畫過一次,為了多練習這套軟&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.307">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十一周:80&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.308">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.309">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.31">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="123.20160109232054.310">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.311">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.312">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.313">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.314">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.315">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.316">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十二&lt;/h2&gt;
    &lt;p&gt;筆記(第十二周)&lt;/p&gt;
    &lt;p&gt;上週CORE零件畫好,集合大家零件,開始做組合練習&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.317">&lt;section&gt;
        &lt;h2&gt;第十二周心得&lt;/h2&gt;
        &lt;p&gt;這次進入到零件的組合,又是新的東西,剛開始不易上手,上課時研究沒有個所以然,回家用自己的電腦練習一便,有抓到一點訣竅~~&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.318">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十二周:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.319">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.32">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="123.20160109232054.320">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.321">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.322">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.323">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.324">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.325">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.326">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138 郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.327">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十三&lt;/h2&gt;
    &lt;p&gt;筆記(第十三周)&lt;/p&gt;
    &lt;p&gt;練習LEO手動,開啟設定位置,因為舊的不能用了
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.328">&lt;section&gt;
        &lt;h2&gt;第十三周心得&lt;/h2&gt;
        &lt;p&gt;這次要我們自己修FIX的檔案,原本的不能用了,而在老師講解之前,就已經有學妹做好了,還有拍攝影片,相當厲害,是我們身為學長姊要學習典範,後來也照他影片去做也順利完成了FIX的更新修正&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.329">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十三周:75&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.33">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="123.20160109232054.330">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.331">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.332">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.333">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.334">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.335">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.336">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.337">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.338">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十四&lt;/h2&gt;
    &lt;p&gt;筆記(第十四周)&lt;/p&gt;
    &lt;p&gt;繼續畫沒畫好的零件和組合,開始講解組別協統,第二次大點名
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.339">&lt;section&gt;
        &lt;h2&gt;第十四周心得&lt;/h2&gt;
        &lt;p&gt;這周在畫CORE的組合和零件,而老師解的組別,不太清楚,有別組先做成功,但老師有說位置放錯了,而我們這組不確認怎麼做,就沒做了,先確認好問好再去做&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.34">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="123.20160109232054.340">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十四周:60&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.341">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.342">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.343">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.344">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.345">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.346">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.347">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.348">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.349">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十五&lt;/h2&gt;
    &lt;p&gt;筆記(第十五周)&lt;/p&gt;
    &lt;p&gt;學習onshape線上繪圖系統
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.35">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="123.20160109232054.350">&lt;section&gt;
        &lt;h2&gt;第十四周心得&lt;/h2&gt;
        &lt;p&gt;老師介紹onshape這網頁相當厲害,能在網路上繪圖,編劃開經過網路邊儲存,而他相當簡單,很容易上手,我們也用了之前CERO畫的那個零件當練習&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.351">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十五周:80&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.352">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.353">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.354">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.355">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.356">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.357">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.358">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.359">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.36">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="123.20160109232054.360">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十六&lt;/h2&gt;
    &lt;p&gt;筆記(第十六周)&lt;/p&gt;
    &lt;p&gt;在onshape做協統設計,做組裝&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.361">&lt;section&gt;
        &lt;h2&gt;第十六周心得&lt;/h2&gt;
        &lt;p&gt;onshape這網頁相當厲害,不但能繪圖做組合圖,還能協統,讓大家一起完成一張龐大的組合,經過分工合作後,很快能完成組裝了,而組裝時也研究了一陣子,因為都是英文的還不太懂,他的說明,經過翻譯後和試驗後才知道每個的功用,他約束條件的意思&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.362">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十五周:75&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.363">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.364">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.365">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109232054.366">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109232054.367">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.368">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.369">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109232054.37">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="123.20160109232054.370">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323138  郭鐙元&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="123.20160109232054.371">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十五&lt;/h2&gt;
    &lt;p&gt;筆記(第十五周)&lt;/p&gt;
    &lt;p&gt;1.onshape組合 2.點名 3.打自評
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="123.20160109232054.372">&lt;section&gt;
        &lt;h2&gt;第十四周心得&lt;/h2&gt;
        &lt;p&gt;其中將近開始要我們打自評,根據上次經驗,我自評打了70分,但其中分數公佈後老師只給我50分,我個人倉儲連結失敗了!!都有做都就差這一步,相信這次把連結做成公,能拿到應該有的分數,給自己一個交代,而我這次打了75希望能達成這分數&lt;/p&gt;
        
    &lt;/section&gt;
				
</t>
<t tx="123.20160109232054.373">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十五周:80&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="123.20160109232054.374">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109232054.375">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109232054.376">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="123.20160109232054.377">&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;檔案標題&lt;/title&gt;
&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
&lt;meta name="author" content="作者"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;	
&lt;/head&gt;

</t>
<t tx="123.20160109232054.378">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.379">&lt;div class="reveal"&gt;
    &lt;!-- Any section element inside of this container is displayed as a slide --&gt;
    &lt;div class="slides"&gt;
    @others
    &lt;/div&gt;
&lt;/div&gt;



</t>
<t tx="123.20160109232054.38">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.380">&lt;section&gt;
    &lt;h1&gt;Reveal.js 使用說明&lt;/h1&gt;
    &lt;h3&gt;The HTML Presentation Framework 框架&lt;/h3&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / 
    &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;
    &lt;/small&gt;
    &lt;/p&gt;
&lt;/section&gt;
	</t>
<t tx="123.20160109232054.381">&lt;section&gt;
    &lt;h2&gt;Hello There&lt;/h2&gt;
    &lt;p&gt;
reveal.js enables you to create beautiful interactive slide decks using HTML. This presentation will show you examples of what it can do.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.382">&lt;section&gt;
&lt;h1&gt;以下為垂直頁面&lt;/h1&gt;
以下為垂直頁
@others
&lt;/section&gt;

						</t>
<t tx="123.20160109232054.383">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="123.20160109232054.384">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="123.20160109232054.385">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="123.20160109232054.386">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.387">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="123.20160109232054.388">&lt;section&gt;
逐一出現
    @others
&lt;/section&gt;

						</t>
<t tx="123.20160109232054.389">&lt;section id="fragments"&gt;
    &lt;h2&gt;Fragments&lt;/h2&gt;
    &lt;p&gt;Hit the next arrow...&lt;/p&gt;
    &lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
    &lt;p&gt;
        &lt;span class="fragment"&gt;... a&lt;/span&gt; 
        &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
        &lt;span class="fragment"&gt;slide.&lt;/span&gt;
    &lt;/p&gt;
    
    &lt;aside class="notes"&gt;
    This slide has fragments which are also stepped through in the notes window.
    &lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="123.20160109232054.39">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="123.20160109232054.390">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="123.20160109232054.391">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="123.20160109232054.392">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="123.20160109232054.393">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="123.20160109232054.394">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="123.20160109232054.395">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="123.20160109232054.396">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="123.20160109232054.397">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="123.20160109232054.398">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="123.20160109232054.399">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
    &lt;pre&gt;
    &lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
    &lt;/code&gt;
    &lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="123.20160109232054.4">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="123.20160109232054.40">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="123.20160109232054.400">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.401">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="123.20160109232054.402">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="123.20160109232054.403">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="123.20160109232054.404">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.405">&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="123.20160109232054.406">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="123.20160109232054.407">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="123.20160109232054.408">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="123.20160109232054.409">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
    &lt;ol&gt;
    @others
    &lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="123.20160109232054.41">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.410">&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="123.20160109232054.411">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="123.20160109232054.412">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="123.20160109232054.413">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
    &lt;table&gt;
    @others
    &lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="123.20160109232054.414">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="123.20160109232054.415">&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="123.20160109232054.416">&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="123.20160109232054.417">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="123.20160109232054.418">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="123.20160109232054.419">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="123.20160109232054.42">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.420">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="123.20160109232054.421">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="123.20160109232054.422">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="123.20160109232054.423">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="123.20160109232054.424">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="123.20160109232054.425">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="123.20160109232054.426">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="123.20160109232054.427">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="123.20160109232054.428">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="123.20160109232054.429">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="123.20160109232054.43">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.430">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="123.20160109232054.431">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="123.20160109232054.432">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
    &lt;p&gt;
    @others
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.433">These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="123.20160109232054.434">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
					</t>
<t tx="123.20160109232054.435">&lt;section&gt;
    &lt;h2&gt;Take a Moment&lt;/h2&gt;
    &lt;p&gt;
    Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.436">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.437">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="123.20160109232054.438">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="123.20160109232054.439">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="123.20160109232054.44">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.440">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="123.20160109232054.441">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="123.20160109232054.442">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="123.20160109232054.443">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="123.20160109232054.444">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="123.20160109232054.445">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="123.20160109232054.446">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.447">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // Full list of configuration options available at:
    // https://github.com/hakimel/reveal.js#configuration
    Reveal.initialize({
        controls: true,
        progress: true,
        history: true,
        center: true,

        transition: 'slide', // none/fade/slide/convex/concave/zoom

        // Optional reveal.js plugins
        dependencies: [
            { src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
            { src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
            { src: 'plugin/zoom-js/zoom.js', async: true },
            { src: 'plugin/notes/notes.js', async: true }
        ]
    });
&lt;/script&gt;

	

		
		</t>
<t tx="123.20160109232054.45">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="123.20160109232054.46">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.47">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="123.20160109232054.48">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="123.20160109232054.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.5">&lt;meta charset="utf-8"&gt;

&lt;title&gt;2015 Fall 電腦輔助設計實習 甲班&lt;/title&gt;

</t>
<t tx="123.20160109232054.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.52">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.53">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="123.20160109232054.54">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.55">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.56">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.57">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="123.20160109232054.58">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="123.20160109232054.59">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="123.20160109232054.6">&lt;meta name="description" content="2015Fall CADP"&gt;
&lt;meta name="author" content="KMOL"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="123.20160109232054.60">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="123.20160109232054.61">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="123.20160109232054.62">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="123.20160109232054.63">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="123.20160109232054.64">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="123.20160109232054.65">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="123.20160109232054.66">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="123.20160109232054.67">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="123.20160109232054.68">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="123.20160109232054.69">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="123.20160109232054.7">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="123.20160109232054.70">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="123.20160109232054.71">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="123.20160109232054.72">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="123.20160109232054.73">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.74">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.75">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="123.20160109232054.76">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="123.20160109232054.77">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="123.20160109232054.78">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.79">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="123.20160109232054.8">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109232054.80">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="123.20160109232054.81">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="123.20160109232054.82">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.83">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="123.20160109232054.84">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="123.20160109232054.85">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="123.20160109232054.86">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.87">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="123.20160109232054.88">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="123.20160109232054.89">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="123.20160109232054.9">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="123.20160109232054.90">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="123.20160109232054.91">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="123.20160109232054.92">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.93">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="123.20160109232054.94">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="123.20160109232054.95">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="123.20160109232054.96">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="123.20160109232054.97">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="123.20160109232054.98">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="123.20160109232054.99">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="leo.20160107155641.2"></t>
<t tx="leo.20160107155707.1"></t>
<t tx="leo.20160107155707.4"></t>
<t tx="leo.20160107155707.5"></t>
<t tx="leo.20160107155707.7"></t>
<t tx="leo.20160107155707.8"></t>
<t tx="leo.20160107155718.1">@language python
import os
os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t ../../theme/pelican-octopress")
g.es("user pelican 執行完畢")</t>
</tnodes>
</leo_file>
