<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20151121093513.1" a="E"><vh>@settings</vh>
<v t="leo.20151121093513.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="leo.20151121093513.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="leo.20151121093509.2" a="E"><vh>個人專案系統</vh>
<v t="leo.20151121095223.1"><vh>設置步驟</vh></v>
<v t="leo.20151121110456.1" a="E"><vh>以下為參考用的 batch 檔案</vh>
<v t="leo.20151121110509.1"><vh>特別注意</vh></v>
</v>
<v t="leo.20151121110353.1"><vh>start.bat</vh></v>
<v t="leo.20151121110402.1"><vh>stop.bat</vh></v>
</v>
<v t="leo.20151121095153.1"><vh>有關 Brython</vh></v>
<v t="leo.20151121095254.1"><vh>@button user pelican</vh></v>
<v t="leo.20151121095330.1"><vh>以下為投影片 ------------</vh></v>
<v t="leo.20160106230311.1"><vh>@clean simplest1.html</vh>
<v t="leo.20160106230311.2"><vh>檔案說明</vh></v>
<v t="leo.20160106230311.3" a="E"><vh>html 標註</vh>
<v t="leo.20160106230311.4" a="E"><vh>body 標註</vh>
<v t="leo.20160106230311.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160106230311.6"><vh>div class="slides"</vh>
<v t="leo.20160106230311.7"><vh>封面</vh></v>
<v t="leo.20160106230311.8"><vh>W1</vh></v>
<v t="leo.20160106230311.9"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20160106230311.10"><vh>script</vh></v>
<v t="leo.20160106230311.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160106230619.1"><vh>@clean simplest2.html</vh>
<v t="leo.20160106230619.2"><vh>檔案說明</vh></v>
<v t="leo.20160106230619.3"><vh>html 標註</vh>
<v t="leo.20160106230619.4"><vh>body 標註</vh>
<v t="leo.20160106230619.5"><vh>div class="reveal"</vh>
<v t="leo.20160106230619.6"><vh>div class="slides"</vh>
<v t="leo.20160106230619.7"><vh>封面</vh></v>
<v t="leo.20160106230619.8"><vh>W2</vh></v>
<v t="leo.20160106230619.9"><vh>影片</vh></v>
<v t="leo.20160106230619.10"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20160106230619.11"><vh>script</vh></v>
<v t="leo.20160106230619.12"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160106230627.1"><vh>@clean simplest3.html</vh>
<v t="leo.20160106230627.2"><vh>檔案說明</vh></v>
<v t="leo.20160106230627.3"><vh>html 標註</vh>
<v t="leo.20160106230627.4"><vh>body 標註</vh>
<v t="leo.20160106230627.5"><vh>div class="reveal"</vh>
<v t="leo.20160106230627.6"><vh>div class="slides"</vh>
<v t="leo.20160106230627.7"><vh>封面</vh></v>
<v t="leo.20160106230627.8"><vh>W3</vh></v>
<v t="leo.20160106230627.9"><vh>影片</vh></v>
<v t="leo.20160106230627.10"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20160106230627.11"><vh>script</vh></v>
<v t="leo.20160106230627.12"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160106230252.1"><vh>@clean simplest4.html</vh>
<v t="leo.20160106230252.2"><vh>檔案說明</vh></v>
<v t="leo.20160106230252.3"><vh>html 標註</vh>
<v t="leo.20160106230252.4"><vh>body 標註</vh>
<v t="leo.20160106230252.5"><vh>div class="reveal"</vh>
<v t="leo.20160106230252.6"><vh>div class="slides"</vh>
<v t="leo.20160106230252.7"><vh>封面</vh></v>
<v t="leo.20160106230252.8"><vh>W4</vh></v>
<v t="leo.20160106230252.9"><vh>影片</vh></v>
<v t="leo.20160106230252.10"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20160106230252.11"><vh>script</vh></v>
<v t="leo.20160106230252.12"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160106230247.1"><vh>@clean simplest5.html</vh>
<v t="leo.20160106230247.2"><vh>檔案說明</vh></v>
<v t="leo.20160106230247.3"><vh>html 標註</vh>
<v t="leo.20160106230247.4"><vh>body 標註</vh>
<v t="leo.20160106230247.5"><vh>div class="reveal"</vh>
<v t="leo.20160106230247.6"><vh>div class="slides"</vh>
<v t="leo.20160106230247.7"><vh>封面</vh></v>
<v t="leo.20160106230247.8"><vh>W5</vh></v>
<v t="leo.20160106230247.9"><vh>影片</vh></v>
<v t="leo.20160106230247.10"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20160106230247.11"><vh>script</vh></v>
<v t="leo.20160106230247.12"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160106230242.1"><vh>@clean simplest6.html</vh>
<v t="leo.20160106230242.2"><vh>檔案說明</vh></v>
<v t="leo.20160106230242.3"><vh>html 標註</vh>
<v t="leo.20160106230242.4"><vh>body 標註</vh>
<v t="leo.20160106230242.5"><vh>div class="reveal"</vh>
<v t="leo.20160106230242.6"><vh>div class="slides"</vh>
<v t="leo.20160106230242.7"><vh>封面</vh></v>
<v t="leo.20160106230242.8"><vh>W6</vh></v>
<v t="leo.20160106230242.9"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20160106230242.10"><vh>script</vh></v>
<v t="leo.20160106230242.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160106230234.1"><vh>@clean simplest7.html</vh>
<v t="leo.20160106230234.2"><vh>檔案說明</vh></v>
<v t="leo.20160106230234.3"><vh>html 標註</vh>
<v t="leo.20160106230234.4"><vh>body 標註</vh>
<v t="leo.20160106230234.5"><vh>div class="reveal"</vh>
<v t="leo.20160106230234.6"><vh>div class="slides"</vh>
<v t="leo.20160106230234.7"><vh>封面</vh></v>
<v t="leo.20160106230234.8"><vh>W7</vh></v>
<v t="leo.20160106230234.9"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20160106230234.10"><vh>script</vh></v>
<v t="leo.20160106230234.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160106230211.1"><vh>@clean simplest8.html</vh>
<v t="leo.20160106230211.2"><vh>檔案說明</vh></v>
<v t="leo.20160106230211.3" a="E"><vh>html 標註</vh>
<v t="leo.20160106230211.4" a="E"><vh>body 標註</vh>
<v t="leo.20160106230211.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160106230211.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160106230211.7"><vh>封面</vh></v>
<v t="leo.20160106230211.8"><vh>W8</vh></v>
<v t="leo.20160106230211.9"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20160106230211.10"><vh>script</vh></v>
<v t="leo.20160106230211.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160106230317.1"><vh>@clean simplest.html</vh>
<v t="leo.20160106230317.2"><vh>檔案說明</vh></v>
<v t="leo.20160106230317.3" a="E"><vh>html 標註</vh>
<v t="leo.20160106230317.4" a="E"><vh>body 標註</vh>
<v t="leo.20160106230317.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160106230317.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160106230317.7"><vh>封面</vh></v>
<v t="leo.20160106230317.8"><vh>目錄</vh></v>
<v t="leo.20160106230317.9"><vh>list</vh>
<v t="leo.20160106230317.10"><vh>1</vh></v>
<v t="leo.20160106230317.11"><vh>2</vh></v>
<v t="leo.20160106230317.12"><vh>3</vh></v>
<v t="leo.20160106230317.13"><vh>4</vh></v>
<v t="leo.20160106230317.14"><vh>5</vh></v>
<v t="leo.20160106230317.15"><vh>6</vh></v>
<v t="leo.20160106230317.16"><vh>7</vh></v>
<v t="leo.20160106230317.17"><vh>8</vh></v>
<v t="leo.20160106230317.18"><vh>vid</vh></v>
</v>
<v t="leo.20160106230317.19"><vh>W1</vh></v>
<v t="leo.20160106230317.20"><vh>W2</vh></v>
<v t="leo.20160106230317.21"><vh>W3</vh></v>
<v t="leo.20160106230317.22"><vh>W4</vh></v>
<v t="leo.20160106230317.23"><vh>W5</vh></v>
<v t="leo.20160106230317.24"><vh>W6</vh></v>
<v t="leo.20160106230317.25"><vh>W7</vh></v>
<v t="leo.20160106230317.26"><vh>W8</vh></v>
<v t="leo.20160106230317.27"><vh>影片</vh></v>
<v t="leo.20160106230317.28"><vh>結束</vh></v>
</v>
</v>
<v t="leo.20160106230317.29"><vh>script</vh></v>
<v t="leo.20160106230317.30"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160107143449.1"><vh>@clean simplest11.html</vh>
<v t="leo.20160107143449.2"><vh>檔案說明</vh></v>
<v t="leo.20160107143449.3" a="E"><vh>html 標註</vh>
<v t="leo.20160107143449.4" a="E"><vh>body 標註</vh>
<v t="leo.20160107143449.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160107143449.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160107143449.7" a="E"><vh>封面</vh>
<v t="leo.20160107143449.14"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160107143449.9" a="E"><vh>W11</vh>
<v t="leo.20160107143449.14"></v>
</v>
<v t="leo.20160107143449.11" a="E"><vh>結束</vh>
<v t="leo.20160107143449.14"></v>
</v>
</v>
</v>
<v t="leo.20160107143449.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160107152555.1"><vh>@clean simplest12.html</vh>
<v t="leo.20160107152555.2"><vh>檔案說明</vh></v>
<v t="leo.20160107152555.3" a="E"><vh>html 標註</vh>
<v t="leo.20160107152555.4" a="E"><vh>body 標註</vh>
<v t="leo.20160107152555.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160107152555.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160107152555.7" a="E"><vh>封面</vh>
<v t="leo.20160107152555.12"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160107152555.9" a="E"><vh>W12</vh>
<v t="leo.20160107152555.12"></v>
</v>
<v t="leo.20160107152555.11" a="E"><vh>結束</vh>
<v t="leo.20160107152555.12"></v>
</v>
</v>
</v>
<v t="leo.20160107152555.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160110142414.1"><vh>@clean simplest13.html</vh>
<v t="leo.20160110142414.2"><vh>檔案說明</vh></v>
<v t="leo.20160110142414.3" a="E"><vh>html 標註</vh>
<v t="leo.20160110142414.4" a="E"><vh>body 標註</vh>
<v t="leo.20160110142414.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160110142414.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160110142414.7" a="E"><vh>封面</vh>
<v t="leo.20160110142414.12"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110142414.9" a="E"><vh>W13</vh>
<v t="leo.20160110142414.12"></v>
</v>
<v t="leo.20160110142414.11" a="E"><vh>結束</vh>
<v t="leo.20160110142414.12"></v>
</v>
</v>
</v>
<v t="leo.20160110142414.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160110142417.1"><vh>@clean simplest14.html</vh>
<v t="leo.20160110142417.2"><vh>檔案說明</vh></v>
<v t="leo.20160110142417.3" a="E"><vh>html 標註</vh>
<v t="leo.20160110142417.4" a="E"><vh>body 標註</vh>
<v t="leo.20160110142417.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160110142417.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160110142417.7" a="E"><vh>封面</vh>
<v t="leo.20160110142417.12"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110142417.9" a="E"><vh>W14</vh>
<v t="leo.20160110142417.12"></v>
</v>
<v t="leo.20160110142417.11" a="E"><vh>結束</vh>
<v t="leo.20160110142417.12"></v>
</v>
</v>
</v>
<v t="leo.20160110142417.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160110142419.1"><vh>@clean simplest15.html</vh>
<v t="leo.20160110142419.2"><vh>檔案說明</vh></v>
<v t="leo.20160110142419.3" a="E"><vh>html 標註</vh>
<v t="leo.20160110142419.4" a="E"><vh>body 標註</vh>
<v t="leo.20160110142419.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160110142419.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160110142419.7" a="E"><vh>封面</vh>
<v t="leo.20160110142419.12"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110142419.9" a="E"><vh>W15</vh>
<v t="leo.20160110142419.12"></v>
</v>
<v t="leo.20160110142419.11" a="E"><vh>結束</vh>
<v t="leo.20160110142419.12"></v>
</v>
</v>
</v>
<v t="leo.20160110142419.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160110142422.1"><vh>@clean simplest16.html</vh>
<v t="leo.20160110142422.2"><vh>檔案說明</vh></v>
<v t="leo.20160110142422.3" a="E"><vh>html 標註</vh>
<v t="leo.20160110142422.4" a="E"><vh>body 標註</vh>
<v t="leo.20160110142422.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160110142422.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160110142422.7" a="E"><vh>封面</vh>
<v t="leo.20160110142422.12"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110142422.9" a="E"><vh>W16</vh>
<v t="leo.20160110142422.12"></v>
</v>
<v t="leo.20160110142422.11" a="E"><vh>結束</vh>
<v t="leo.20160110142422.12"></v>
</v>
</v>
</v>
<v t="leo.20160110142422.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160110142424.1"><vh>@clean simplest17.html</vh>
<v t="leo.20160110142424.2"><vh>檔案說明</vh></v>
<v t="leo.20160110142424.3" a="E"><vh>html 標註</vh>
<v t="leo.20160110142424.4" a="E"><vh>body 標註</vh>
<v t="leo.20160110142424.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160110142424.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160110142424.7" a="E"><vh>封面</vh>
<v t="leo.20160110142424.12"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110142424.9" a="E"><vh>W17</vh>
<v t="leo.20160110142424.12"></v>
</v>
<v t="leo.20160110142424.11" a="E"><vh>結束</vh>
<v t="leo.20160110142424.12"></v>
</v>
</v>
</v>
<v t="leo.20160110142424.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160110142538.1"><vh>@clean simplest end.html</vh>
<v t="leo.20160110142538.2"><vh>檔案說明</vh></v>
<v t="leo.20160110142538.3" a="E"><vh>html 標註</vh>
<v t="leo.20160110142538.4" a="E"><vh>body 標註</vh>
<v t="leo.20160110142538.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160110142538.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160110142538.7" a="E"><vh>封面</vh>
<v t="leo.20160110142538.12"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110160539.1"><vh>目錄</vh>
<v t="leo.20160110160613.1"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110160650.1"><vh>list</vh>
<v t="leo.20160110160650.2"><vh>1</vh></v>
<v t="leo.20160110160650.3"><vh>2</vh></v>
<v t="leo.20160110160650.4"><vh>3</vh></v>
<v t="leo.20160110160650.5"><vh>4</vh></v>
<v t="leo.20160110160650.6"><vh>5</vh></v>
<v t="leo.20160110160650.7"><vh>6</vh></v>
<v t="leo.20160110160650.8"><vh>7</vh></v>
<v t="leo.20160110160650.9"><vh>8</vh></v>
<v t="leo.20160110160650.10"><vh>vid</vh></v>
<v t="leo.20160110201657.1"><vh>vid</vh></v>
</v>
<v t="leo.20160110214844.1"><vh>W11</vh>
<v t="leo.20160110215042.1"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110215101.1"><vh>W12</vh>
<v t="leo.20160110215101.2"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110215103.1"><vh>W13</vh>
<v t="leo.20160110215103.2"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110215105.1"><vh>W14</vh>
<v t="leo.20160110215105.2"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110215108.1"><vh>W15</vh>
<v t="leo.20160110215108.2"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110215110.1"><vh>W16</vh>
<v t="leo.20160110215110.2"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110215112.1"><vh>W17</vh>
<v t="leo.20160110215112.2"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110215114.1"><vh>creo</vh>
<v t="leo.20160110215114.2"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110215116.1"><vh>onshape</vh>
<v t="leo.20160110215116.2"><vh>&lt;&lt; header &gt;&gt;</vh></v>
</v>
<v t="leo.20160110142538.11"><vh>結束</vh>
<v t="leo.20160110142538.12"></v>
</v>
</v>
</v>
<v t="leo.20160110142538.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151121095422.1"><vh>@path pelican</vh>
<v t="leo.20151121095422.2"><vh>以下為設定檔 ------------</vh></v>
<v t="leo.20151121095422.3"><vh>@edit publishconf.py</vh></v>
<v t="leo.20151121095422.4" a="E"><vh>@path content</vh>
<v t="leo.20151121095422.5"><vh>以下為網誌 md 檔案 ------------</vh></v>
<v t="leo.20160106230335.1"><vh>@edit 2015cphww1.md</vh></v>
<v t="leo.20160106230341.1"><vh>@edit 2015cphww2.md</vh></v>
<v t="leo.20160106230346.1"><vh>@edit 2015cphww3.md</vh></v>
<v t="leo.20160106230353.1"><vh>@edit 2015cphww4.md</vh></v>
<v t="leo.20160106230401.1"><vh>@edit 2015cphww5.md</vh></v>
<v t="leo.20160106230406.1"><vh>@edit 2015cphww6.md</vh></v>
<v t="leo.20160106230411.1"><vh>@edit 2015cphww7.md</vh></v>
<v t="leo.20160106230418.1"><vh>@edit 2015cphww8.md</vh></v>
<v t="leo.20160110145320.1"><vh>@edit 2015cphww9.md</vh></v>
<v t="leo.20160110145322.1"><vh>@edit 2015cphww10.md</vh></v>
<v t="leo.20160106230949.1"><vh>@edit 2015cphwwall.md</vh></v>
<v t="leo.20160107153450.1"><vh>@edit 2015cphww11.md</vh></v>
<v t="leo.20160110142513.1"><vh>@edit 2015cphww12.md</vh></v>
<v t="leo.20160110142516.1"><vh>@edit 2015cphww13.md</vh></v>
<v t="leo.20160110142519.1"><vh>@edit 2015cphww14.md</vh></v>
<v t="leo.20160110142521.1"><vh>@edit 2015cphww15.md</vh></v>
<v t="leo.20160110142524.1"><vh>@edit 2015cphww16.md</vh></v>
<v t="leo.20160110142526.1"><vh>@edit 2015cphww17.md</vh></v>
<v t="leo.20160110142527.1"><vh>@edit 2015cphww end.md</vh></v>
</v>
</v>
<v t="123.20160111020855.2"><vh>Recovered Nodes</vh>
<v t="123.20160111020855.3"><vh>Recovered node "其他內容" from @clean g8_introduce.md</vh>
<v t="123.20160111020855.4"><vh>old:其他內容</vh></v>
<v t="123.20160111020855.5"><vh>new:其他內容</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="123.20160111020855.2"></t>
<t tx="123.20160111020855.3">(uncached) leo.20160106205103.2
Diff...
- &lt;h1&gt;CADPA Group8 Member:&lt;/h1&gt;
?         ^
+ &lt;h1&gt;CADPa Group8 Member:&lt;/h1&gt;
?         ^
  
  40323129 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323129"&gt;翁振端&lt;/a&gt;
  
- 40323130 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323130"&gt;康民宗&lt;/a&gt;
?                                                                             ^
+ 40323130 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323130"&gt;康明宗&lt;/a&gt;
?                                                                             ^
  
  40323132 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323132"&gt;張哲銘&lt;/a&gt;
  
  40323138 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323138"&gt;郭鐙元&lt;/a&gt;
  
  40323149 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323149"&gt;楊智堯&lt;/a&gt;
  
- 40323150 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150"&gt;詹晟弘&lt;/a&gt;
?                                                                                   -
+ 40323150 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150"&gt;詹晟弘&lt;/a&gt;</t>
<t tx="123.20160111020855.4">&lt;h1&gt;CADPa Group8 Member:&lt;/h1&gt;

40323129 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323129"&gt;翁振端&lt;/a&gt;

40323130 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323130"&gt;康明宗&lt;/a&gt;

40323132 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323132"&gt;張哲銘&lt;/a&gt;

40323138 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323138"&gt;郭鐙元&lt;/a&gt;

40323149 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323149"&gt;楊智堯&lt;/a&gt;

40323150 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150"&gt;詹晟弘&lt;/a&gt;</t>
<t tx="123.20160111020855.5">&lt;h1&gt;CADPA Group8 Member:&lt;/h1&gt;

40323129 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323129"&gt;翁振端&lt;/a&gt;

40323130 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323130"&gt;康民宗&lt;/a&gt;

40323132 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323132"&gt;張哲銘&lt;/a&gt;

40323138 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323138"&gt;郭鐙元&lt;/a&gt;

40323149 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323149"&gt;楊智堯&lt;/a&gt;

40323150 &lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150"&gt;詹晟弘&lt;/a&gt;
</t>
<t tx="leo.20151121093509.2"></t>
<t tx="leo.20151121093513.1"></t>
<t tx="leo.20151121093513.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="leo.20151121093513.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="leo.20151121095153.1">Leo Editor

Pelican

Brython

Creo Parametric Pro/Web.Link

http://www.brython.info/</t>
<t tx="leo.20151121095223.1">copy pelican button outline

copy 投影片節點

copy pelican 節點

refresh 各資料節點內容, 確定可以進行編輯存檔

測試 user-pelican 按鈕是否可以正確將 .md 檔案轉為靜態網頁</t>
<t tx="leo.20151121095254.1">@language python
import os
os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t ../../theme/pelican-octopress")
g.es("user pelican 執行完畢")</t>
<t tx="leo.20151121095330.1"></t>
<t tx="leo.20151121095422.1"></t>
<t tx="leo.20151121095422.2"></t>
<t tx="leo.20151121095422.4"></t>
<t tx="leo.20151121095422.5"></t>
<t tx="leo.20151121110353.1">@echo off
REM 設定 V 硬碟代號與 data 目錄對應
set Disk=y
subst %Disk%: "data"
REM 設定 leo 相關對應 Home 位置
set HomePath=%Disk%:\home
set HomeDrive=%Disk%:\home
set Home=%Disk%:\home
REM 設定 Leo 所用的編輯器
set LEO_EDITOR=%Disk%:\SciTE\SciTE.exe
REM 將後續的指令執行, 以 %Disk% 為主
%Disk%:
REM 設定 PYTHONPATH
set PYTHONPATH=%Disk%:\Anaconda3
REM Jupyter 設定
set JUPYTER_CONFIG_DIR=%Disk%:\home\.jupyter\profile_nbserver
REM 設定 Jre 路徑, 特別注意 CLASSPATH 後的分號, 一定要有
set JAVA_HOME=%Disk%:\Java\jre1.8.0_51
set CLASSPATH=.;
REM 設定 node.js 相關路徑
set NODE_PATH=%Disk%:\nodejs\node_modules\npm\node_modules;%Disk%:\nodejs\node_modules\npm
set path1=%PATH%;%Disk%:\Anaconda3;%Disk%:\Anaconda3\Scripts;%JAVA_HOME%\bin;%Disk%:\nodejs;
set path2=%Disk%:\apps\Git\bin;%Disk%:\apps\pandoc;%Disk%:\apps\portableLatex\MiKTeX\texmf\miktex\bin;
path=%path1%;%path2%;
REM 啟動  SciTE
start /MIN %Disk%:\SciTE\SciTE.exe
REM 取 IPV4 IP address
for /f "delims=[] tokens=2" %%a in ('ping -4 %computername% -n 1 ^| findstr "["') do (set thisip=%%a)
REM echo %thisip%
REM 取 IPV6 IP address
REM for /f "delims=[] tokens=2" %%a in ('ping %computername% -n 1 ^| findstr "["') do (set thisip=%%a)
REM echo %thisip%
REM 啟動 Jupyter
cd %Disk%:\tmp\2015fallcadpa-1.0\user\9999\content\notebook
start %Disk%:\Anaconda3\python.exe "%Disk%:\Anaconda3\Scripts\jupyter-script.py" notebook --ip=%thisip% --certfile=%Disk%:\home\ssl_cert.pem --profile=nbserver
cd ..
REM 啟動 VMEmulator
REM start %Disk%:\apps\nand2tetris\tools\VMEmulator.bat
REM 啟動 Assembler
REM start %Disk%:\apps\nand2tetris\tools\Assembler.bat
REM 啟動 CPUEmulator
REM start %Disk%:\apps\nand2tetris\tools\CPUEmulator.bat
REM 啟動 HardwareSimulator
REM start %Disk%:\apps\nand2tetris\tools\HardwareSimulator.bat
REM 啟動 JackCompiler
REM start %Disk%:\apps\nand2tetris\tools\JackCompiler.bat
REM 啟動 TextComparer
REM start %Disk%:\apps\nand2tetris\tools\TextComparer.bat
REM 啟動 node.js
REM 啟動 node.js
REM start /MIN cmd.exe /k "%Disk%:\nodejs\nodejsvars.bat"
REM start %Disk%:\nodejs\node.exe
start /MIN cmd.exe
start /MIN cmd.exe
start /MIN cmd.exe
REM 啟動 node.js
REM start %Disk%:\IDE\nodejs\node.exe
REM C:\WINDOWS\system32\cmd.exe /k %Disk%:\IDE\nodejs\nodejsvars.bat
REM 啟動 Leo 編輯器
REM %Disk%:\IDE\Python33\python.exe %Disk%:\commands\launchLeo.py
python.exe %Disk%:\apps\launchLeo.py
Exit
</t>
<t tx="leo.20151121110402.1">@echo off
set Disk=y
REM 關閉 mongoose
REM taskkill /IM mongoose.exe /F
REM 關閉 nginx
REM taskkill /IM nginx.exe /F
REM 關閉 SciTE
taskkill /IM SciTE.exe /F
REM 關閉 python
taskkill /IM python.exe /F
REM 清除 log 資料
REM 清除 log 資料
path=%PATH%;
REM del /Q /F  V:\wwwServers\logs\*.*
REM del /Q /F V:\wwwServers\nginx-1.2.3\logs\*.*
REM del /Q /F V:\www\cmsimplexh_20130809\cmsimple\log.txt
del /Q /F  V:\tmp\*.*
REM copy V:\www\cmsimplexh_20130809\cmsimple\log_clean.txt V:\www\cmsimpleSpring2013\cmsimple\log.txt
path=%PATH%;
del /Q /F  V:\tmp\*.*
REM 終止虛擬硬碟與目錄的對應
subst %Disk%: /D
REM 關閉 cmd 指令視窗
taskkill /IM cmd.exe /F
EXIT
</t>
<t tx="leo.20151121110456.1"></t>
<t tx="leo.20151121110509.1">若在 Leo Editor 以 @edit 編輯 .bat 檔案, 必須將 @language batch 刪除, 否則 .bat 無法正確執行

發生此一錯誤的原因不明</t>
<t tx="leo.20160106230211.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160106230211.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160106230211.11">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20160106230211.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160106230211.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20160106230211.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160106230211.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230211.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230211.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20160106230211.8">&lt;section id="w8" data-background="#000000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-8&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;1.2015 Fall CADP W8 總結&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="http://wordpress-2015course.rhcloud.com/?p=4281#more-4281"&gt;2015 Fall CADP W8 總結&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;2.CADP-二甲組員連結:&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/2015cp_hw_w7.html"&gt;2015 電腦輔助設計實習甲班 W7 示範&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;學習到這裡，終於也快經過半個學期了，總結這半學期所學到的東西也不少，時間很快就流逝掉了，以後還得多加努力!!!&lt;/p&gt;
    &lt;p&gt;自評:90&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/1"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230211.9">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20160106230234.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160106230234.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160106230234.11">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20160106230234.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160106230234.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20160106230234.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160106230234.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230234.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230234.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20160106230234.8">&lt;section id="w7"data-background="#9F4D95"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-7&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;1.二甲 CADP 全班協同作業&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/"&gt;2015FALL 作業主頁&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;2.全班協同作業－40323150&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150/"&gt;2015-電腦輔助設計實習課程&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;成功將各自進度上傳至協同作業網站，並建立分支，及修改各項連結&lt;/p&gt;
    自評:75&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/8"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230234.9">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20160106230242.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160106230242.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160106230242.11">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20160106230242.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160106230242.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20160106230242.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160106230242.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230242.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230242.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20160106230242.8">&lt;section id="w6"data-background="#0000C6"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-6&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;1.至Git hub建立全班協同網站&lt;/p&gt;
    &lt;p&gt;連結請參考:&lt;a href="https://github.com/2015fallhw/2015fallcadpa"&gt;全班協同倉儲&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;開始整班協同倉儲，將自己進度上傳至協同網站，剛開始比較混亂，有些人傳錯檔案，導致後續同學下載錯誤檔案，也因可能過多人同時上傳，導致網路系統崩潰。&lt;/p&gt;
    &lt;p&gt;自評:84&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/7"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230242.9">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20160106230247.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160106230247.10">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20160106230247.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160106230247.12">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20160106230247.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160106230247.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20160106230247.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160106230247.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230247.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230247.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20160106230247.8">&lt;section id="w5"data-background="#00AEAE"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-5&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;Pro/Engineer Mechanism &lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m"&gt;&lt;/a&gt;&lt;/p&gt;	
    &lt;p&gt;2.繼續完成各項進度&lt;small&gt;ex:網路建立及修正&lt;/small&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;漸入佳境，開始熟悉程式環境，並且能更有效建立及修改網站架構等等
    &lt;p&gt;自評:90&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/6"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230247.9">&lt;section&gt;
&lt;h2&gt;Creo Parametric– Assembly實作影片&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156576" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;/section&gt;</t>
<t tx="leo.20160106230252.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160106230252.10">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20160106230252.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160106230252.12">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20160106230252.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160106230252.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20160106230252.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160106230252.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230252.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230252.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20160106230252.8">&lt;section id="w4"data-background="#00BB00"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-4&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt;
    &lt;p&gt;使用pelican建立作業分支&lt;/p&gt;	
    &lt;p&gt;2.製作Solvespace作業影片&lt;/p&gt;
    &lt;p&gt;&lt;a href="https://vimeo.com/144714197"&gt;40323150 Solvespace－Tutorial 實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p&gt;或&lt;a href="#/5/2"&gt;slide down↓&lt;/a&gt;&lt;/p&gt;	
    &lt;p&gt;3.Creo Parametric 基本操作，可參考&lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;這裡&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;使用Solvespace嘗試繪製零件，其實和其他繪圖軟體差不多，熟悉一些動作指令，以及網站參考資料，照著圖片跟著步驟，就能做出需要的模型。&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/5"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				




</t>
<t tx="leo.20160106230252.9">&lt;section&gt;
&lt;h2&gt;Creo Parametric－Strut實作影片&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156351" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;/section&gt;</t>
<t tx="leo.20160106230311.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160106230311.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160106230311.11">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20160106230311.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160106230311.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20160106230311.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160106230311.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230311.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230311.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20160106230311.8">&lt;section id="w1"data-background="#FF0000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-1&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt;
    &lt;p&gt;1.上課攜帶筆記本、耳機、隨身硬碟&lt;/p&gt;	
    &lt;p&gt;2.建立工程環境-(Ana3_lite2.7z)&lt;/p&gt;	
    &lt;p&gt;3.上課用電子書&lt;a href="http://www.sciencedirect.com/science/article/pii/B9780815514473500029"&gt;Engineering Problem Solving&lt;/a&gt;&lt;/p&gt;
    &lt;p&gt;4.Vimeo 影片嵌入&lt;/p&gt;
    &lt;p&gt;請連結→ &lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech from 虎尾科大機械設計工程系&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;新學期開始了，該準備收收心回來上課了，這學期"電腦輔助設計實習"感覺會學到蠻多新東西的，雖然剛開始拉，很多都聽不懂...還有許多地方還可以更好喔!&lt;/p&gt;
    &lt;p&gt;自評分數: 75分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="/#2"&gt;top&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20160106230311.9">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20160106230317.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160106230317.10">&lt;li&gt;&lt;p&gt;&lt;small&gt;W1-利用 Leo Editor 摘要重點, 建立個人 Github 課程倉儲&lt;a href="#/w1"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;
   </t>
<t tx="leo.20160106230317.11">&lt;li&gt;&lt;p&gt;&lt;small&gt;W2-完成 Solvespace所提供的 Tutorial,學會使用基本操作&lt;a href="#/w2"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160106230317.12">&lt;li&gt;&lt;p&gt;&lt;small&gt;W3-學習 Creo Parametric 最基本的零件繪製&lt;a href="#/w3"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160106230317.13">&lt;li&gt;&lt;p&gt;&lt;small&gt;W4-學習 Creo Parametric 最基本的零件繪製&lt;a href="#/w4"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160106230317.14">&lt;li&gt;&lt;p&gt;&lt;small&gt;W5-學習 Creo Parametric 最基本的零件繪製&lt;a href="#/w5"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160106230317.15">&lt;li&gt;&lt;p&gt;&lt;small&gt;W6-建立協同網站&lt;a href="#/w6"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160106230317.16">&lt;li&gt;&lt;p&gt;&lt;small&gt;W7-建立協同網站&lt;a href="#/w7"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160106230317.17">&lt;li&gt;&lt;p&gt;&lt;small&gt;W8-總結&lt;a href="#/w8"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160106230317.18">&lt;li&gt;&lt;p&gt;&lt;small&gt;實作影片&lt;a href="#/vid"&gt;→&lt;/a&gt;&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160106230317.19">&lt;section id="w1"data-background="#FF0000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-1&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.上課攜帶筆記本、耳機、隨身硬碟&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.建立工程環境-(Ana3_lite2.7z)&lt;/p&gt;	
    &lt;p class="fragment"&gt;3.上課用電子書&lt;a href="http://www.sciencedirect.com/science/article/pii/B9780815514473500029"&gt;Engineering Problem Solving&lt;/a&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;4.Vimeo 影片嵌入&lt;/p&gt;
    &lt;p class="fragment"&gt;請連結→ &lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech from 虎尾科大機械設計工程系&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;新學期開始了，該準備收收心回來上課了，這學期"電腦輔助設計實習"感覺會學到蠻多新東西的，雖然剛開始拉，很多都聽不懂...還有許多地方還可以更好喔!&lt;/p&gt;
    &lt;p&gt;自評分數: 75分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/2"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20160106230317.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160106230317.20">&lt;section id="w2"data-background="#ff8000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-2&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.reveal.js 倉儲&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.指令學習:
    &lt;p class="fragment"&gt;&lt;small&gt;※git branch-檢查分支.※git branch *gh-pages*-建立分支(**內為分支名稱)&lt;/small&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;&lt;small&gt;※git checkout*gh-pages*-切換分支.※dir-檔案資料&lt;/small&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;&lt;small&gt;※git push origin gh-pages - 將近端資料推到遠端分支&lt;/small&gt;&lt;/p&gt;	
    &lt;p class="fragment"&gt;3.建立&lt;a href="http://40323150.github.io/2015cadp"&gt;個人Git hub&lt;/a&gt;課程倉儲網站&lt;/p&gt;	
     &lt;p class="fragment"&gt;&lt;a href="https://vimeo.com/145155334"&gt;Solvespace－Tutorial 實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p class="fragment highlight-blue"&gt;或slide down↓&lt;a href="#/3/2"&gt;(slide down↓)&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;TUTORIAL: ANGLE BRACKET&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155334" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;剛開始很多部分還是蠻模糊的，不過經過老師一步一步講解後，就比較好跟上進度，再加上有操作影片等，漸漸能完成本次作業，很高興能看到網站架構成功!!&lt;/p&gt;
    &lt;p&gt;自評分數: 90分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/3"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230317.21">&lt;section id="w3"data-background="#FFD306"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-3&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.利用Leo editer製作各週作業分支&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.&lt;a href="http://solvespace.com/tutorial.pl"&gt;Solvespace&lt;/a&gt;介紹&lt;/p&gt;	
    &lt;p class="fragment"&gt;3.利用Leo editer編輯&lt;a href="http://40323150.github.io/2015cadp/simplest.html"&gt;作業&lt;/a&gt;投影片&lt;/p&gt;	
     &lt;p class="fragment"&gt;&lt;a href="https://vimeo.com/145155876"&gt;Creo Parametric-Corner cube實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p class="fragment highlight-green"&gt;或slide down↓&lt;a href="#/4/2"&gt;(slide down↓)&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;Creo Parametric:Procedure－Corner cube&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155876" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;用投影片弄得有點煩，一直無法修改，或達不到想要呈現的樣子，還得多加練習reveal.js 的基本語法，又新增了一樣繪圖軟體-Solvespace。整體上漸漸能熟悉工作環境並且能協助同學架設網站&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/4"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;




				
</t>
<t tx="leo.20160106230317.22">&lt;section id="w4"data-background="#00BB00"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-4&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt;
    &lt;p class="fragment"&gt;1.使用pelican建立作業分支&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.製作作業影片&lt;/p&gt;	
    &lt;p class="fragment"&gt;3.Creo Parametric 基本操作，可參考&lt;a href="https://copy.com/97ZkQ0UqfVUPTxn8"&gt;這裡&lt;/a&gt;&lt;/p&gt;	
    &lt;p class="fragment"&gt;&lt;a href="https://vimeo.com/145156351"&gt;Creo Parametric－Strut 實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p class="fragment highlight-red"&gt;或slide down↓&lt;a href="#/5/2"&gt;(slide down↓)&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;Creo Parametric:Procedure－Strut&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156351" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;使用Solvespace嘗試繪製零件，其實和其他繪圖軟體差不多，熟悉一些動作指令，以及網站參考資料，照著圖片跟著步驟，就能做出需要的模型。&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/5"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				




</t>
<t tx="leo.20160106230317.23">&lt;section id="w5"data-background="#00AEAE"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-5&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.Pro/Engineer Mechanism &lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m"&gt;&lt;/a&gt;&lt;/p&gt;	
    &lt;p class="fragment"&gt;2.繼續完成各項進度&lt;small&gt;ex:網路建立及修正&lt;/small&gt;&lt;/p&gt;
     &lt;p class="fragment"&gt;&lt;a href="https://vimeo.com/145156576"&gt;Creo Parametric-Assembly 實作影片&lt;/a&gt; 點選觀看&lt;/p&gt;
    &lt;p class="fragment highlight-red"&gt;或slide down↓&lt;a href="#/6/2"&gt;(slide down↓)&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;Creo Parametric: Procedure–Assembly&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156576" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;漸入佳境，開始熟悉程式環境，並且能更有效建立及修改網站架構等等
    &lt;p&gt;自評:90分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/6"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230317.24">&lt;section id="w6"data-background="#0000C6"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-6&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.至Git hub建立全班協同網站&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="https://github.com/2015fallhw/2015fallcadpa"&gt;全班協同倉儲&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;開始整班協同倉儲，將自己進度上傳至協同網站，剛開始比較混亂，有些人傳錯檔案，導致後續同學下載錯誤檔案，也因可能過多人同時上傳，導致網路系統崩潰。&lt;/p&gt;
    &lt;p&gt;自評:80&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/7"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230317.25">&lt;section id="w7"data-background="#9F4D95"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-7&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.二甲 CADP 全班協同作業&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/"&gt;2015FALL 作業主頁&lt;/a&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;2.全班協同作業－40323150&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150/"&gt;2015-電腦輔助設計實習課程&lt;/a&gt;&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;成功將各自進度上傳至協同作業網站，並建立分支，及修改各項連結&lt;/p&gt;
    自評:75&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/8"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230317.26">&lt;section id="w8" data-background="#000000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-8&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p class="fragment"&gt;1.2015 Fall CADP W8 總結&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="http://wordpress-2015course.rhcloud.com/?p=4281#more-4281"&gt;2015 Fall CADP W8 總結&lt;/a&gt;&lt;/p&gt;
    &lt;p class="fragment"&gt;2.CADP-二甲組員連結:&lt;/p&gt;
    &lt;p class="fragment"&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/2015cp_hw_w7.html"&gt;2015 電腦輔助設計實習甲班 W7 示範&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;學習到這裡，終於也快經過半個學期了，總結這半學期所學到的東西也不少，時間很快就流逝掉了，以後還得多加努力!!!&lt;/p&gt;
    &lt;p&gt;自評:90&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/9"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230317.27">&lt;section id="vid"&gt;
    &lt;section&gt;
&lt;h2&gt;實作影片回顧&lt;/h2&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;(W2)TUTORIAL:ANGLE BRACKET&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155334" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;(W3)Creo Parametric－Corner cube&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155876" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;(W4)Creo Parametric－Strut&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156351" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;(W5)Creo Parametric –Assembly&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145156576" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
&lt;/section&gt;</t>
<t tx="leo.20160106230317.28">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20160106230317.29">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160106230317.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20160106230317.30">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20160106230317.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160106230317.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230317.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230317.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20160106230317.8">&lt;section&gt;
    &lt;h1&gt;&lt;small&gt;◎目錄&lt;/small&gt;&lt;/h1&gt;
    
				
</t>
<t tx="leo.20160106230317.9">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;
					</t>
<t tx="leo.20160106230619.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160106230619.10">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20160106230619.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160106230619.12">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20160106230619.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160106230619.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20160106230619.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160106230619.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230619.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230619.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20160106230619.8">&lt;section id="w2"data-background="#ff8000"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-2&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
    &lt;p&gt;1.reveal.js 倉儲&lt;/p&gt;	
    &lt;p&gt;2.指令學習:
    &lt;p&gt;&lt;small&gt;※git branch-檢查分支.※git branch *gh-pages*-建立分支(**內為分支名稱)&lt;/small&gt;&lt;/p&gt;
    &lt;p&gt;&lt;small&gt;※git checkout*gh-pages*-切換分支.※dir-檔案資料&lt;/small&gt;&lt;/p&gt;
    &lt;p&gt;&lt;small&gt;※git push origin gh-pages - 將近端資料推到遠端分支&lt;/small&gt;&lt;/p&gt;	
    &lt;p&gt;3.建立&lt;a href="http://40323150.github.io/2015cadp"&gt;個人Git hub&lt;/a&gt;課程倉儲網站&lt;/p&gt;	
    &lt;/section&gt;
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;剛開始很多部分還是蠻模糊的，不過經過老師一步一步講解後，就比較好跟上進度，再加上有操作影片等，漸漸能完成本次作業，很高興能看到網站架構成功!!&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/3"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20160106230619.9">&lt;section&gt;
&lt;h2&gt;Solvespace－Tutorial 實作影片&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155334" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;/section&gt;</t>
<t tx="leo.20160106230627.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160106230627.10">    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
				
</t>
<t tx="leo.20160106230627.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160106230627.12">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="leo.20160106230627.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160106230627.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;40323150－電腦輔助設計實習&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="leo.20160106230627.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160106230627.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230627.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160106230627.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
&lt;/section&gt;
</t>
<t tx="leo.20160106230627.8">&lt;section id="w3"data-background="#FFD306"&gt;
    &lt;section&gt;
    &lt;h1&gt;作業Mission-3&lt;/h1&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt;
    &lt;p&gt;1.利用Leo editer製作各週作業分支&lt;/p&gt;	
    &lt;p&gt;2.&lt;a href="http://solvespace.com/tutorial.pl"&gt;Solvespace&lt;/a&gt;介紹&lt;/p&gt;	
    &lt;p&gt;3.利用Leo editer編輯&lt;a href="http://40323150.github.io/2015cadp/simplest.html"&gt;作業&lt;/a&gt;投影片&lt;/p&gt;	
     &lt;section&gt;
    &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
    &lt;p&gt;用投影片弄得有點煩，一直無法修改，或達不到想要呈現的樣子，還得多加練習reveal.js 的基本語法，又新增了一樣繪圖軟體-Solvespace。整體上漸漸能熟悉工作環境並且能協助同學架設網站&lt;/p&gt;
    &lt;p&gt;自評分數: 85分&lt;/p&gt;
    &lt;p&gt;－&lt;a href="#/4"&gt;top&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;




				
</t>
<t tx="leo.20160106230627.9">&lt;section&gt;
&lt;h2&gt;Creo Parametric－Corner cube實作影片&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/145155876" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;/section&gt;</t>
<t tx="leo.20160107143449.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160107143449.11">&lt;&lt; header &gt;&gt;

    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;/section&gt;
&lt;/section&gt;
			
				
</t>
<t tx="leo.20160107143449.14">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "課程: 電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160107143449.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160107143449.2">&lt;!--
cadp w12 講課內容投影片
--&gt;
</t>
<t tx="leo.20160107143449.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;CADP W12 課程內容&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20160107143449.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160107143449.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;

&lt;!-- 出現在每一頁的 header 格式 --&gt;

&lt;header style="position: absolute;top: 20px; left: 20px; font-size:20px;background-color: rgba(150,150,0,0.5)"&gt;&lt;/header&gt;

&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160107143449.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160107143449.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;&lt; header &gt;&gt;

    &lt;section id="hw-task-one"&gt;
    &lt;p&gt;&lt;font size="5" color="ffff00"&gt;&lt;marquee scrollamount="10" direction="down" width="400" height="200" behavior="alternate" style="border:solid"&gt;
  &lt;marquee behavior="alternate"&gt;
    版本更新於105年01月07日
  &lt;/marquee&gt;
&lt;/marquee&gt;&lt;/font&gt;&lt;/p&gt;
    &lt;style&gt;.header1 header:after { content: "Header 1 Example"; }&lt;/style&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
    &lt;/section&gt;
&lt;/section&gt;

    
    

	
</t>
<t tx="leo.20160107143449.9">&lt;&lt; header &gt;&gt;

        &lt;section&gt;
            &lt;h1&gt;作業Mission-11&lt;/h1&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;期中過後介紹接下來程序&lt;/p&gt;
            &lt;p&gt;介紹Nutcracker機構零件，並使用Creo繪製&lt;/p&gt;
            &lt;p&gt;開始分組，使用組別完成各自進度並上傳至群組網站&lt;/p&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;經過半個學期了，考完期中考後，雖然是放下了心中一顆石頭，但過了不久這學期感覺就要結束了，總之希望能把期中那份熱情繼續延續下去。&lt;/p&gt;
            &lt;p&gt;自評分數:75分&lt;/p&gt;
        &lt;/section&gt;
        &lt;/section&gt;
&lt;/section&gt;</t>
<t tx="leo.20160107152555.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160107152555.11">&lt;&lt; header &gt;&gt;

    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;/section&gt;
&lt;/section&gt;
			
				
</t>
<t tx="leo.20160107152555.12">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { 
display: block;
white-space: pre;
content: "課程: 電腦輔助設計實習A 學號:40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160107152555.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160107152555.2">&lt;!--
cadp w12 講課內容投影片
--&gt;
</t>
<t tx="leo.20160107152555.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;CADP W12 課程內容&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20160107152555.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160107152555.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;

&lt;!-- 出現在每一頁的 header 格式 --&gt;

&lt;header style="position: absolute;top: 20px; left: 20px; z-index:300; font-size:30px;background-color: rgba(255,255,255,0.2)"&gt;&lt;/header&gt;

&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160107152555.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160107152555.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;&lt; header &gt;&gt;

  &lt;marquee scrollamount="15"&gt;&lt;font size="60"&gt;
來畫我啊~~~&lt;img src="https://copy.com/mHTybiLVZUdsMnpX" width="400" height="300"&gt;&lt;/font&gt;
&lt;/marquee&gt;
    &lt;style&gt;.header1 header:after { content: "Header 1 Example"; }&lt;/style&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
    &lt;/section&gt;
&lt;/section&gt;

    
    

	
</t>
<t tx="leo.20160107152555.9">&lt;&lt; header &gt;&gt;

        &lt;section&gt;
            &lt;h1&gt;作業Mission-12&lt;/h1&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;1.利用Creo繪製 Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;2.Nutcracker機構零件&lt;/p&gt; 
            &lt;p&gt;連結請參考:&lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m"&gt;Nutcracker機構零件&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;3.各組協同網站:&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/"&gt;2015FALL CADPA 作業主頁&lt;/a&gt;&lt;/p&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;找完組員後，分配各自的工作，開始用Creo繪製Nutcracker機構零件，這週開始要把之前user的節點刪除，得自己編輯新的節點才能備份之前的資料，以及建立新的節點。&lt;/p&gt;
            &lt;p&gt;自評分數:80分&lt;/p&gt;
        &lt;/section&gt;
        &lt;/section&gt;
&lt;/section&gt;</t>
<t tx="leo.20160110142414.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160110142414.11">&lt;&lt; header &gt;&gt;

    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;p&gt;&lt;a href="#/hw-task-one"&gt;返回首頁&lt;/a&gt;
    &lt;/section&gt;
&lt;/section&gt;
			
				
</t>
<t tx="leo.20160110142414.12">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "課程: 電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110142414.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160110142414.2">&lt;!--
cadp w12 講課內容投影片
--&gt;
</t>
<t tx="leo.20160110142414.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;CADP W12 課程內容&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20160110142414.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160110142414.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;

&lt;!-- 出現在每一頁的 header 格式 --&gt;

&lt;header style="position: absolute;top: 20px; left: 20px; font-size:20px;background-color: rgba(150,150,0,0.5)"&gt;&lt;/header&gt;

&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142414.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142414.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;&lt; header &gt;&gt;

   &lt;marquee direction="up" height="50" scrollamount="1"&gt;
本週要點:利用Creo繪製 Nutcracker機構零件&lt;/marquee&gt;
    &lt;style&gt;.header1 header:after { content: "Header 1 Example"; }&lt;/style&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
    &lt;/section&gt;
&lt;/section&gt;

    
    

	
</t>
<t tx="leo.20160110142414.9">&lt;&lt; header &gt;&gt;

        &lt;section&gt;
            &lt;h1&gt;作業Mission-13&lt;/h1&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;利用Creo繪製 Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;利用fix.bat修復程式環境 開啟Leo編輯倉儲&lt;/p&gt;
            &lt;p&gt;利用leo編輯個人及群組倉儲&lt;/p&gt;
            &lt;p&gt;介紹Header用法&lt;/p&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;介紹了投影片新的用法－header 能將自己的學號固定顯示在投影片上方，也說到了跑馬燈，試了幾個玩一玩，效果感覺還不錯!!對之後製作心得等應該會有很大的用途~~&lt;/p&gt;
            &lt;p&gt;自評:80&lt;/p&gt;
        &lt;/section&gt;
        &lt;/section&gt;
&lt;/section&gt;</t>
<t tx="leo.20160110142417.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160110142417.11">&lt;&lt; header &gt;&gt;

    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;/section&gt;
&lt;/section&gt;
			
				
</t>
<t tx="leo.20160110142417.12">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "課程: 電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110142417.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160110142417.2">&lt;!--
cadp w12 講課內容投影片
--&gt;
</t>
<t tx="leo.20160110142417.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;CADP W12 課程內容&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20160110142417.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160110142417.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;

&lt;!-- 出現在每一頁的 header 格式 --&gt;

&lt;header style="position: absolute;top: 20px; left: 20px; font-size:20px;background-color: rgba(150,150,0,0.5)"&gt;&lt;/header&gt;

&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142417.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142417.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;&lt; header &gt;&gt;

     &lt;marquee behavior="slide"scrollamount="15"&gt;
何謂工程??&lt;/marquee&gt;
&lt;marquee behavior="slide"scrollamount="10"&gt;
Ans:利用科學方法解決問題的人&lt;/marquee&gt;
    &lt;style&gt;.header1 header:after { content: "Header 1 Example"; }&lt;/style&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
    &lt;/section&gt;
&lt;/section&gt;

    
    

	
</t>
<t tx="leo.20160110142417.9">&lt;&lt; header &gt;&gt;

        &lt;section&gt;
            &lt;h1&gt;作業Mission-14&lt;/h1&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;利用Creo組裝Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;將Creo繪製出的零件轉檔成.stl檔並放在GITHUB上&lt;/p&gt;
            &lt;p&gt;介紹Onshape&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="https://www.onshape.com/"&gt;Onshape網站&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;何謂工程??&lt;br&gt;Ans:利用科學方法解決問題的人&lt;/p&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;大致上都把零件繪製好了，大家也試著把零件組合起來，並且開始錄製部分影片，以及編輯個人網站。這次又介紹了一個新的繪圖軟體－Onshape，這個是直接放在網站上的，所以建立好就直接可以在遠端分享，感覺比較方便。&lt;/p&gt;
            &lt;p&gt;自評:75&lt;/p&gt;
        &lt;/section&gt;
        &lt;/section&gt;
&lt;/section&gt;</t>
<t tx="leo.20160110142419.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160110142419.11">&lt;&lt; header &gt;&gt;

    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;/section&gt;
&lt;/section&gt;
			
				
</t>
<t tx="leo.20160110142419.12">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "課程: 電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110142419.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160110142419.2">&lt;!--
cadp w12 講課內容投影片
--&gt;
</t>
<t tx="leo.20160110142419.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;CADP W12 課程內容&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20160110142419.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160110142419.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;

&lt;!-- 出現在每一頁的 header 格式 --&gt;

&lt;header style="position: absolute;top: 20px; left: 20px; font-size:20px;background-color: rgba(150,150,0,0.5)"&gt;&lt;/header&gt;

&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142419.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142419.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;&lt; header &gt;&gt;

    &lt;marquee direction="up" height="50" scrollamount="1"&gt;
本週要點:在Onshape上建立偕同，將組員加入，並傳到遠端&lt;/marquee&gt;
    &lt;style&gt;.header1 header:after { content: "Header 1 Example"; }&lt;/style&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
    &lt;/section&gt;
&lt;/section&gt;

    
    

	
</t>
<t tx="leo.20160110142419.9">&lt;&lt; header &gt;&gt;

        &lt;section&gt;
            &lt;h1&gt;作業Mission-15&lt;/h1&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;利用Onshape繪製 Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;在Onshape上建立偕同，將組員加入，並傳到遠端給老師&lt;/p&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;運用上次提到的Onshape開始繪製Nutcracker機構零件，一樣分組完成零件檔，並且一起偕同，但網路好像不太給力阿，還蠻卡的~下次還是自己帶筆電比較快!!&lt;/p&gt;
            &lt;p&gt;自評:75&lt;/p&gt;
        &lt;/section&gt;
        &lt;/section&gt;
&lt;/section&gt;</t>
<t tx="leo.20160110142422.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160110142422.11">&lt;&lt; header &gt;&gt;

    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;/section&gt;
&lt;/section&gt;
			
				
</t>
<t tx="leo.20160110142422.12">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "課程: 電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110142422.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160110142422.2">&lt;!--
cadp w12 講課內容投影片
--&gt;
</t>
<t tx="leo.20160110142422.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;CADP W12 課程內容&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20160110142422.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160110142422.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;

&lt;!-- 出現在每一頁的 header 格式 --&gt;

&lt;header style="position: absolute;top: 20px; left: 20px; font-size:20px;background-color: rgba(150,150,0,0.5)"&gt;&lt;/header&gt;

&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142422.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142422.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;&lt; header &gt;&gt;

    &lt;marquee direction="up" height="50" scrollamount="1"&gt;
本週要點:開始組裝Nutcracker機構及拍攝影片&lt;/marquee&gt;
    &lt;style&gt;.header1 header:after { content: "Header 1 Example"; }&lt;/style&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
    &lt;/section&gt;
&lt;/section&gt;

    
    

	
</t>
<t tx="leo.20160110142422.9">&lt;&lt; header &gt;&gt;

        &lt;section&gt;
            &lt;h1&gt;作業Mission-16&lt;/h1&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;利用Onshape繪製 Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;開始組裝Nutcracker機構及拍攝影片&lt;/p&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;好快呀，一年又要過去了，距離期末也不遠了，這學期又快過完了呢，時間感覺真的過得好快，一下子又過去了，這學期其實也學到了不少東西，每天雖然過得忙碌，卻很充實，期許之後能變得更厲害!!!&lt;/p&gt;
            &lt;p&gt;自評:80&lt;/p&gt;
        &lt;/section&gt;
        &lt;/section&gt;
&lt;/section&gt;</t>
<t tx="leo.20160110142424.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160110142424.11">&lt;&lt; header &gt;&gt;

    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;/section&gt;
&lt;/section&gt;
			
				
</t>
<t tx="leo.20160110142424.12">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110142424.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160110142424.2">&lt;!--
cadp w12 講課內容投影片
--&gt;
</t>
<t tx="leo.20160110142424.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;CADP W12 課程內容&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20160110142424.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160110142424.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;

&lt;!-- 出現在每一頁的 header 格式 --&gt;

&lt;header style="position: absolute;top: 20px; left: 20px; font-size:20px;background-color: rgba(150,150,0,0.5)"&gt;&lt;/header&gt;

&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142424.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142424.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;&lt; header &gt;&gt;

    &lt;marquee direction="up" height="50" scrollamount="1"&gt;
本週要點:上傳個週進度至個人、個人偕同及群組偕同&lt;/marquee&gt;
    &lt;style&gt;.header1 header:after { content: "Header 1 Example"; }&lt;/style&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
    &lt;/section&gt;
&lt;/section&gt;

    
    

	
</t>
<t tx="leo.20160110142424.9">&lt;&lt; header &gt;&gt;

        &lt;section&gt;
            &lt;h1&gt;作業Mission-17&lt;/h1&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;編輯個人偕同倉儲網站&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150/"&gt;2015FALL C.A.D.P_A－40323150&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;CADP-二甲組員連結:&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/2015cp_hw_w7.html"&gt;2015 電腦輔助設計實習甲班 W7 示範&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;編輯組別偕同倉儲網站&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/g8.html"&gt;2015FALL CADPA 作業主頁－G8&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;CADP-各組連結:&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/cadpa-ke-cheng.html"&gt;2015FALL CADPA 作業主頁&lt;/a&gt;&lt;/p&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;最後一週了，總結這學期所學的，不論是個人、個人偕同倉儲還增加了一個組別偕同倉儲，用CREO及ONSHAPE組合了一個機構，使用fix建立環境模式(雖然之後都懶得用，直接帶自己的電腦)，投影片HEADER和跑馬燈等，這學期又要過完了，學習永不停止，加油!!!&lt;/p&gt;
            &lt;p&gt;自評:85&lt;/p&gt;
        &lt;/section&gt;
        &lt;/section&gt;
&lt;/section&gt;</t>
<t tx="leo.20160110142538.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160110142538.11">&lt;&lt; header &gt;&gt;

    &lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;h3&gt;created by Cheng hong&lt;/h3&gt;
    &lt;/section&gt;
&lt;/section&gt;
			
				
</t>
<t tx="leo.20160110142538.12">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110142538.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160110142538.2">&lt;!--
cadp w12 講課內容投影片
--&gt;
</t>
<t tx="leo.20160110142538.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;CADP W12 課程內容&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20160110142538.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160110142538.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;

&lt;!-- 出現在每一頁的 header 格式 --&gt;

&lt;header style="position: absolute;top: 20px; left: 20px; font-size:20px;background-color: rgba(150,150,0,0.5)"&gt;&lt;/header&gt;

&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142538.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160110142538.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;&lt; header &gt;&gt;

    &lt;section id="hw-task-one"&gt;
    &lt;p&gt;&lt;font size="5" color= "ffff00"&gt;&lt;marquee direction="down" width="400" height="200" behavior="alternate" style="border:solid"&gt;
  &lt;marquee behavior="alternate"&gt;
    #期末報告總結
  &lt;/marquee&gt;
&lt;/marquee&gt;&lt;/font&gt;&lt;/p&gt;
    &lt;style&gt;.header1 header:after { content: "Header 1 Example"; }&lt;/style&gt;
    &lt;h1&gt;
    &lt;small&gt;
    電腦輔助設計實習
    &lt;/small&gt;
    &lt;/h1&gt; 
   &lt;p&gt;&lt;strong&gt;#Class/#Number/#Name&lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;四設計二甲 40323150 詹晟弘&lt;/p&gt;		
    &lt;/section&gt;
&lt;/section&gt;

    
    

	
</t>
<t tx="leo.20160110160539.1">&lt;&lt; header &gt;&gt;
    &lt;h1&gt;&lt;small&gt;◎目錄&lt;/small&gt;&lt;/h1&gt;
    
				
</t>
<t tx="leo.20160110160613.1">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110160650.1">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;
					</t>
<t tx="leo.20160110160650.10">&lt;li&gt;&lt;p&gt;&lt;small&gt;Creo實作影片&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160110160650.2">&lt;li&gt;&lt;p&gt;&lt;small&gt;W11-建立群組偕同倉儲&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;
   </t>
<t tx="leo.20160110160650.3">&lt;li&gt;&lt;p&gt;&lt;small&gt;W12-利用Creo繪製 Nutcracker機構零件&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160110160650.4">&lt;li&gt;&lt;p&gt;&lt;small&gt;W13-利用Creo繪製 Nutcracker機構零件&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160110160650.5">&lt;li&gt;&lt;p&gt;&lt;small&gt;W14-利用Creo組合Nutcracker機構&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160110160650.6">&lt;li&gt;&lt;p&gt;&lt;small&gt;W15-利用Onshape繪製 Nutcracker機構零件&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160110160650.7">&lt;li&gt;&lt;p&gt;&lt;small&gt;W16-利用Onshape繪製 Nutcracker機構零件&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160110160650.8">&lt;li&gt;&lt;p&gt;&lt;small&gt;W17-利用Onshape組合Nutcracker機構&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160110160650.9">&lt;li&gt;&lt;p&gt;&lt;small&gt;期末總結&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160110201657.1">&lt;li&gt;&lt;p&gt;&lt;small&gt;Onshape實作影片&lt;/small&gt;&lt;/p&gt;&lt;/li&gt;</t>
<t tx="leo.20160110214844.1">&lt;&lt; header &gt;&gt;

    &lt;section&gt;
    &lt;h1&gt;作業Mission-11&lt;/h1&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;1.期中過後介紹接下來程序&lt;/p&gt;
            &lt;p&gt;2.介紹Nutcracker機構零件，並使用Creo繪製&lt;/p&gt;
            &lt;p&gt;3.開始分組，使用組別完成各自進度並上傳至群組網站&lt;/p&gt;
    &lt;/section&gt;
     &lt;section&gt;
     &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;經過半個學期了，考完期中考後，雖然是放下了心中一顆石頭，但過了不久這學期感覺就要結束了，總之希望能把期中那份熱情繼續延續下去。&lt;/p&gt;
            &lt;p&gt;自評分數:75分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20160110215042.1">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110215101.1">&lt;&lt; header &gt;&gt;

    &lt;section&gt;
    &lt;h1&gt;作業Mission-12&lt;/h1&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;1.利用Creo繪製 Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;2.Nutcracker機構零件&lt;/p&gt; 
            &lt;p&gt;連結請參考:&lt;a href="https://copy.com/DXQiGkDoe9K8Cz7m"&gt;Nutcracker機構零件&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;3.各組協同網站:&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/"&gt;2015FALL CADPA 作業主頁&lt;/a&gt;&lt;/p&gt;
        &lt;/section&gt;
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;找完組員後，分配各自的工作，開始用Creo繪製Nutcracker機構零件，這週開始要把之前user的節點刪除，得自己編輯新的節點才能備份之前的資料，以及建立新的節點。&lt;/p&gt;
            &lt;p&gt;自評分數:80分&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20160110215101.2">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110215103.1">&lt;&lt; header &gt;&gt;

    &lt;section&gt;
    &lt;h1&gt;作業Mission-13&lt;/h1&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;1.利用Creo繪製 Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;2.利用fix.bat修復程式環境 開啟Leo編輯倉儲&lt;/p&gt;
            &lt;p&gt;3.利用leo編輯個人及群組倉儲&lt;/p&gt;
            &lt;p&gt;4.介紹Header用法&lt;/p&gt;
        &lt;/section&gt;     
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;介紹了投影片新的用法－header 能將自己的學號固定顯示在投影片上方，也說到了跑馬燈，試了幾個玩一玩，效果感覺還不錯!!對之後製作心得等應該會有很大的用途~~&lt;/p&gt;
            &lt;p&gt;自評:80&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20160110215103.2">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110215105.1">&lt;&lt; header &gt;&gt;

    &lt;section&gt;
    &lt;h1&gt;作業Mission-14&lt;/h1&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;1.利用Creo組裝Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;2.將Creo繪製出的零件轉檔成.stl檔並放在GITHUB上&lt;/p&gt;
            &lt;p&gt;3.介紹Onshape&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="https://www.onshape.com/"&gt;Onshape網站&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;4.何謂工程??&lt;br&gt;Ans:利用科學方法解決問題的人&lt;/p&gt;
        &lt;/section&gt;
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;大致上都把零件繪製好了，大家也試著把零件組合起來，並且開始錄製部分影片，以及編輯個人網站。這次又介紹了一個新的繪圖軟體－Onshape，這個是直接放在網站上的，所以建立好就直接可以在遠端分享，感覺比較方便。&lt;/p&gt;
            &lt;p&gt;自評:75&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20160110215105.2">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110215108.1">&lt;&lt; header &gt;&gt;

    &lt;section&gt;
    &lt;h1&gt;作業Mission-15&lt;/h1&gt;
    &lt;/section&gt;
    &lt;section&gt;
     &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;1.利用Onshape繪製 Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;2.在Onshape上建立偕同，將組員加入，並傳到遠端給老師&lt;/p&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;運用上次提到的Onshape開始繪製Nutcracker機構零件，一樣分組完成零件檔，並且一起偕同，但網路好像不太給力阿，還蠻卡的~下次還是自己帶筆電比較快!!&lt;/p&gt;
            &lt;p&gt;自評:75&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20160110215108.2">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110215110.1">&lt;&lt; header &gt;&gt;

    &lt;section&gt;
    &lt;h1&gt;作業Mission-16&lt;/h1&gt;
    &lt;/section&gt;
    &lt;section&gt;
   &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;1.利用Onshape繪製 Nutcracker機構零件&lt;/p&gt;
            &lt;p&gt;2.開始組裝Nutcracker機構及拍攝影片&lt;/p&gt;
        &lt;/section&gt;      
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;好快呀，一年又要過去了，距離期末也不遠了，這學期又快過完了呢，時間感覺真的過得好快，一下子又過去了，這學期其實也學到了不少東西，每天雖然過得忙碌，卻很充實，期許之後能變得更厲害!!!&lt;/p&gt;
            &lt;p&gt;自評:80&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20160110215110.2">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110215112.1">&lt;&lt; header &gt;&gt;

    &lt;section&gt;
    &lt;h1&gt;作業Mission-17&lt;/h1&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;&lt;small&gt;筆記 note／行程 Schedule&lt;/small&gt;&lt;/h2&gt; 
            &lt;p&gt;1.開始編輯個人偕同倉儲網站&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323150/"&gt;2015FALL C.A.D.P_A－40323150&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;2.CADP-二甲組員連結:&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/2015cp_hw_w7.html"&gt;2015 電腦輔助設計實習甲班 W7 示範&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;3.編輯組別偕同倉儲網站&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/g8.html"&gt;2015FALL CADPA 作業主頁－G8&lt;/a&gt;&lt;/p&gt;
            &lt;p&gt;4.CADP-各組連結:&lt;/p&gt;
            &lt;p&gt;連結請參考:&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/cadpa-ke-cheng.html"&gt;2015FALL CADPA 作業主頁&lt;/a&gt;&lt;/p&gt;
        &lt;/section&gt;
        
        &lt;section&gt;
            &lt;h1&gt;&lt;small&gt;成績自評分數＆心得&lt;/small&gt;&lt;/h1&gt;
            &lt;p&gt;最後一週了，總結這學期所學的，不論是個人、個人偕同倉儲還增加了一個組別偕同倉儲，用CREO及ONSHAPE組合了一個機構，使用fix建立環境模式(雖然之後都懶得用，直接帶自己的電腦)，投影片HEADER和跑馬燈等，這學期又要過完了，學習永不停止，加油!!!&lt;/p&gt;
            &lt;p&gt;自評:85&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;
    				
</t>
<t tx="leo.20160110215112.2">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110215114.1">&lt;&lt; header &gt;&gt;

&lt;section&gt;
&lt;h2&gt;Creo實作影片回顧&lt;/h2&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;Nutcracker機構-Assembly&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150985599" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;BASE&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150805720" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;HINGE&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150805725" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;ADJUSTER BASE&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150805726" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;CYLINDER&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150805722" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;PISTON&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150805724" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;ADJUSTER&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150805723" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;CONNECTION&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150808153" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;HANDLE&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150808152" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
&lt;/section&gt;    				
</t>
<t tx="leo.20160110215114.2">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
<t tx="leo.20160110215116.1">&lt;&lt; header &gt;&gt;

&lt;section&gt;
&lt;h2&gt;Onshape實作影片回顧&lt;/h2&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;Nutcracker機構-Assembly&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150931846" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;BASE&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150932966" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;HINGE&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150927520" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;ADJUSTER BASE&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150927515" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;CYLINDER&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150927519" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;PISTON&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150927521" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;ADJUSTER&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150933506" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;CONNECTION&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150927526" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
    &lt;section&gt;
    &lt;h2&gt;HANDLE&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/150927524" width="9000" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/section&gt;
&lt;/section&gt;    				

</t>
<t tx="leo.20160110215116.2">&lt;section data-state="header1"&gt;
&lt;style&gt;.header1 header:after { content: "電腦輔助設計實習A 學號: 40323150"; }&lt;/style&gt;</t>
</tnodes>
</leo_file>
